// ============================================================
// library.js — study-library catalog + object-URL resolution
// ============================================================
// The catalog is a Supabase table (public.library_docs). The bytes live in an
// object store, never in the repo and never in `public/`: that directory is
// already 157 MB of tracked figures, and Vercel's Hobby bandwidth is a hard
// stop rather than an overage — one popular textbook could take the whole app
// offline for the rest of the month, mid-exam.
//
// Two providers, chosen per row:
//
//   'supabase' → private bucket + createSignedUrl(). Zero new infrastructure,
//                same shape as CaseLibrary's lab-dicom reads. Egress billed.
//   'r2'       → Cloudflare R2 behind a custom domain named by
//                VITE_LIBRARY_CDN_BASE. Egress is free and the edge caches
//                content-addressed keys forever, so the marginal cost of a
//                second reader is zero.
//
// Moving a document between providers is a column update plus a re-upload; no
// caller in this module or in LibraryView knows which one it got.
// ============================================================

// Vite statically replaces `import.meta.env`. Under plain node (unit tests) it
// is undefined, so every read goes through optional chaining and the module
// stays importable outside the bundler.
const CDN_BASE = import.meta.env?.VITE_LIBRARY_CDN_BASE || '';

// Signed URLs are short-lived on purpose. Ten minutes is long enough to open a
// large PDF over a slow campus connection and short enough that a URL pasted
// into a group chat stops working before it spreads. Matches lab-dicom.
const SIGNED_URL_TTL_SEC = 600;

export const LIBRARY_BUCKET_DEFAULT = 'library-docs';

// Column list kept explicit (not `*`) so a future private column added to
// library_docs cannot leak into the client by accident.
const CATALOG_COLUMNS = [
  'id', 'slug', 'title', 'description',
  'kind', 'subject', 'year', 'topics', 'lang',
  'storage_provider', 'storage_bucket', 'storage_key',
  'mime', 'byte_size', 'page_count', 'sha256_16', 'linearized',
  'license', 'source_url', 'attribution',
  'status', 'created_at', 'updated_at',
].join(', ');

export const LIBRARY_KINDS = Object.freeze([
  { id: 'all', label: 'ทั้งหมด' },
  { id: 'handout', label: 'เอกสารประกอบ' },
  { id: 'slide', label: 'สไลด์' },
  { id: 'summary', label: 'สรุป' },
  { id: 'textbook', label: 'ตำรา' },
  { id: 'pastpaper', label: 'ข้อสอบเก่า' },
  { id: 'guideline', label: 'แนวปฏิบัติ' },
  { id: 'other', label: 'อื่นๆ' },
]);

const KIND_LABELS = new Map(LIBRARY_KINDS.map((k) => [k.id, k.label]));

export function kindLabel(kind) {
  return KIND_LABELS.get(kind) || KIND_LABELS.get('other');
}

// ── Pure helpers (unit-tested without a network or a bundler) ──────────────

export function formatBytes(bytes) {
  const n = Number(bytes);
  if (!Number.isFinite(n) || n <= 0) return '—';
  if (n < 1024) return `${n} B`;
  const mb = n / (1024 * 1024);
  if (mb < 1) return `${(n / 1024).toFixed(0)} KB`;
  if (mb < 1024) return `${mb.toFixed(mb < 10 ? 1 : 0)} MB`;
  return `${(mb / 1024).toFixed(1)} GB`;
}

// Reject anything that is not an absolute https origin, and strip trailing
// slashes so joining never produces a double slash. A misconfigured base that
// silently became a relative path would make every object URL resolve against
// vetmock.vercel.app and 404 — worth failing loudly at the boundary instead.
export function normalizeCdnBase(base) {
  if (typeof base !== 'string' || !base.trim()) return '';
  const trimmed = base.trim().replace(/\/+$/, '');
  if (!/^https:\/\/[^/\s]+/i.test(trimmed)) return '';
  return trimmed;
}

// Storage keys are content-addressed (`docs/<sha256_16>/<safe-name>.pdf`) and
// generated by the ingest script, but they arrive here from the database, so
// they are still normalized before being pasted into a URL: a leading slash or
// a `..` segment would let a bad row reach outside the intended prefix.
export function isSafeStorageKey(key) {
  if (typeof key !== 'string' || !key) return false;
  if (key.startsWith('/') || key.includes('//')) return false;
  if (key.split('/').some((seg) => seg === '' || seg === '.' || seg === '..')) return false;
  return !/[\s?#]/.test(key);
}

export function cdnUrlFor(doc, base = CDN_BASE) {
  const root = normalizeCdnBase(base);
  if (!root) return null;
  if (!doc || !isSafeStorageKey(doc.storage_key)) return null;
  return `${root}/${doc.storage_key.split('/').map(encodeURIComponent).join('/')}`;
}

// A document can be range-streamed when the object store honours Range and the
// PDF was linearized at ingest. Both R2 and Supabase Storage serve ranges, so
// the deciding factor is linearization: without it pdf.js would issue dozens of
// small ranges chasing a cross-reference table at the end of the file, which is
// slower than one sequential download.
export function canStream(doc) {
  return !!(doc && doc.linearized && doc.mime === 'application/pdf');
}

// Search index. Lowercasing every field of every row on every keystroke is
// the recurring perf bug on this codebase (CommandPalette, FacultyView,
// NotesView all had it): the haystack is built and lowered ONCE here, and the
// hot path does a single indexOf per row. Same shape as FacultyView's
// instructorIndex.
export function indexDocs(docs) {
  return (Array.isArray(docs) ? docs : []).map((doc) => ({
    doc,
    _hayLc: [
      doc.title, doc.description, doc.subject, doc.attribution,
      kindLabel(doc.kind),
      ...(Array.isArray(doc.topics) ? doc.topics : []),
    ].filter(Boolean).join(' ').toLowerCase(),
  }));
}

export function filterIndexed(index, { query = '', kind = 'all', subject = 'all', year = 'all' } = {}) {
  const qlc = (query || '').trim().toLowerCase();
  const terms = qlc ? qlc.split(/\s+/) : null;
  const out = [];
  for (const entry of (Array.isArray(index) ? index : [])) {
    const d = entry.doc;
    if (kind !== 'all' && d.kind !== kind) continue;
    if (subject !== 'all' && d.subject !== subject) continue;
    if (year !== 'all' && String(d.year) !== String(year)) continue;
    if (terms && !terms.every((t) => entry._hayLc.includes(t))) continue;
    out.push(d);
  }
  return out;
}

// ── Catalog access ────────────────────────────────────────────────────────

// Pre-migration state — the table does not exist yet — must look like an empty
// shelf, not like a broken app. Same reasoning as CaseLibrary: a student who
// opens the library before the migration lands should see "ยังไม่มีเอกสาร",
// not a red error they cannot act on.
function isPreMigration(err) {
  const msg = err?.message || String(err || '');
  return /schema cache|library_docs|does not exist|relation .* does not exist/i.test(msg);
}

export async function fetchLibraryDocs() {
  const { hasSupabase, getSupabase } = await import('./supabase.js');
  if (!hasSupabase) return { docs: [], configured: false };

  const sb = await getSupabase();
  const { data, error } = await sb
    .from('library_docs')
    .select(CATALOG_COLUMNS)
    .order('year', { ascending: true, nullsFirst: false })
    .order('title', { ascending: true });

  if (error) {
    if (isPreMigration(error)) return { docs: [], configured: true };
    throw error;
  }
  // RLS already restricts rows to public (anon) or public+restricted (signed
  // in). Archived rows can only appear through a service-role client, which
  // the browser never has, but filtering here keeps the view honest if that
  // ever changes.
  return { docs: (data || []).filter((d) => d.status !== 'archived'), configured: true };
}

// Resolves a catalog row to a fetchable URL.
//
// R2 rows resolve to a permanent public CDN URL — the key is content-addressed
// and served `immutable`, so it caches at the edge and in the browser forever.
// Supabase rows are signed per open, which is why the bucket can stay private.
export async function resolveDocUrl(doc) {
  if (!doc) throw new Error('resolveDocUrl: missing doc');

  if (doc.storage_provider === 'r2') {
    const url = cdnUrlFor(doc);
    if (!url) {
      throw new Error('คลังไฟล์ยังไม่ได้ตั้งค่า CDN (VITE_LIBRARY_CDN_BASE)');
    }
    return url;
  }

  if (!isSafeStorageKey(doc.storage_key)) {
    throw new Error('เส้นทางไฟล์ไม่ถูกต้อง');
  }
  const { getSupabase } = await import('./supabase.js');
  const sb = await getSupabase();
  const { data, error } = await sb.storage
    .from(doc.storage_bucket || LIBRARY_BUCKET_DEFAULT)
    .createSignedUrl(doc.storage_key, SIGNED_URL_TTL_SEC);
  if (error) throw new Error(`ขอลิงก์ไฟล์ไม่สำเร็จ: ${error.message}`);
  return data.signedUrl;
}
