"""Cross-check values for Research Studio M1 methods, computed with SciPy/NumPy.

Written by the architect on 2026-09-27 (docs/research/M1-DESIGN.md section 13). These are a SECOND,
independent implementation, not the pin: the pin for every method is R 4.6.0 (tests/fixtures/r/,
generated by the rparity role) or a published source (NIST StRD, the course deck, the serosurvey
numbers checked by work/research-studio/workspace/check.py). A method's fixture test should assert
against R and against these values; a disagreement between R and SciPy beyond tolerance is a bug
report, not a choice.

Every dataset below is defined here, literally, so no value depends on recalling a published table.
Closed forms are written out where SciPy has no function, and are marked "formula".

Run:  PYTHONIOENCODING=utf-8 python scipy_crosscheck.py  (writes scipy-crosscheck.json beside it)
"""
import json
import math
import platform
from pathlib import Path

import numpy as np
import scipy
from scipy import stats
from scipy.stats.contingency import odds_ratio

HERE = Path(__file__).parent
OUT = {}
Z975 = stats.norm.ppf(0.975)


def f(x):
    """Full-precision float for JSON; None for nan; the strings Infinity/-Infinity for infinities."""
    x = float(x)
    if math.isnan(x):
        return None
    if math.isinf(x):
        return "Infinity" if x > 0 else "-Infinity"
    return x


# ---------------------------------------------------------------- datasets (defined here)
DS = {
    # two independent groups, no value shared between groups, no ties within
    "two": {"g1": [5.1, 4.9, 6.2, 5.8, 6.0, 5.5, 5.3, 6.4],
            "g2": [6.8, 7.1, 6.5, 7.4, 6.9, 7.8, 6.25, 7.0, 7.3, 6.6]},
    # paired before/after, differences all distinct and non-zero
    "paired": {"before": [12.1, 14.3, 11.8, 13.5, 15.2, 12.9, 14.8, 13.1, 12.4, 14.0],
               "after": [11.4, 13.9, 11.9, 12.2, 14.1, 12.0, 14.5, 12.3, 12.6, 13.25]},
    # three groups, unequal n, with ties inside and across groups
    "three": {"A": [23, 25, 21, 27, 24], "B": [30, 28, 33, 29, 31, 27], "C": [26, 24, 28, 25, 29, 30, 27]},
    # correlation, no ties in x or y
    "corr": {"x": [1.2, 2.3, 3.1, 4.8, 5.0, 6.7, 7.1, 8.4, 9.0, 10.5],
             "y": [2.1, 2.9, 3.8, 5.2, 4.9, 7.3, 6.8, 8.9, 9.5, 10.1]},
    "quantiles": [2, 4, 4, 5, 7, 9, 10, 12],
}
OUT["datasets"] = DS

# ---------------------------------------------------------------- t-tests
g1, g2 = np.array(DS["two"]["g1"]), np.array(DS["two"]["g2"])
w = stats.ttest_ind(g1, g2, equal_var=False)
v1, v2, n1, n2 = g1.var(ddof=1), g2.var(ddof=1), len(g1), len(g2)
welch_df = (v1 / n1 + v2 / n2) ** 2 / ((v1 / n1) ** 2 / (n1 - 1) + (v2 / n2) ** 2 / (n2 - 1))
ci = w.confidence_interval(0.95)
OUT["tTest.welch"] = {"data": "two (x = g1, y = g2)", "R": "t.test(g1, g2)",
                      "t": f(w.statistic), "df": f(welch_df), "p": f(w.pvalue),
                      "meanDiff": f(g1.mean() - g2.mean()), "ci": [f(ci.low), f(ci.high)]}
p_ = stats.ttest_ind(g1, g2, equal_var=True)
ci = p_.confidence_interval(0.95)
OUT["tTest.pooled"] = {"data": "two", "R": "t.test(g1, g2, var.equal = TRUE)",
                       "t": f(p_.statistic), "df": n1 + n2 - 2, "p": f(p_.pvalue), "ci": [f(ci.low), f(ci.high)]}
b, a = np.array(DS["paired"]["before"]), np.array(DS["paired"]["after"])
pr = stats.ttest_rel(b, a)
ci = pr.confidence_interval(0.95)
OUT["tTest.paired"] = {"data": "paired (x = before, y = after)", "R": "t.test(before, after, paired = TRUE)",
                       "t": f(pr.statistic), "df": len(b) - 1, "p": f(pr.pvalue),
                       "meanDiff": f((b - a).mean()), "ci": [f(ci.low), f(ci.high)]}

# ---------------------------------------------------------------- one-way ANOVA and Tukey HSD
A, B, C = (np.array(DS["three"][k], dtype=float) for k in "ABC")
an = stats.f_oneway(A, B, C)
N = len(A) + len(B) + len(C)
OUT["anova1"] = {"data": "three", "R": "summary(aov(y ~ g))", "F": f(an.statistic), "df1": 2, "df2": N - 3, "p": f(an.pvalue)}
tk = stats.tukey_hsd(A, B, C)
tci = tk.confidence_interval(0.95)
OUT["anova1.tukey"] = {"data": "three", "R": "TukeyHSD(aov(y ~ g)) (diff = later level minus earlier)",
                       "note": "SciPy reports mean(i) - mean(j) for row i, column j; R's TukeyHSD row B-A is mean(B) - mean(A).",
                       "pairs": {}}
names = "ABC"
for i in range(3):
    for j in range(i + 1, 3):
        OUT["anova1.tukey"]["pairs"][f"{names[j]}-{names[i]}"] = {
            "diff": f(-tk.statistic[i, j]), "p": f(tk.pvalue[i, j]),
            "ci": [f(-tci.high[i, j]), f(-tci.low[i, j])]}

# ---------------------------------------------------------------- rank tests
mw = stats.mannwhitneyu(g1, g2, method="exact", alternative="two-sided")
OUT["mannWhitney.exact"] = {"data": "two", "R": "wilcox.test(g1, g2)  (exact: n < 50 and no ties)",
                            "W": f(mw.statistic), "p": f(mw.pvalue)}
mwa = stats.mannwhitneyu(A, B, method="asymptotic", use_continuity=True, alternative="two-sided")
OUT["mannWhitney.normalTiesCC"] = {"data": "three: A vs B (ties)", "R": "wilcox.test(A, B, exact = FALSE, correct = TRUE)",
                                   "W": f(mwa.statistic), "p": f(mwa.pvalue)}
d = b - a
ranks = stats.rankdata(np.abs(d))
vplus = float(ranks[d > 0].sum())
wx = stats.wilcoxon(b, a, method="exact", alternative="two-sided")
OUT["wilcoxonSignedRank.exact"] = {"data": "paired", "R": "wilcox.test(before, after, paired = TRUE)",
                                   "V": vplus, "p": f(wx.pvalue),
                                   "note": "R's V is the sum of positive ranks; SciPy's two-sided statistic is min(V+, V-)."}
kw = stats.kruskal(A, B, C)
OUT["kruskalWallis"] = {"data": "three", "R": "kruskal.test(list(A, B, C))", "H": f(kw.statistic), "df": 2, "p": f(kw.pvalue)}

# ---------------------------------------------------------------- correlation
x, y = np.array(DS["corr"]["x"]), np.array(DS["corr"]["y"])
pe = stats.pearsonr(x, y)
pci = pe.confidence_interval(0.95)
OUT["corr.pearson"] = {"data": "corr", "R": "cor.test(x, y)", "r": f(pe.statistic), "p": f(pe.pvalue),
                       "ciFisherZ": [f(pci.low), f(pci.high)], "df": len(x) - 2}
sp = stats.spearmanr(x, y)
OUT["corr.spearman"] = {"data": "corr", "R": "cor.test(x, y, method = 'spearman')",
                        "rho": f(sp.statistic),
                        "pTApprox": f(sp.pvalue),
                        "note": "R's default p for n < 1290 without ties comes from prho (AS 89), not the t approximation; pin p to R only."}
lr = stats.linregress(x, y)
OUT["ols.simple"] = {"data": "corr (y on x)", "R": "summary(lm(y ~ x))",
                     "slope": f(lr.slope), "intercept": f(lr.intercept), "slopeSE": f(lr.stderr),
                     "interceptSE": f(lr.intercept_stderr), "r2": f(lr.rvalue ** 2), "pSlope": f(lr.pvalue)}

# ---------------------------------------------------------------- descriptives
q = np.array(DS["quantiles"], dtype=float)
OUT["desc.quantiles"] = {"data": "quantiles", "R": "quantile(v, c(.25,.5,.75), type = 7) and type = 6",
                         "mean": f(q.mean()), "sd": f(q.std(ddof=1)), "se": f(q.std(ddof=1) / math.sqrt(len(q))),
                         "type7": [f(v) for v in np.quantile(q, [0.25, 0.5, 0.75], method="linear")],
                         "type6": [f(v) for v in np.quantile(q, [0.25, 0.5, 0.75], method="weibull")]}

# ---------------------------------------------------------------- proportions
for label, xx, nn in [("17of179", 17, 179), ("0of20", 0, 20), ("20of20", 20, 20)]:
    bt = stats.binomtest(xx, nn)
    wi, ex = bt.proportion_ci(0.95, method="wilson"), bt.proportion_ci(0.95, method="exact")
    p0 = xx / nn
    se = math.sqrt(p0 * (1 - p0) / nn)
    OUT[f"proportion.{label}"] = {"R": f"binom.test({xx}, {nn}); prop.test({xx}, {nn}, correct = FALSE) for Wilson",
                                  "p": f(p0), "wilson": [f(wi.low), f(wi.high)], "exact": [f(ex.low), f(ex.high)],
                                  "wald": [f(p0 - Z975 * se), f(p0 + Z975 * se)]}

# ---------------------------------------------------------------- incidence rate (course 107006) with exact Poisson CI
cases, T = 7, 1089
OUT["incidenceRate.course107006"] = {"source": "course item 107006; CI formula", "R": "poisson.test(7, 1089)",
                                     "rate": f(cases / T), "per1000": f(1000 * cases / T),
                                     "exact": [f(stats.chi2.ppf(0.025, 2 * cases) / 2 / T), f(stats.chi2.ppf(0.975, 2 * cases + 2) / 2 / T)]}

# ---------------------------------------------------------------- chi-square
t22 = np.array([[116, 364], [27, 209]])  # serosurvey age >= 24 by ELISA (numbers.json assoc.table)
c0 = stats.chi2_contingency(t22, correction=False)
c1 = stats.chi2_contingency(t22, correction=True)
OUT["chisq.serosurvey2x2"] = {"R": "chisq.test(m, correct = FALSE / TRUE)",
                              "pearson": {"X2": f(c0.statistic), "p": f(c0.pvalue)},
                              "yates": {"X2": f(c1.statistic), "p": f(c1.pvalue)}, "minExpected": f(c0.expected_freq.min())}
trc = np.array([[20, 15, 10], [10, 20, 25]])
c2 = stats.chi2_contingency(trc, correction=False)
OUT["chisq.rxc"] = {"table": trc.tolist(), "R": "chisq.test(m)", "X2": f(c2.statistic), "df": int(c2.dof), "p": f(c2.pvalue)}

# ---------------------------------------------------------------- Fisher exact 2x2
for label, tab in [("tea", [[3, 1], [1, 3]]), ("zeroCell", [[7, 0], [2, 5]]), ("serosurvey", t22.tolist())]:
    two = stats.fisher_exact(tab, alternative="two-sided")
    gr = stats.fisher_exact(tab, alternative="greater")
    cor = odds_ratio(tab, kind="conditional")
    ci = cor.confidence_interval(0.95, alternative="two-sided")
    OUT[f"fisher.{label}"] = {"table": tab, "R": "fisher.test(m); fisher.test(m, alternative = 'greater')",
                              "pTwoSided": f(two.pvalue), "pGreater": f(gr.pvalue),
                              "conditionalMLE": f(cor.statistic), "exactCI": [f(ci.low), f(ci.high)]}
OUT["fisher.tea"]["closedForm"] = "pGreater = (C(4,3)C(4,1) + C(4,4)C(4,0)) / C(8,4) = 17/70"

# ---------------------------------------------------------------- McNemar (b = 15, c = 5)
bb, cc = 15, 5
OUT["mcnemar"] = {"table": [[30, 15], [5, 50]], "R": "mcnemar.test(m); mcnemar.test(m, correct = FALSE)",
                  "corrected": {"X2": (abs(bb - cc) - 1) ** 2 / (bb + cc), "p": f(stats.chi2.sf((abs(bb - cc) - 1) ** 2 / (bb + cc), 1))},
                  "uncorrected": {"X2": (bb - cc) ** 2 / (bb + cc), "p": f(stats.chi2.sf((bb - cc) ** 2 / (bb + cc), 1))},
                  "exactBinomial": {"p": f(min(1.0, 2 * stats.binom.cdf(min(bb, cc), bb + cc, 0.5)))}}

# ---------------------------------------------------------------- chi-square for trend (formula of R prop.trend.test)
tx, tn, ts = np.array([15, 10, 8, 4.0]), np.array([20, 20, 20, 20.0]), np.array([1, 2, 3, 4.0])
pbar = tx.sum() / tn.sum()
sbar = (tn * ts).sum() / tn.sum()
num = ((tn * (ts - sbar)) * (tx / tn - pbar)).sum() ** 2
den = pbar * (1 - pbar) * (tn * (ts - sbar) ** 2).sum()
OUT["trend"] = {"x": tx.tolist(), "n": tn.tolist(), "score": ts.tolist(), "R": "prop.trend.test(x, n)",
                "X2": f(num / den), "p": f(stats.chi2.sf(num / den, 1)), "formula": "weighted regression SS of x/n on score"}

# ---------------------------------------------------------------- 2x2 measures (formula) on two tables
def measures(a, b, c, d):
    n1, n0 = a + b, c + d
    r1, r0 = a / n1, c / n0
    rr = r1 / r0
    se_lrr = math.sqrt(1 / a - 1 / n1 + 1 / c - 1 / n0)
    orr = a * d / (b * c)
    se_lor = math.sqrt(1 / a + 1 / b + 1 / c + 1 / d)
    rd = r1 - r0
    se_rd = math.sqrt(r1 * (1 - r1) / n1 + r0 * (1 - r0) / n0)
    # Newcombe (1998) method 10: difference of Wilson intervals
    def wil(x, n):
        ci = stats.binomtest(x, n).proportion_ci(0.95, method="wilson")
        return ci.low, ci.high
    l1, u1 = wil(a, n1)
    l0, u0 = wil(c, n0)
    nlo = rd - math.sqrt((r1 - l1) ** 2 + (u0 - r0) ** 2)
    nhi = rd + math.sqrt((u1 - r1) ** 2 + (r0 - l0) ** 2)
    rt = (a + c) / (n1 + n0)
    return {"table": [[a, b], [c, d]],
            "risk1": f(r1), "risk0": f(r0),
            "RR": f(rr), "RR.waldLog": [f(rr * math.exp(-Z975 * se_lrr)), f(rr * math.exp(Z975 * se_lrr))],
            "OR": f(orr), "OR.woolf": [f(orr * math.exp(-Z975 * se_lor)), f(orr * math.exp(Z975 * se_lor))],
            "RD": f(rd), "RD.wald": [f(rd - Z975 * se_rd), f(rd + Z975 * se_rd)], "RD.newcombe10": [f(nlo), f(nhi)],
            "AFe": f((rr - 1) / rr), "AFp": f((rt - r0) / rt), "AFeFromOR": f((orr - 1) / orr)}


OUT["twoByTwo.serosurvey"] = {**measures(116, 364, 27, 209), "source": "numbers.json assoc.table (crudePR, crudePOR)"}
OUT["twoByTwo.small"] = {**measures(12, 8, 5, 15), "source": "defined here"}

# ---------------------------------------------------------------- Mantel-Haenszel on three strata defined here, Breslow-Day and Tarone (formula)
STRATA = [[[10, 20], [5, 25]], [[8, 12], [6, 24]], [[15, 5], [9, 11]]]
R_ = S_ = PR_ = PSQR = QS_ = 0.0
sa = sea = va = 0.0
for (a, b), (c, d) in STRATA:
    T_ = a + b + c + d
    r_, s_ = a * d / T_, b * c / T_
    P_, Q_ = (a + d) / T_, (b + c) / T_
    R_ += r_; S_ += s_; PR_ += P_ * r_; PSQR += P_ * s_ + Q_ * r_; QS_ += Q_ * s_
    m1, n1_, n0_ = a + c, a + b, c + d
    sa += a; sea += n1_ * m1 / T_
    va += n1_ * n0_ * m1 * (b + d) / (T_ ** 2 * (T_ - 1))
ormh = R_ / S_
vlog = PR_ / (2 * R_ ** 2) + PSQR / (2 * R_ * S_) + QS_ / (2 * S_ ** 2)


def expected_a(tab, psi):
    (a, b), (c, d) = tab
    n1_, n0_, m1 = a + b, c + d, a + c
    # solve e(n0 - m1 + e) = psi (n1 - e)(m1 - e) for e in the admissible range
    qa = 1 - psi
    qb = (n0_ - m1) + psi * (n1_ + m1)
    qc = -psi * n1_ * m1
    lo, hi = max(0, m1 - n0_), min(n1_, m1)
    roots = np.roots([qa, qb, qc]) if abs(qa) > 1e-15 else np.array([-qc / qb])
    root = [float(r.real) for r in np.atleast_1d(roots) if abs(r.imag) < 1e-12 and lo - 1e-9 <= r.real <= hi + 1e-9]
    return root[0]


bd = 0.0
sum_diff = sum_var = 0.0
for tab in STRATA:
    (a, b), (c, d) = tab
    e = expected_a(tab, ormh)
    n1_, n0_, m1 = a + b, c + d, a + c
    var = 1 / (1 / e + 1 / (n1_ - e) + 1 / (m1 - e) + 1 / (n0_ - m1 + e))
    bd += (a - e) ** 2 / var
    sum_diff += a - e
    sum_var += var
tarone = bd - sum_diff ** 2 / sum_var
cmh = (abs(sa - sea) - 0.5) ** 2 / va
OUT["mantelHaenszel.threeStrata"] = {
    "strata": STRATA, "R": "mantelhaen.test(array(...)); DescTools::BreslowDayTest(x, correct = TRUE)",
    "ORmh": f(ormh), "ciRGB": [f(ormh * math.exp(-Z975 * math.sqrt(vlog))), f(ormh * math.exp(Z975 * math.sqrt(vlog)))],
    "CMHcorrected": f(cmh), "pCMH": f(stats.chi2.sf(cmh, 1)),
    "breslowDay": f(bd), "pBreslowDay": f(stats.chi2.sf(bd, len(STRATA) - 1)),
    "tarone": f(tarone), "pTarone": f(stats.chi2.sf(tarone, len(STRATA) - 1))}

# ---------------------------------------------------------------- diagnostic accuracy (course 107013/107015 and 107014)
def dx(tp, fn, fp, tn):
    se, sp = tp / (tp + fn), tn / (tn + fp)
    lrp, lrn = se / (1 - sp), (1 - se) / sp
    sep = math.sqrt(1 / tp - 1 / (tp + fn) + 1 / fp - 1 / (fp + tn))
    sen = math.sqrt(1 / fn - 1 / (tp + fn) + 1 / tn - 1 / (fp + tn))
    out = {"TP": tp, "FN": fn, "FP": fp, "TN": tn,
           "Se": f(se), "Sp": f(sp), "PPV": f(tp / (tp + fp)), "NPV": f(tn / (tn + fn)),
           "accuracy": f((tp + tn) / (tp + fn + fp + tn)),
           "LRpos": f(lrp), "LRpos.log": [f(lrp * math.exp(-Z975 * sep)), f(lrp * math.exp(Z975 * sep))],
           "LRneg": f(lrn), "LRneg.log": [f(lrn * math.exp(-Z975 * sen)), f(lrn * math.exp(Z975 * sen))]}
    for k, (xx, nn) in {"Se": (tp, tp + fn), "Sp": (tn, tn + fp), "PPV": (tp, tp + fp), "NPV": (tn, tn + fn)}.items():
        bt = stats.binomtest(xx, nn)
        wi, ex = bt.proportion_ci(0.95, "wilson"), bt.proportion_ci(0.95, "exact")
        out[k + ".wilson"] = [f(wi.low), f(wi.high)]
        out[k + ".exact"] = [f(ex.low), f(ex.high)]
    return out


OUT["dx.course107013"] = {**dx(90, 10, 60, 120), "source": "course items 107013 and 107015 (same table)", "R": "epiR::epi.tests(as.table(matrix(c(90, 10, 60, 120), 2)))"}
OUT["dx.course107014"] = {**dx(32, 8, 16, 944), "source": "course item 107014 (FeLV)"}

# ---------------------------------------------------------------- kappa (formula)
K = np.array([[20, 5, 1], [4, 15, 6], [1, 3, 25]], dtype=float)
n = K.sum()
po = np.trace(K) / n
pe = (K.sum(1) * K.sum(0)).sum() / n ** 2
k_ = K.shape[0]
res = {"table": K.astype(int).tolist(), "R": "irr::kappa2(ratings, weight = 'unweighted' / 'equal' / 'squared')",
       "po": f(po), "kappa": f((po - pe) / (1 - pe))}
for name, wfun in [("linear", lambda i, j: 1 - abs(i - j) / (k_ - 1)), ("quadratic", lambda i, j: 1 - ((i - j) / (k_ - 1)) ** 2)]:
    W = np.array([[wfun(i, j) for j in range(k_)] for i in range(k_)])
    pow_ = (W * K).sum() / n
    pew = (W * np.outer(K.sum(1), K.sum(0))).sum() / n ** 2
    res[f"kappa.{name}"] = f((pow_ - pew) / (1 - pew))
OUT["kappa.threeLevel"] = res
K2 = np.array([[40, 9], [6, 45]], dtype=float)
n2 = K2.sum()
po2 = np.trace(K2) / n2
pe2 = (K2.sum(1) * K2.sum(0)).sum() / n2 ** 2
OUT["kappa.twoByTwo"] = {"table": K2.astype(int).tolist(), "R": "epiR::epi.kappa(m)", "po": f(po2), "kappa": f((po2 - pe2) / (1 - pe2)),
                         "PABAK": f(2 * po2 - 1), "prevalenceIndex": f(abs(K2[0, 0] - K2[1, 1]) / n2), "biasIndex": f(abs(K2[0, 1] - K2[1, 0]) / n2)}
OUT["agreement.course107027"] = {"source": "course item 107027", "agree": 865, "n": 986, "po": f(865 / 986)}

# ---------------------------------------------------------------- ICC (one-way ANOVA estimator, unequal clusters) for a continuous outcome
CL = {"F1": [4.1, 3.8, 4.5, 4.0], "F2": [5.2, 5.0, 4.8], "F3": [3.1, 3.5, 3.3, 2.9, 3.6], "F4": [4.4, 4.9]}
vals = np.concatenate([np.array(v) for v in CL.values()])
sizes = np.array([len(v) for v in CL.values()])
Ntot, kc = len(vals), len(CL)
gm = vals.mean()
msb = sum(len(v) * (np.mean(v) - gm) ** 2 for v in CL.values()) / (kc - 1)
msw = sum(((np.array(v) - np.mean(v)) ** 2).sum() for v in CL.values()) / (Ntot - kc)
n0 = (Ntot - (sizes ** 2).sum() / Ntot) / (kc - 1)
icc = (msb - msw) / (msb + (n0 - 1) * msw)
OUT["icc.continuous"] = {"clusters": CL, "R": "ICC::ICCest(cluster, y) (one-way ANOVA estimator); formula in base R",
                         "MSB": f(msb), "MSW": f(msw), "n0": f(n0), "ICC": f(icc),
                         "DEFFmeanSize": f(1 + (Ntot / kc - 1) * icc)}

# ---------------------------------------------------------------- multiplicity
pv = [0.01, 0.04, 0.03, 0.005]
order = np.argsort(pv)
m = len(pv)
holm = np.empty(m)
running = 0.0
for rank, idx in enumerate(order):
    running = max(running, min(1.0, (m - rank) * pv[idx]))
    holm[idx] = running
OUT["padjust"] = {"p": pv, "R": "p.adjust(p, 'holm'); p.adjust(p, 'bonferroni')",
                  "holm": [f(v) for v in holm], "bonferroni": [f(min(1.0, m * v)) for v in pv]}

# ---------------------------------------------------------------- true prevalence (Rogan-Gladen), closed form
OUT["truePrevalence.closedForm"] = {"AP": 0.2, "Se": 0.95, "Sp": 0.98, "TP": f((0.2 + 0.98 - 1) / (0.95 + 0.98 - 1))}

# ---------------------------------------------------------------- sample size, closed forms (course mode and the alternatives)
za, zb = stats.norm.ppf(0.975), stats.norm.ppf(0.8)
p0_, OR_ = 0.25, 3.0
p1_ = p0_ * OR_ / (1 + p0_ * (OR_ - 1))
pb = (p1_ + p0_) / 2
pooled = (za + zb) ** 2 * pb * (1 - pb) * 2 / (p1_ - p0_) ** 2
fl = (za * math.sqrt(2 * pb * (1 - pb)) + zb * math.sqrt(p1_ * (1 - p1_) + p0_ * (1 - p0_))) ** 2 / (p1_ - p0_) ** 2
flcc = fl / 4 * (1 + math.sqrt(1 + 4 / (fl * abs(p1_ - p0_)))) ** 2
OUT["sampleSize"] = {
    "zAlpha975": f(za), "zBeta80": f(zb),
    "caseControl.course107029": {"p1": f(p1_), "pooled": f(pooled), "fleiss": f(fl), "fleissCC": f(flcc), "courseAnswer": 59},
    "paired.course107035": {"d": 0.8, "normal": f((za + zb) ** 2 / 0.64), "courseAnswer": 13},
    "oneMean.course107036": {"sd": 0.5, "margin": 0.1, "zExact": f(za ** 2 * 0.25 / 0.01), "z196": f(1.96 ** 2 * 0.25 / 0.01), "courseAnswer": 97},
    "fpc.course107038": {"n0": 544, "N": 2000, "course": f(544 / (1 + 543 / 2000)), "epiR": f(544 / (1 + 544 / 2000)), "courseAnswer": 428},
    "deff.course107039": {"m": 15, "rho": 0.05, "deff": f(1 + 14 * 0.05), "n": f(428 * (1 + 14 * 0.05)), "courseAnswer": 728},
    "nonResponse.course107040": {"n": 200, "rate": 0.4, "adjusted": f(200 / 0.6), "courseAnswer": 334},
    "prevalence.p05d005": {"p": 0.5, "d": 0.05, "n": f(za ** 2 * 0.25 / 0.0025)},
}

OUT["_fixture"] = {"family": f"scipy-{scipy.__version__}", "kind": "crosscheck",
                   "methods": ["test.tTest", "test.anova1", "posthoc.tukey", "test.mannWhitney", "test.wilcoxonSignedRank",
                               "test.kruskalWallis", "corr.pearson", "corr.spearman", "reg.ols", "desc.summary", "freq.proportion",
                               "freq.incidenceRate", "test.chisq", "test.fisher2x2", "test.mcnemar", "test.trend", "epi.twoByTwo",
                               "epi.mantelHaenszel", "dx.accuracy", "agree.kappa", "agree.percent", "cluster.iccDeff",
                               "adjust.pValues", "freq.truePrevalence", "ss.caseControl", "ss.paired", "ss.mean", "ss.proportion"]}
OUT["_meta"] = {"written": "2026-09-27", "python": platform.python_version(), "numpy": np.__version__, "scipy": scipy.__version__,
                "role": "cross-check, not the pin; see M1-DESIGN.md section 13"}
(HERE / "scipy-crosscheck.json").write_text(json.dumps(OUT, ensure_ascii=False, indent=1), encoding="utf-8")
print("wrote", HERE / "scipy-crosscheck.json", len(OUT), "entries")
