// One-off helper: auto-generate .ds-entry.tsx + componentSrcMap for the
// presentational component set, so we don't hand-read every file's export
// style. Detects default + named PascalCase component exports via regex
// heuristics. The render check afterwards reveals which actually mount.
//
// Usage: node .ds-sync/gen-entry.mjs <component files...>
// (pass the pre-filtered file list as args)

import { readFileSync, writeFileSync } from 'node:fs';

const files = process.argv.slice(2).filter(Boolean);
if (!files.length) { console.error('no files given'); process.exit(1); }

const exportLines = [];
const srcMap = {};
const skipped = [];

// PascalCase names that are obviously NOT components (style/const maps, types).
const NON_COMPONENT = /^(VARIANT|ICON|TITLE|DESC|TIER|DEFAULT|TOOLTIP|CLASSES?)/;
const stripExt = (s) => s.replace(/\.[tj]sx?$/, '');

for (const f of files) {
  const slashed = f.replace(/\\/g, '/');
  const rel = './' + slashed.replace(/^.*?(src\/)/, '$1');
  const importPath = stripExt(rel);
  const src = readFileSync(f, 'utf8');

  const names = new Set();
  let hasDefault = null;

  // export default function/class Name
  let m = src.match(/export\s+default\s+(?:async\s+)?(?:function|class)\s+([A-Z][A-Za-z0-9]*)/);
  if (m) hasDefault = m[1];
  // export default Name;   (Name declared above)
  if (!hasDefault) { m = src.match(/export\s+default\s+([A-Z][A-Za-z0-9]*)\s*;/); if (m) hasDefault = m[1]; }
  // any other default form (arrow, memo, forwardRef, anonymous) -> name from filename
  if (!hasDefault && /export\s+default\b/.test(src)) {
    hasDefault = stripExt(slashed.replace(/^.*\//, ''));
  }

  // named: export function Name | export const Name = | export class Name
  for (const mm of src.matchAll(/export\s+(?:function|const|class)\s+([A-Z][A-Za-z0-9]*)/g)) {
    if (!NON_COMPONENT.test(mm[1])) names.add(mm[1]);
  }

  if (hasDefault && /^[A-Z][A-Za-z0-9]*$/.test(hasDefault)) {
    exportLines.push(`export { default as ${hasDefault} } from '${importPath}';`);
    srcMap[hasDefault] = rel;
  }
  const namedList = [...names];
  if (namedList.length) {
    exportLines.push(`export { ${namedList.join(', ')} } from '${importPath}';`);
    for (const n of namedList) srcMap[n] = rel;
  }
  if (!Object.values(srcMap).includes(rel)) skipped.push(rel);
}

const header = `// AUTO-GENERATED by gen-entry.mjs — curated design-system bundle entry.
// Only standalone-ish presentational components (no supabase/i18n at module load).
// Components that need live data still floor-card; ones that crash the IIFE get pruned.
`;
writeFileSync('.ds-entry.tsx', header + exportLines.join('\n') + '\n');

const cfg = JSON.parse(readFileSync('.design-sync/config.json', 'utf8'));
cfg.componentSrcMap = srcMap;
writeFileSync('.design-sync/config.json', JSON.stringify(cfg, null, 2) + '\n');

console.error(`entry: ${exportLines.length} re-export line(s), ${Object.keys(srcMap).length} component name(s)`);
console.error(`names: ${Object.keys(srcMap).sort().join(', ')}`);
if (skipped.length) console.error(`skipped (no detectable export): ${skipped.join(', ')}`);
