import { MOCHI_ACTIONS } from "./mochi/actions.js";
export const GROUPS = [
  { id: "mochi", name: "Mochi", en: "Mochi", symbol: "♡" },
  { id: "cursor", name: "เมาส์", en: "Cursors", symbol: "↗" },
  { id: "loading", name: "รอโหลด", en: "Loading", symbol: "◌" },
  { id: "interaction", name: "ปุ่มและการ์ด", en: "Interactions", symbol: "◇" },
  { id: "celebration", name: "ฉลอง", en: "Celebrations", symbol: "✦" },
  { id: "play", name: "เล่นพัก", en: "Play", symbol: "◒" },
  { id: "ambient", name: "บรรยากาศ", en: "Ambient", symbol: "≈" }
];
export const EFFECTS = [
  ["paw", "cursor", "Paw trail", "รอยอุ้งเท้าตามเมาส์", "เลื่อนเมาส์หรือแตะ แล้วทิ้งรอยอุ้งเท้าไว้ให้ Mochi", "↗"],
  ["halo", "cursor", "Soft halo", "วงแหวนตามมือ", "วงแหวนค่อย ๆ ตามปลายเมาส์ แตะเพื่อส่งคลื่น", "◎"],
  ["comet", "cursor", "Little comet", "ดาวหางจิ๋ว", "ลากให้เร็วขึ้นเพื่อทิ้งหางประกายที่ยาวขึ้น", "✧"],
  ["orbit", "cursor", "Orbit buddies", "ดาวโคจร", "จุดเล็กสามจุดหมุนรอบเมาส์ของคุณ", "◌"],
  ["mochi", "cursor", "Mochi follows", "Mochi ตามมา", "พา Mochi เดินเล่นด้วยเมาส์ หรือแตะจุดที่อยากให้น้องไป", "◒"],
  ["leaf", "cursor", "Leaf trail", "ใบไม้ปลิว", "ลากเมาส์ให้ใบไม้เล็ก ๆ หมุนเบา ๆ ตามทาง", "⌁"],
  ["ink", "cursor", "Study ink", "หมึกอ่านหนังสือ", "วาดเส้นด้วยเมาส์หรือลากนิ้ว เส้นจะค่อย ๆ จาง", "∿"],
  ["spotlight", "cursor", "Reading light", "แสงตามสายตา", "เลื่อนแสงไปตามพื้นที่ที่คุณกำลังอ่าน", "⌖"],
  ["pawsteps", "loading", "Paw steps", "อุ้งเท้าเดินรอ", "อุ้งเท้าค่อย ๆ เดินไปข้างหน้าระหว่างรอ", "••"],
  ["orbital", "loading", "Quiet orbit", "วงโคจร", "วงแหวนสองชั้นหมุนอย่างนุ่มนวล", "◎"],
  ["pages", "loading", "Page turn", "พลิกหน้า", "หน้ากระดาษเล็ก ๆ พลิกไปทีละหน้า", "▤"],
  ["heartbeat", "loading", "Little pulse", "จังหวะชีพจร", "เส้นชีพจรลากผ่านอย่างต่อเนื่อง", "⌁"],
  ["dots", "loading", "Thinking dots", "จุดกำลังคิด", "จุดสามจุดเด้งส่งต่อกัน", "•••"],
  ["helix", "loading", "DNA helix", "เกลียวดีเอ็นเอ", "จุดสองสายหมุนเป็นเกลียว", "⠿"],
  ["skeleton", "loading", "Content shimmer", "โครงเนื้อหารอโหลด", "แสงวิ่งผ่านตำแหน่งเนื้อหาที่กำลังเตรียม", "▥"],
  ["progress", "loading", "Paw progress", "แถบความคืบหน้า", "ลองปรับเปอร์เซ็นต์ในพื้นที่ตัวอย่าง", "▰"],
  ["magnet", "interaction", "Magnetic button", "ปุ่มดูดเมาส์", "เลื่อนเข้าใกล้ปุ่ม หรือแตะเพื่อกด", "↗"],
  ["tilt", "interaction", "Tilt card", "การ์ดมีมิติ", "เอียงการ์ดตามเมาส์ หรือแตะเพื่อให้การ์ดเด้ง", "◇"],
  ["ripple", "interaction", "Soft ripple", "คลื่นเมื่อกด", "คลิกหรือแตะตรงไหนก็เกิดคลื่นจากจุดนั้น", "◎"],
  ["flip", "interaction", "Flip flashcard", "พลิกแฟลชการ์ด", "กดการ์ดเพื่อสลับด้าน", "▱"],
  ["bookmark", "interaction", "Bookmark pop", "เด้งเมื่อบันทึก", "กดเพื่อบันทึกหรือยกเลิก พร้อมปุ่มเด้งรับ", "⌑"],
  ["reveal", "interaction", "Reveal answer", "เปิดเฉลย", "แตะเพื่อเปิดคำตอบด้วยแสงและการเลื่อนเบา ๆ", "≡"],
  ["retry", "interaction", "Gentle retry", "ลองใหม่อย่างนุ่มนวล", "กดแล้วปุ่มขยับเบา ๆ พร้อมคำให้กำลังใจ", "↺"],
  ["like", "interaction", "Heart pop", "หัวใจเด้ง", "กดหัวใจเพื่อส่งกำลังใจ", "♡"],
  ["accordion", "interaction", "Smooth details", "เปิดรายละเอียด", "เปิดรายละเอียดพร้อมข้อความค่อย ๆ ปรากฏ", "+"],
  ["toast", "interaction", "Saved toast", "แจ้งว่าบันทึกแล้ว", "กดบันทึกเพื่อแสดงข้อความยืนยันชั่วครู่", "✓"],
  ["confetti", "celebration", "Forest confetti", "กระดาษโปรย", "ฉลองด้วยกระดาษสีเขียว ครีม และทอง", "✦"],
  ["pawburst", "celebration", "Paw burst", "อุ้งเท้ากระจาย", "กดฉลองให้อุ้งเท้ากระจายรอบ Mochi", "✧"],
  ["fireflies", "celebration", "Firefly burst", "หิ่งห้อยลอย", "กดฉลองให้จุดแสงเล็ก ๆ ลอยรอบ Mochi", "⋆"],
  ["hearts", "celebration", "Floating hearts", "หัวใจลอย", "หัวใจค่อย ๆ ลอยขึ้นเมื่อส่งกำลังใจ", "♡"],
  ["streak", "celebration", "Study streak", "ฉลองความต่อเนื่อง", "ลองเอฟเฟกต์สำหรับความต่อเนื่องในการเรียน", "↟"],
  ["chapter", "celebration", "Chapter complete", "จบบทแล้ว", "ฉลองเมื่ออ่านจบด้วย Mochi และกระดาษโปรย", "✓"],
  ["fetch", "play", "Fetch with Mochi", "โยนบอลให้ Mochi", "แตะพื้นที่ว่างหรือกดโยนบอล ให้น้องวิ่งตาม", "●"],
  ["memory", "play", "Memory paws", "จับคู่ให้ครบ", "เปิดการ์ดหาสัญลักษณ์ที่เหมือนกัน 4 คู่", "▦"],
  ["bubbles", "play", "Bubble break", "จิ้มฟองพักสมอง", "แตะฟองให้แตก ลองเก็บให้ครบ 12 ฟอง", "○"],
  ["breath", "play", "Breathe together", "หายใจไปด้วยกัน", "กดเริ่ม วงกลมจะค่อย ๆ ขยายและหด", "◉"],
  ["rain", "ambient", "Window rain", "ฝนหลังหน้าต่าง", "ฝนเส้นบางสำหรับมุมอ่านหนังสือ", "╱"],
  ["glow", "ambient", "Firefly field", "สวนหิ่งห้อย", "ขยับเมาส์ให้แสงลอยเข้ามาทัก", "⋆"],
  ["garden", "ambient", "Orbit garden", "สวนดาวมีมิติ", "ขยับหรือลากเพื่อหมุนกลุ่มดาวในสามมิติ", "◌"],
  ["focus", "ambient", "Line focus", "โฟกัสทีละบรรทัด", "เลือกบรรทัดที่กำลังอ่าน แล้วค่อย ๆ ไปต่อ", "≡"]
].map(([id, group, name, th, hint, symbol]) => ({ id, group, name, th, hint, symbol }));
EFFECTS.unshift(...Object.entries(MOCHI_ACTIONS).map(([id, [state, name, th]], i) => ({ id, group: "mochi", name, th, hint: "เลือก 2D หรือ 3D แล้วเปลี่ยนท่าขณะ Mochi ขยับได้เลย", symbol: ["♡", "↗", "»", "↑", "♫", "☀", "☾", "z", "☀", "♡", "✦", "⌁", "∿", "?", "◒", "◌", "♥", "✋", "▤", "∞"][i] })));
