"""Independent recomputation of numbers.json from the raw bytes (Python + SciPy).

Shares no code with build-data.mjs: its own decoder (cp874), date parser, age rule and statistics.
Exit code 1 on any mismatch. Run: python check.py

Repo copy: identical to work/research-studio/workspace/check.py except that it reads the CSV beside
it (tests/fixtures/serosurvey/serosurvey-2569.csv, phone column regenerated by regen-phones.mjs).
"""
import csv, hashlib, io, json, math, sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
from scipy import stats
from scipy.stats.contingency import relative_risk, odds_ratio

HERE = Path(__file__).parent
raw = (HERE / "serosurvey-2569.csv").read_bytes()
N = json.loads((HERE / "numbers.json").read_text(encoding="utf-8"))
bad = []


def same(label, got, want, rel=1e-9):
    ok = (got == want) if isinstance(want, (str, bool)) or want is None else math.isclose(got, want, rel_tol=rel, abs_tol=1e-12)
    print(("ok  " if ok else "BAD ") + label, got, "" if ok else f"(numbers.json {want})")
    if not ok:
        bad.append(label)


# --- file ---
same("bytes", len(raw), N["file"]["bytes"])
same("sha256", hashlib.sha256(raw).hexdigest(), N["file"]["sha256"])
try:
    raw.decode("utf-8")
    utf8_fails = False
except UnicodeDecodeError:
    utf8_fails = True
same("utf-8 strict decode fails", utf8_fails, True)
text = raw.decode("cp874")
rows = list(csv.reader(io.StringIO(text)))
head, rows = rows[0], rows[1:]
same("rows", len(rows), N["file"]["rows"])
C = {h: i for i, h in enumerate(head)}
TH = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
MISS = {"ไม่ทราบ", "-", "", "999"}


def date(s):
    s = s.strip().translate(TH)
    d, m, y = s.split("/")
    y = int(y)
    if len(str(y)) == 2:
        y += 2500
    return (y - 543, int(m), int(d))


same("thai-digit cells", sum(any("๐" <= ch <= "๙" for ch in c) for r in rows for c in r), N["conv"]["thaiDigitCells"])
same("two-digit-year cells", sum(1 for r in rows if len(r[C["วันที่เก็บตัวอย่าง"]].split("/")[2]) == 2), N["conv"]["twoDigitYearCells"])
same("excel date ids", sum(1 for r in rows if r[C["รหัสโค"]].split("-")[-1] in ("Apr",)), len(N["conv"]["excelDateIds"]))
same("trailing spaces", sum(1 for r in rows if r[C["พันธุ์"]] != r[C["พันธุ์"]].strip()), N["conv"]["trailingSpaceCells"])
feb29 = [r for r in rows if r[C["วันเกิด"]] not in MISS and date(r[C["วันเกิด"]])[1:] == (2, 29)]
same("29 Feb birth dates", len(feb29), N["conv"]["feb29"]["count"])
for label, name, code in [("birth ไม่ทราบ", "วันเกิด", "ไม่ทราบ"), ("birth -", "วันเกิด", "-"), ("parity 999", "จำนวนครั้งที่คลอด", "999"), ("parity -", "จำนวนครั้งที่คลอด", "-"), ("vaccine ไม่ทราบ", "วัคซีนใน 6 เดือน", "ไม่ทราบ")]:
    same(label, sum(1 for r in rows if r[C[name]] == code), N["conv"]["missing"][name][code])

# --- per animal ---
A = []
for r in rows:
    s = date(r[C["วันที่เก็บตัวอย่าง"]])
    b = None if r[C["วันเกิด"]] in MISS else date(r[C["วันเกิด"]])
    age = None
    if b:
        age = (s[0] - b[0]) * 12 + (s[1] - b[1]) - (1 if s[2] < b[2] else 0)
    A.append(dict(farm=r[0], pos=r[C["ผล ELISA"]] == "บวก", age=age))
farms = sorted({a["farm"] for a in A})
x, n = sum(a["pos"] for a in A), len(A)
same("positives", x, N["prev"]["x"])
p = x / n
z = stats.norm.ppf(0.975)

# ICC, one-way ANOVA estimator with unequal cluster sizes
sizes = np.array([sum(1 for a in A if a["farm"] == f) for f in farms])
ys = np.array([sum(a["pos"] for a in A if a["farm"] == f) for f in farms])
k = len(farms)
pf = ys / sizes
msb = np.sum(sizes * (pf - p) ** 2) / (k - 1)
msw = np.sum(sizes * pf * (1 - pf)) / (n - k)
n0 = (n - np.sum(sizes ** 2) / n) / (k - 1)
icc = (msb - msw) / (msb + (n0 - 1) * msw)
deff = 1 + (n / k - 1) * icc
same("ICC", icc, N["prev"]["icc"])
same("DEFF", deff, N["prev"]["deff"])
se = math.sqrt(p * (1 - p) / n)
same("Wald independent lo", p - z * se, N["prev"]["waldIndependent"][0], 1e-7)
same("Wald DEFF hi", p + z * se * math.sqrt(deff), N["prev"]["waldDeff"][1], 1e-7)
w = stats.binomtest(x, n).proportion_ci(0.95, method="wilson")
same("Wilson lo", w.low, N["prev"]["wilsonIndependent"][0], 1e-7)
same("farms with a positive", int(np.sum(ys > 0)), N["prev"]["farmsWithPositive"])
se_, sp_ = 0.95, 0.98
same("true prevalence", (p + sp_ - 1) / (se_ + sp_ - 1), N["prev"]["trueP"]["p"])

# --- 2x2 on animals with a known age ---
K = [a for a in A if a["age"] is not None]
a_ = sum(1 for q in K if q["age"] >= 24 and q["pos"]); b_ = sum(1 for q in K if q["age"] >= 24 and not q["pos"])
c_ = sum(1 for q in K if q["age"] < 24 and q["pos"]); d_ = sum(1 for q in K if q["age"] < 24 and not q["pos"])
same("cell a", a_, N["assoc"]["table"]["a"]); same("cell b", b_, N["assoc"]["table"]["b"])
same("cell c", c_, N["assoc"]["table"]["c"]); same("cell d", d_, N["assoc"]["table"]["d"])
rr = relative_risk(a_, a_ + b_, c_, c_ + d_)
same("PR", rr.relative_risk, N["assoc"]["crudePR"]["est"])
ci = rr.confidence_interval(0.95)
same("PR lo", ci.low, N["assoc"]["crudePR"]["ci"][0], 1e-7)
same("PR hi", ci.high, N["assoc"]["crudePR"]["ci"][1], 1e-7)
orr = odds_ratio([[a_, b_], [c_, d_]], kind="sample")
same("POR", orr.statistic, N["assoc"]["crudePOR"]["est"])
oci = orr.confidence_interval(0.95)
same("POR lo", oci.low, N["assoc"]["crudePOR"]["ci"][0], 1e-7)
chi2, pchi, _, exp = stats.chi2_contingency([[a_, b_], [c_, d_]], correction=False)
same("naive chi-square", chi2, N["assoc"]["crudePR"]["chi"])
same("naive p", pchi, N["assoc"]["crudePR"]["pNaive"], 1e-7)
same("min expected", exp.min(), N["assoc"]["minExpected"])

# --- Mantel-Haenszel across farms, written out again ---
num = den = gr = R = S = PR = PSQR = QS = sa = se_a = va = 0.0
for f in farms:
    q = [a for a in K if a["farm"] == f]
    a1 = sum(1 for t in q if t["age"] >= 24 and t["pos"]); b1 = sum(1 for t in q if t["age"] >= 24 and not t["pos"])
    c1 = sum(1 for t in q if t["age"] < 24 and t["pos"]); d1 = sum(1 for t in q if t["age"] < 24 and not t["pos"])
    e1, e0, T = a1 + b1, c1 + d1, a1 + b1 + c1 + d1
    if T < 2:
        continue
    num += a1 * e0 / T; den += c1 * e1 / T
    gr += (e1 * e0 * (a1 + c1) - a1 * c1 * T) / T ** 2
    r_, s_ = a1 * d1 / T, b1 * c1 / T
    P_, Q_ = (a1 + d1) / T, (b1 + c1) / T
    R += r_; S += s_; PR += P_ * r_; PSQR += P_ * s_ + Q_ * r_; QS += Q_ * s_
    sa += a1; se_a += e1 * (a1 + c1) / T
    va += e1 * e0 * (a1 + c1) * (b1 + d1) / (T ** 2 * (T - 1))
prmh = num / den
same("MH PR", prmh, N["assoc"]["mh"]["pr"]["est"])
same("MH PR lo", prmh * math.exp(-z * math.sqrt(gr / (num * den))), N["assoc"]["mh"]["pr"]["ci"][0], 1e-7)
ormh = R / S
same("MH OR", ormh, N["assoc"]["mh"]["or"]["est"])
v = PR / (2 * R ** 2) + PSQR / (2 * R * S) + QS / (2 * S ** 2)
same("MH OR hi (RGB)", ormh * math.exp(z * math.sqrt(v)), N["assoc"]["mh"]["or"]["ci"][1], 1e-7)
cmh = (abs(sa - se_a) - 0.5) ** 2 / va
same("CMH (continuity corrected)", cmh, N["assoc"]["mh"]["cmh"])
same("CMH p", stats.chi2.sf(cmh, 1), N["assoc"]["mh"]["p"], 1e-7)

# --- Table 1 (numpy default quantile = R type 7) ---
ages = [a["age"] for a in A if a["age"] is not None]
same("age median", float(np.quantile(ages, 0.5)), N["table1"]["animals"]["all"]["age"][0])
same("age q3", float(np.quantile(ages, 0.75)), N["table1"]["animals"]["all"]["age"][2])
herd = [int(next(r[C["ขนาดฝูง (ตัว)"]] for r in rows if r[0] == f)) for f in farms]
same("herd size median", float(np.quantile(herd, 0.5)), N["table1"]["farms"]["herd"][0])

# --- course mode ---
zb = stats.norm.ppf(0.8)
p0, OR = 0.25, 3
p1 = OR * p0 / (1 + p0 * (OR - 1)); pb = (p1 + p0) / 2
same("course case-control pooled", (z + zb) ** 2 * pb * (1 - pb) * 2 / (p1 - p0) ** 2, N["course"]["caseControl"]["pooled"])
nf = (z * math.sqrt(2 * pb * (1 - pb)) + zb * math.sqrt(p0 * (1 - p0) + p1 * (1 - p1))) ** 2 / (p1 - p0) ** 2
same("Fleiss", nf, N["course"]["caseControl"]["fleiss"])
same("Fleiss + cc", nf / 4 * (1 + math.sqrt(1 + 4 / (nf * abs(p1 - p0)))) ** 2, N["course"]["caseControl"]["fleissCC"])
same("FPC (course)", 544 / (1 + 543 / 2000), N["course"]["fpc"]["course"])

print("\n" + ("ALL MATCH" if not bad else f"{len(bad)} MISMATCH: " + ", ".join(bad)))
sys.exit(1 if bad else 0)
