// ============================================================
// CommandPalette — ⌘K / Ctrl+K instant search-jump
// ============================================================
// Single keyboard shortcut → fuzzy search across:
//   • Quick actions (Dashboard, Schedule, Videos, Bookmarks, …)
//   • Subjects (COM III / IV / V / EngProf)
//   • Video summaries (by title)
//
// Lightweight, no external lib. Thai-friendly fuzzy match
// (substring + per-token + tolerance for word order).
//
// Wired in App.jsx via global keydown listener — only opens when
// the user is NOT typing in an input/textarea/contenteditable.
// ============================================================

import { useState, useEffect, useMemo, useRef } from 'react';
import { SUBJECTS } from '../data/curriculum.js';
// CommandPalette only needs {title, subject, instructor} for search —
// importing the full VIDEO_SUMMARIES dragged ~360 KB of markdown body
// text into the palette's lazy chunk. Switched to a lightweight meta
// index (auto-regenerated by scripts/regen-video-meta.mjs) so opening
// ⌘K stays snappy even on slow connections.
import { VIDEO_META as VIDEO_SUMMARIES } from '../data/video-summaries-meta.js';
import { ALL_INSTRUCTORS } from '../data/instructors.js';
// QB is already in the main bundle (App.jsx + HomeView import it eagerly),
// so adding it here doesn't grow the palette lazy chunk — it's deduped.
// Only the first 80 chars of q.q are added to the keyword string to keep
// fuzzy-filter cost bounded (~1999 Qs × short stem = manageable).
import { QB } from '../data/questions.js';
// User-authored flashcards (Highlight → Flashcard feature). Same
// module that owns the localStorage key, so we don't re-parse here.
import { loadUserFlashcards } from '../lib/user-flashcards.js';

// localStorage keys for user-authored content surfaced in the palette.
// Keeping the literals here mirrors the convention used by NotesView
// (the writer) — a single rename would touch both files, which is
// acceptable for two strings.
const NOTES_LS_KEY = 'vmx-notes';

// Cap on how many results we render at once. The full index has
// ~1700 items (mostly question stems). Rendering all of them as
// <button>s on every keystroke turned the palette into a noticeable
// freeze on slower phones. 80 fills the visible list comfortably and
// the user almost never scrolls past the top of the result set
// anyway — they refine the query instead.
const MAX_RESULTS = 80;

// ── Module-level cache for the static parts of the index ─────────
// The actual run() handlers depend on App.jsx's setState refs (fresh
// identity on every render of App), but the rest — label, hint, icon,
// keyword bag, pre-lowered haystack — is fully deterministic from
// imported data modules. Build that part ONCE per session and stash
// it. Opening the palette re-uses the same array; we only re-attach
// the run() closures per open.
let _staticItemsCache = null;

/**
 * Bust the module-level static index. Call this whenever
 * user-authored content (flashcards, per-Q notes, bookmarks) changes
 * outside the palette — the next open() rebuilds the index lazily.
 * Cheap and idempotent.
 */
export function invalidateCommandPaletteCache() {
  _staticItemsCache = null;
}

// Global hook: any code path can fire this event without importing
// us. user-flashcards.js dispatches it after save/delete; NotesView
// (or any future writer) can opt-in by dispatching the same event.
if (typeof window !== 'undefined') {
  window.addEventListener('vmx-palette-invalidate', () => {
    _staticItemsCache = null;
  });
}

// Truncate a label for the result row. The result button is a single
// line with ellipsis CSS, but we still cap at the source so the
// pre-lowered haystack stays small and tooltips don't blow up either.
const MAX_LABEL_LEN = 60;
function trunc(s) {
  const str = (s || '').toString().replace(/\s+/g, ' ').trim();
  return str.length > MAX_LABEL_LEN ? str.slice(0, MAX_LABEL_LEN - 1) + '…' : str;
}

// Safely read & JSON-parse a localStorage key. Returns fallback on
// any failure (corrupted JSON, disabled storage, SSR, …). Palette
// should never crash because the user's localStorage is dirty.
function safeReadLS(key, fallback) {
  if (typeof window === 'undefined' || !window.localStorage) return fallback;
  try {
    const raw = window.localStorage.getItem(key);
    if (!raw) return fallback;
    const parsed = JSON.parse(raw);
    return parsed == null ? fallback : parsed;
  } catch {
    return fallback;
  }
}

// Each cached entry has shape:
//   { type, label, hint, icon, kw, payload, _labelLc, _hayLc }
//
//   type      'action' | 'subject' | 'summary' | 'instructor' | 'question'
//   payload   data needed by the dispatcher (action key, subject id,
//             Q ref, instructor object, …) — keeps the cached entry
//             pure data so it can outlive any component instance.
//   _labelLc  label.toLowerCase() — used by fuzzyFilter so we don't
//             re-lowercase 1700 strings per keystroke
//   _hayLc    (label + ' ' + kw).toLowerCase() — same idea
function buildStaticItems() {
  if (_staticItemsCache) return _staticItemsCache;
  const items = [];

  const push = (it) => {
    const labelLc = (it.label || '').toLowerCase();
    items.push({
      ...it,
      _labelLc: labelLc,
      _hayLc: labelLc + ' ' + (it.kw || '').toLowerCase(),
    });
  };

  // Quick actions — payload is the action key the dispatcher knows.
  const actions = [
    { key: 'home',              label: 'หน้าแรก',                 hint: 'Home',                            icon: '🏠',  kw: 'home หน้าแรก main' },
    { key: 'dashboard',         label: 'Dashboard / สถิติ',        hint: 'Dashboard',                       icon: '📊',  kw: 'dashboard stats สถิติ analytics' },
    { key: 'schedule',          label: 'ตารางสอบ',                 hint: 'Schedule',                        icon: '📅',  kw: 'schedule exam ตาราง สอบ' },
    { key: 'videos',            label: 'คลิปย้อนหลัง',              hint: 'Videos',                          icon: '🎬',  kw: 'video clip คลิป ย้อนหลัง summary' },
    { key: 'reading-checklist', label: 'Reading Checklist',        hint: 'Checklist',                       icon: '📖',  kw: 'reading checklist อ่าน หัวข้อ' },
    { key: 'bookmarks',         label: 'Bookmarks',                hint: 'Saved questions',                 icon: '⭐',  kw: 'bookmark saved star ⭐ ข้อ' },
    { key: 'pinboard',          label: 'Pinboard',                 hint: 'รายการ pin',                       icon: '📌',  kw: 'pinboard pin หมุด รวบรวม board collect saved' },
    { key: 'question-manager',  label: 'Question Manager',         hint: 'Custom Q',                        icon: '✏️',  kw: 'manage edit custom question จัดการ' },
    { key: 'sr-session',        label: 'Spaced Repetition',        hint: 'SR review',                       icon: '🧠',  kw: 'sr spaced repetition review flashcard ทบทวน' },
    { key: 'scores',            label: 'คะแนนล่าสุด',                hint: 'Scores',                          icon: '🏆',  kw: 'score คะแนน history ประวัติ' },
    { key: 'about',             label: 'About',                    hint: 'เกี่ยวกับ',                         icon: 'ℹ️',  kw: 'about info เกี่ยวกับ' },
    { key: 'feedback',          label: 'แจ้งปัญหา / Feedback',       hint: 'Feedback',                        icon: '🐛',  kw: 'feedback bug แจ้ง ปัญหา ติชม' },
    { key: 'ig-cards',          label: 'IG Card Studio',           hint: 'Generate posts for @vetmock.cu',  icon: '📷',  kw: 'ig instagram card studio post daily admin export' },
    { key: 'faculty',           label: 'อาจารย์ผู้สอนทั้งหมด',         hint: 'Faculty index',                   icon: '👨‍🏫', kw: 'faculty instructor อาจารย์ ผู้สอน lecturer professor' },
    { key: 'account-settings',  label: 'Account Settings',         hint: 'จัดการ account',                   icon: '⚙️',  kw: 'account settings password email logout delete รหัสผ่าน อีเมล ลบ' },
    { key: 'voice-settings',    label: 'Voice Settings',           hint: 'ปรับเสียงพูดข้อสอบ',                icon: '🎚',  kw: 'voice tts settings pause speed เสียง อ่าน เสียงพูด พูด ความเร็ว pace tempo iapp kaitom' },
    { key: 'pdf-annotate',      label: 'PDF + annotate',           hint: 'อัปโหลด lecture PDF แล้วเขียนทับ',  icon: '📑',  kw: 'pdf annotate annotation lecture slide สไลด์ เขียนทับ' },
    { key: 'image-occlusion',   label: 'Image Occlusion',          hint: 'ทำ flashcard จากรูป',              icon: '🖼',  kw: 'image occlusion mask anatomy รูปภาพ ปกปิด anki' },
    { key: 'pomodoro',          label: 'Pomodoro · 🐤',            hint: 'จับเวลา focus 25 นาที + ลูกไก่ฟัก', icon: '🍅',  kw: 'pomodoro focus timer 25 minute chick ลูกไก่ ฟัก จับเวลา โฟกัส' },
    { key: 'phase-wrapped',     label: 'Phase Wrapped',            hint: 'สรุปการเรียน',                     icon: '📊',  kw: 'wrapped phase summary สรุป recap spotify year-in-review เทอม สอบจบ' },
  ];
  for (const a of actions) push({ type: 'action', payload: a.key, label: a.label, hint: a.hint, icon: a.icon, kw: a.kw });

  // Subjects
  for (const s of SUBJECTS) {
    if (s.id === 'all') continue;
    push({
      type: 'subject',
      payload: s.id,
      label: s.name,
      hint: s.name_en || s.code || '',
      icon: s.icon || '📚',
      kw: `${s.id} ${s.name} ${s.name_en || ''} ${s.code || ''}`,
    });
  }

  // Video summaries
  for (const s of Object.values(VIDEO_SUMMARIES || {})) {
    if (!s?.title) continue;
    push({
      type: 'summary',
      payload: null,
      label: s.title,
      hint: `📝 สรุปคลิป, ${(s.subject || '').toUpperCase()}`,
      icon: '📝',
      kw: `${s.title} ${s.subject || ''} ${s.instructor || ''} summary สรุป คลิป`,
    });
  }

  // Instructors
  for (const ins of (ALL_INSTRUCTORS || [])) {
    push({
      type: 'instructor',
      payload: ins,
      label: `Aj. ${ins.nameEn}`,
      hint: `👨‍🏫 ${ins.nameTh || ''}, ${(ins.subjects || []).join('/').toUpperCase()}`,
      icon: '👨‍🏫',
      kw: `${ins.nameEn} ${ins.nameTh || ''} ${ins.position || ''} ${(ins.areas || []).join(' ')} instructor faculty อาจารย์`,
    });
  }

  // Question stems
  const seenQText = new Set();
  for (const q of (QB || [])) {
    if (!q?.q || typeof q.q !== 'string') continue;
    const stem = q.q.slice(0, 100);
    const dedupeKey = q.subject + ':' + stem.slice(0, 50);
    if (seenQText.has(dedupeKey)) continue;
    seenQText.add(dedupeKey);
    push({
      type: 'question',
      payload: { subject: q.subject, id: q.id },
      label: stem.length < q.q.length ? stem + '…' : stem,
      hint: `${q.subject?.toUpperCase() || 'Q'}, Q${q.id}${q.tags?.length ? ' · ' + q.tags.slice(0, 2).join(', ') : ''}`,
      icon: '❓',
      kw: stem + ' ' + (q.tags || []).join(' '),
    });
  }

  // User-authored flashcards (Highlight → Flashcard). Reads localStorage
  // via the dedicated module so a corrupted blob or quota-exceeded
  // state can't bring the palette down. front+back together become
  // the searchable haystack so even back-of-card terms hit.
  let flashcards = [];
  try {
    flashcards = loadUserFlashcards() || [];
  } catch {
    flashcards = [];
  }
  for (const card of flashcards) {
    if (!card || typeof card.front !== 'string' || !card.front.trim()) continue;
    const back = (card.back || '').toString();
    push({
      type: 'flashcard',
      payload: card,
      label: trunc(card.front),
      hint: 'Flashcard',
      icon: '⚡',
      kw: (card.front + ' ' + back).toLowerCase(),
    });
  }

  // Per-Q notes — stored as { [qIdOrCompoundKey]: noteText } under
  // 'vmx-notes'. We surface each non-empty note as its own row so the
  // user can fuzzy-search their own annotations and jump back to the
  // Q. Key shape is opaque to us; we pass it through as the payload.
  const notesMap = safeReadLS(NOTES_LS_KEY, null);
  if (notesMap && typeof notesMap === 'object' && !Array.isArray(notesMap)) {
    for (const [key, raw] of Object.entries(notesMap)) {
      const text = typeof raw === 'string' ? raw : (raw && typeof raw === 'object' ? (raw.text || raw.note || '') : '');
      const trimmed = (text || '').toString().trim();
      if (!trimmed) continue;
      push({
        type: 'q-note',
        payload: key,
        label: trunc(trimmed),
        hint: 'โน้ต Q ' + key,
        icon: '📝',
        kw: trimmed.toLowerCase(),
      });
    }
  }

  _staticItemsCache = items;
  return items;
}

// Dispatch table — translates a cached item back into an action.
// Keeps the item array pure data so we don't have to rebuild closures.
function runItem(item, handlers) {
  const { goView, setSubject, setPracticeMode, openInstructor, openVoiceSettings } = handlers;
  switch (item.type) {
    case 'action': {
      if (item.payload === 'bookmarks') { setPracticeMode?.('bookmarks'); goView?.('config'); return; }
      // voice-settings opens an overlay instead of navigating — keeps
      // the user on the current Q if they triggered from ExamView.
      if (item.payload === 'voice-settings') { openVoiceSettings?.(); return; }
      goView?.(item.payload);
      return;
    }
    case 'subject':    setSubject?.(item.payload); goView?.('topic-select'); return;
    case 'summary':    goView?.('videos'); return;
    case 'instructor': openInstructor?.(item.payload); return;
    case 'question':   setSubject?.(item.payload.subject); setPracticeMode?.('all'); goView?.('config'); return;
    // User flashcard → jump into SR review. v1 doesn't scroll to the
    // specific card; the user can rip through the deck from the top.
    case 'flashcard':  goView?.('sr-session'); return;
    // Per-Q note → open Bookmarks practice so the user can fuzzy-find
    // their noted Q in a quick-review set. Cheapest navigation that
    // gets them into a context where the note matters.
    case 'q-note':     setPracticeMode?.('bookmarks'); goView?.('config'); return;
    default: return;
  }
}

// Lightweight fuzzy match against pre-lowered haystacks. The empty
// query returns the top MAX_RESULTS items in original (action-first)
// order so the open-state list isn't 1700 <button>s long.
function fuzzyFilter(items, query) {
  const q = query.trim().toLowerCase();
  if (!q) return items.slice(0, MAX_RESULTS);
  const tokens = q.split(/\s+/).filter(Boolean);

  const scored = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    let score = 0;
    let allMatch = true;
    for (const t of tokens) {
      const pos = item._hayLc.indexOf(t);
      if (pos < 0) { allMatch = false; break; }
      const labelPos = item._labelLc.indexOf(t);
      score += labelPos >= 0 ? (100 - labelPos) : (50 - Math.min(50, pos));
      if (item._labelLc.startsWith(t)) score += 200;
    }
    if (allMatch) scored.push({ item, score });
  }
  scored.sort((a, b) => b.score - a.score);
  // Cap render — anything past MAX_RESULTS won't fit on screen anyway
  // and the user refines the query if they need more specific hits.
  const out = new Array(Math.min(scored.length, MAX_RESULTS));
  for (let i = 0; i < out.length; i++) out[i] = scored[i].item;
  return out;
}

export default function CommandPalette({ open, onClose, ...handlers }) {
  const [query, setQuery] = useState('');
  // Debounced version drives the filter — keeps the heavy work off
  // the input keystroke. 60ms is below the human-perceivable threshold
  // for input echo but long enough to coalesce a burst of fast typing
  // into one filter pass.
  const [debouncedQuery, setDebouncedQuery] = useState('');
  const [activeIdx, setActiveIdx] = useState(0);
  const inputRef = useRef(null);
  const listRef = useRef(null);

  // Static index lives at module scope — first call builds it (lazy),
  // subsequent opens reuse it. Handlers attach via runItem() at fire
  // time, so re-renders that produce new handler identities don't
  // invalidate the index.
  const items = useMemo(() => buildStaticItems(), []);
  // Pre-stringify handlers into a stable ref — runItem reads from it.
  const handlersRef = useRef(handlers);
  handlersRef.current = handlers;

  // Debounce the query → filter pipeline
  useEffect(() => {
    if (query === debouncedQuery) return;
    const t = setTimeout(() => setDebouncedQuery(query), 60);
    return () => clearTimeout(t);
  }, [query, debouncedQuery]);

  const filtered = useMemo(() => fuzzyFilter(items, debouncedQuery), [items, debouncedQuery]);

  // Index totals — informational chip shown when the query is empty
  // so the user knows what's actually searchable. Cheap reduce over
  // the static index; memoized so it doesn't run per keystroke.
  const indexTotals = useMemo(() => {
    let questions = 0, flashcards = 0, notes = 0;
    for (const it of items) {
      if (it.type === 'question') questions++;
      else if (it.type === 'flashcard') flashcards++;
      else if (it.type === 'q-note') notes++;
    }
    return { questions, flashcards, notes };
  }, [items]);

  // Reset on open / close
  useEffect(() => {
    if (open) {
      setQuery('');
      setDebouncedQuery('');
      setActiveIdx(0);
      // Defer focus until modal is in DOM
      const t = setTimeout(() => inputRef.current?.focus(), 0);
      return () => clearTimeout(t);
    }
  }, [open]);

  // Reset active index when filter changes
  useEffect(() => { setActiveIdx(0); }, [debouncedQuery]);

  // Keep active item in view when navigating with arrows
  useEffect(() => {
    if (!listRef.current) return;
    const el = listRef.current.children[activeIdx];
    if (el && typeof el.scrollIntoView === 'function') {
      el.scrollIntoView({ block: 'nearest' });
    }
  }, [activeIdx]);

  if (!open) return null;

  const handleKey = (e) => {
    if (e.key === 'Escape') { e.preventDefault(); onClose(); }
    else if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActiveIdx((i) => Math.min(filtered.length - 1, i + 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActiveIdx((i) => Math.max(0, i - 1));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const item = filtered[activeIdx];
      if (item) { runItem(item, handlersRef.current); onClose(); }
    }
  };

  return (
    <div
      className="vmx-modal-overlay"
      onClick={onClose}
      style={{ alignItems: 'flex-start', paddingTop: 'min(15vh, 100px)' }}
    >
      <div
        className="vmx-modal"
        onClick={(e) => e.stopPropagation()}
        style={{ maxWidth: 600, padding: 0, overflow: 'hidden' }}
        role="dialog"
        aria-label="Command palette"
      >
        {/* Search input */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          padding: '16px 20px',
          borderBottom: '1px solid var(--clr-border)',
        }}>
          <span style={{ fontSize: 18, color: 'var(--clr-ink-soft)' }}>🔍</span>
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={handleKey}
            placeholder="ค้นหาทุกอย่าง — subject, summary, เมนู…"
            style={{
              all: 'unset',
              flex: 1,
              fontSize: 16,
              color: 'var(--clr-ink)',
              fontFamily: 'inherit',
              minWidth: 0,
            }}
            autoComplete="off"
            spellCheck="false"
          />
          <span style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 11,
            color: 'var(--clr-ink-soft)',
            padding: '2px 6px',
            border: '1px solid var(--clr-border)',
            borderRadius: 4,
          }}>esc</span>
        </div>

        {/* Index totals — helps the user understand what's searchable
            without typing anything. Hidden once they start filtering
            so it doesn't compete with the result count in the footer. */}
        {!query.trim() && (
          <div style={{
            padding: '8px 20px',
            display: 'flex',
            gap: 8,
            flexWrap: 'wrap',
            borderBottom: '1px solid var(--clr-border)',
            background: 'var(--clr-bg)',
          }}>
            <span style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 10,
              color: 'var(--clr-ink-soft)',
              padding: '2px 8px',
              border: '1px solid var(--clr-border)',
              borderRadius: 10,
            }}>{indexTotals.questions} ข้อ</span>
            <span style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 10,
              color: 'var(--clr-ink-soft)',
              padding: '2px 8px',
              border: '1px solid var(--clr-border)',
              borderRadius: 10,
            }}>{indexTotals.flashcards} flashcards</span>
            <span style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 10,
              color: 'var(--clr-ink-soft)',
              padding: '2px 8px',
              border: '1px solid var(--clr-border)',
              borderRadius: 10,
            }}>{indexTotals.notes} notes</span>
          </div>
        )}

        {/* Results list */}
        <div
          ref={listRef}
          style={{
            maxHeight: '50vh',
            overflowY: 'auto',
            padding: 4,
          }}
        >
          {filtered.length === 0 && (
            <div style={{
              padding: '32px 20px',
              textAlign: 'center',
              color: 'var(--clr-ink-soft)',
              fontSize: 14,
            }}>
              ไม่พบที่ตรงกับ "{query}"
            </div>
          )}
          {filtered.map((item, i) => {
            const active = i === activeIdx;
            // Section header — only when no query (so fuzzy ranking
            // doesn't shuffle the type order). Renders before the first
            // item of each type group.
            const SECTION_LABELS = {
              action: '⚡ Quick Actions',
              subject: '📚 Subjects',
              summary: '📝 Video Summaries',
              instructor: '👨‍🏫 Faculty',
              flashcard: '⚡ Flashcards',
              'q-note': '📝 โน้ต Q',
            };
            const showHeader = !query.trim() && (i === 0 || filtered[i - 1].type !== item.type);
            return (
              <div key={`wrap-${item.type}-${item.label}-${i}`}>
                {showHeader && SECTION_LABELS[item.type] && (
                  <div style={{
                    padding: '10px 16px 4px',
                    fontSize: 10,
                    fontFamily: 'JetBrains Mono, monospace',
                    color: 'var(--clr-ink-soft)',
                    textTransform: 'uppercase',
                    letterSpacing: '0.1em',
                    fontWeight: 600,
                  }}>
                    {SECTION_LABELS[item.type]}
                  </div>
                )}
              <button
                key={`${item.type}-${item.label}-${i}`}
                onClick={() => { runItem(item, handlersRef.current); onClose(); }}
                onMouseEnter={() => setActiveIdx(i)}
                style={{
                  all: 'unset',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 12,
                  width: '100%',
                  boxSizing: 'border-box',
                  padding: '10px 16px',
                  borderRadius: 8,
                  background: active ? 'var(--clr-surface-2)' : 'transparent',
                  transition: 'background 0.05s',
                }}
              >
                <span style={{ fontSize: 20, flex: '0 0 auto' }}>{item.icon}</span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{
                    fontSize: 14,
                    fontWeight: 500,
                    color: 'var(--clr-ink)',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}>
                    {item.label}
                  </div>
                  {item.hint && (
                    <div style={{
                      fontSize: 11,
                      color: 'var(--clr-ink-soft)',
                      fontFamily: 'JetBrains Mono, monospace',
                      marginTop: 2,
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                      whiteSpace: 'nowrap',
                    }}>
                      {item.hint}
                    </div>
                  )}
                </div>
                {active && (
                  <span style={{
                    fontFamily: 'JetBrains Mono, monospace',
                    fontSize: 11,
                    color: 'var(--clr-ink-soft)',
                    flex: '0 0 auto',
                  }}>↵</span>
                )}
              </button>
              </div>
            );
          })}
        </div>

        {/* Footer hint */}
        <div style={{
          padding: '10px 16px',
          borderTop: '1px solid var(--clr-border)',
          background: 'var(--clr-bg)',
          fontFamily: 'JetBrains Mono, monospace',
          fontSize: 10,
          color: 'var(--clr-ink-soft)',
          display: 'flex',
          gap: 16,
          flexWrap: 'wrap',
        }}>
          <span>↑↓ เลื่อน</span>
          <span>↵ เลือก</span>
          <span>esc ปิด</span>
          <span style={{ marginLeft: 'auto' }}>{filtered.length} ผลลัพธ์</span>
        </div>
      </div>
    </div>
  );
}
