// ============================================================
// CommandPalette — the AI Search surface (⌘K / Ctrl+K / 🔍)
// ============================================================
// One box → everything the app knows, grouped and streamed:
//   • Quick actions, subjects, exams, videos, faculty, questions,
//     VetWiki, flashcards, per-Q notes  (bundled index, instant)
//   • the 1,496-doc library shelf + the drug database  (async sources,
//     stream in while the palette is open)
//   • intent cards: "ketamine 12 kg แมว" answers with the computed dose,
//     a course number answers with the course — data, never generated
//
// Lightweight, no external lib. Thai-friendly fuzzy match
// (substring + per-token + tolerance for word order).
//
// Wired in App.jsx via global keydown listener — only opens when
// the user is NOT typing in an input/textarea/contenteditable.
// ============================================================

import { useState, useEffect, useMemo, useRef } from 'react';
import { SUBJECTS, yearForSubject } from '../data/curriculum.js';
import { getUpcomingExams, fmtThaiDate } from '../data/schedule.js';
// CommandPalette only needs {title, subject, instructor} for search —
// importing the full VIDEO_SUMMARIES dragged ~360 KB of markdown body
// text into the palette's lazy chunk. Switched to a lightweight meta
// index (auto-regenerated by scripts/regen-video-meta.mjs) so opening
// ⌘K stays snappy even on slow connections.
import { VIDEO_META as VIDEO_SUMMARIES } from '../data/video-summaries-meta.js';
import { ALL_INSTRUCTORS } from '../data/instructors.js';
// QB is already in the main bundle (App.jsx + HomeView import it eagerly),
// so adding it here doesn't grow the palette lazy chunk — it's deduped.
// Only the first 80 chars of q.q are added to the keyword string to keep
// fuzzy-filter cost bounded (~1999 Qs × short stem = manageable).
import { QB } from '../data/questions.js';
import { isQuestionDeliverable } from '../data/question-delivery.generated.js';
// User-authored flashcards (Highlight → Flashcard feature). Same
// module that owns the localStorage key, so we don't re-parse here.
import { loadUserFlashcards } from '../lib/user-flashcards.js';
// Feature registry — single source of truth shared with HomeView. The
// palette's "Quick Actions" are derived from it so a feature added once
// shows up in BOTH the home grid and search (no more hand-synced drift,
// which had left 7 navigable features unsearchable).
import { FEATURES, visibleFeatures, FEATURE_FLAGS } from '../lib/feature-registry.js';
import { listTopics } from '../lib/vetwiki/registry.js';
import { useModalFocus } from '../hooks/useModalFocus.js';
import ErrorBoundary from './ErrorBoundary.jsx';
// Async sources (library shelf, drug DB) + deterministic intent cards —
// the pieces that turn the palette into the app's AI search surface.
import { OMNI_SOURCES } from '../lib/omni-sources.js';
import { detectIntents } from '../lib/omni-intents.js';
import { docOpenMode, readerPayload, recordRecentDoc, resolveDocUrl } from '../lib/library.js';

// localStorage keys for user-authored content surfaced in the palette.
// Keeping the literals here mirrors the convention used by NotesView
// (the writer) — a single rename would touch both files, which is
// acceptable for two strings.
const NOTES_LS_KEY = 'vmx-notes';

// Cap on how many results we render at once. The full index has
// ~1700 items (mostly question stems). Rendering all of them as
// <button>s on every keystroke turned the palette into a noticeable
// freeze on slower phones. 80 fills the visible list comfortably and
// the user almost never scrolls past the top of the result set
// anyway — they refine the query instead.
const MAX_RESULTS = 80;

// ── Module-level cache for the static parts of the index ─────────
// The actual run() handlers depend on App.jsx's setState refs (fresh
// identity on every render of App), but the rest — label, hint, icon,
// keyword bag, pre-lowered haystack — is fully deterministic from
// imported data modules. Build that part ONCE per session and stash
// it. Opening the palette re-uses the same array; we only re-attach
// the run() closures per open.
let _staticItemsCache = null;

/**
 * Bust the module-level static index. Call this whenever
 * user-authored content (flashcards, per-Q notes, bookmarks) changes
 * outside the palette — the next open() rebuilds the index lazily.
 * Cheap and idempotent.
 */
export function invalidateCommandPaletteCache() {
  _staticItemsCache = null;
}

// Global hook: any code path can fire this event without importing
// us. user-flashcards.js dispatches it after save/delete; NotesView
// (or any future writer) can opt-in by dispatching the same event.
if (typeof window !== 'undefined') {
  window.addEventListener('vmx-palette-invalidate', () => {
    _staticItemsCache = null;
  });
}

// Truncate a label for the result row. The result button is a single
// line with ellipsis CSS, but we still cap at the source so the
// pre-lowered haystack stays small and tooltips don't blow up either.
const MAX_LABEL_LEN = 60;
function trunc(s) {
  const str = (s || '').toString().replace(/\s+/g, ' ').trim();
  return str.length > MAX_LABEL_LEN ? str.slice(0, MAX_LABEL_LEN - 1) + '…' : str;
}

// Safely read & JSON-parse a localStorage key. Returns fallback on
// any failure (corrupted JSON, disabled storage, SSR, …). Palette
// should never crash because the user's localStorage is dirty.
function safeReadLS(key, fallback) {
  if (typeof window === 'undefined' || !window.localStorage) return fallback;
  try {
    const raw = window.localStorage.getItem(key);
    if (!raw) return fallback;
    const parsed = JSON.parse(raw);
    return parsed == null ? fallback : parsed;
  } catch {
    return fallback;
  }
}

// Each cached entry has shape:
//   { type, label, hint, icon, kw, payload, _labelLc, _hayLc }
//
//   type      'action' | 'subject' | 'summary' | 'instructor' | 'question'
//   payload   data needed by the dispatcher (action key, subject id,
//             Q ref, instructor object, …) — keeps the cached entry
//             pure data so it can outlive any component instance.
//   _labelLc  label.toLowerCase() — used by fuzzyFilter so we don't
//             re-lowercase 1700 strings per keystroke
//   _hayLc    (label + ' ' + kw).toLowerCase() — same idea
function buildStaticItems() {
  // The cache is keyed on the bank size: QB is lazy-loaded and mutated in
  // place, so a cache built before the load (or before a year switch pulls a
  // different bank) held stale question rows for the rest of the session —
  // search results and their counts disagreed with the app.
  if (_staticItemsCache && _staticItemsCache.qbLen === QB.length) return _staticItemsCache.items;
  const items = [];

  const push = (it) => {
    const labelLc = (it.label || '').toLowerCase();
    items.push({
      ...it,
      _labelLc: labelLc,
      _hayLc: labelLc + ' ' + (it.kw || '').toLowerCase(),
    });
  };

  // Quick actions — DERIVED from the feature registry (single source of
  // truth shared with HomeView), plus two nav-only entries that aren't
  // standalone "features": home (navigation) and bookmarks (a practice
  // mode, not a screen). payload carries the invoke descriptor that
  // runItem() interprets. Deriving here means adding a feature to the
  // registry makes it searchable automatically — closing the old gap
  // where race/groups/lab/leaderboard/contribute/review-queue/mini-game
  // were navigable from somewhere but never showed up in ⌘K.
  push({ type: 'action', payload: { kind: 'view', view: 'home' }, label: 'หน้าแรก', hint: 'Home', icon: '🏠', kw: 'home หน้าแรก main' });
  push({ type: 'action', payload: { kind: 'bookmarks' }, label: 'Bookmarks', hint: 'ข้อที่บันทึกไว้', icon: '⭐', kw: 'bookmark saved star ดาว ข้อบันทึก' });
  for (const f of FEATURES) {
    push({ type: 'action', payload: f.invoke, label: f.label, hint: f.hint, icon: f.icon, kw: f.kw, category: f.category, featureId: f.id });
  }

  // VetWiki articles — governed knowledge is searchable from anywhere.
  // Keywords include the summary so Thai queries reach English-titled topics.
  if (FEATURE_FLAGS.VETWIKI_ENABLED !== false) {
    for (const t of listTopics()) {
      push({
        type: 'wiki',
        payload: { subject: t.subject, topic: t.topic },
        label: t.title,
        hint: 'VetWiki, บอกที่มาได้ทุกส่วน',
        icon: '🧬',
        kw: `vetwiki wiki ${t.title} ${t.summary || ''} ${t.subject} ${t.topic}`,
      });
    }
  }

  // Subjects
  for (const s of SUBJECTS) {
    if (s.id === 'all') continue;
    push({
      type: 'subject',
      payload: s.id,
      year: yearForSubject(s.id),
      label: s.name,
      hint: s.name_en || s.code || '',
      icon: s.icon || '📚',
      kw: `${s.id} ${s.name} ${s.name_en || ''} ${s.code || ''}`,
    });
  }

  // Upcoming exams — so "สอบ zoonoses", a course code, or "กลางภาค" lands on
  // the real date/time/room instead of the student asking in the group chat.
  for (const yr of [1, 2, 3, 4, 5]) {
    for (const e of getUpcomingExams(`y${yr}`)) {
      if (e.daysLeft < 0) continue; // past exams are noise in a search box
      push({
        type: 'exam',
        payload: 'schedule',
        year: yr,
        label: `สอบ ${e.title}`,
        hint: `${fmtThaiDate(e.date)}, ${e.time}, ${e.location}`,
        icon: e.icon || '📅',
        kw: `exam สอบ ${e.term === 'midterm' ? 'กลางภาค midterm' : 'ปลายภาค final'} ${e.code} ${e.title} ${e.subject} ${e.location}`,
      });
    }
  }

  // Video summaries
  for (const s of Object.values(VIDEO_SUMMARIES || {})) {
    if (!s?.title) continue;
    push({
      type: 'summary',
      payload: null,
      label: s.title,
      hint: `สรุปคลิป, ${(s.subject || '').toUpperCase()}`,
      icon: '📝',
      kw: `${s.title} ${s.subject || ''} ${s.instructor || ''} summary สรุป คลิป`,
    });
  }

  // Instructors
  for (const ins of (ALL_INSTRUCTORS || [])) {
    push({
      type: 'instructor',
      payload: ins,
      label: `อ. ${ins.nameTh || ins.nameEn}`,
      hint: `👨‍🏫 ${ins.nameEn}, ${(ins.subjects || []).join('/').toUpperCase()}`,
      icon: '👨‍🏫',
      kw: `${ins.nameEn} ${ins.nameTh || ''} ${(ins.aliases || []).join(' ')} ${ins.position || ''} ${(ins.areas || []).join(' ')} instructor faculty อาจารย์`,
    });
  }

  // Question stems
  const seenQText = new Set();
  for (const q of (QB || [])) {
    if (!isQuestionDeliverable(q)) continue;
    if (!q?.q || typeof q.q !== 'string') continue;
    const stem = q.q.slice(0, 100);
    const dedupeKey = q.subject + ':' + stem.slice(0, 50);
    if (seenQText.has(dedupeKey)) continue;
    seenQText.add(dedupeKey);
    push({
      type: 'question',
      payload: { subject: q.subject, id: q.id },
      label: stem.length < q.q.length ? stem + '…' : stem,
      hint: `${q.subject?.toUpperCase() || 'Q'}, Q${q.id}${q.tags?.length ? ', ' + q.tags.slice(0, 2).join(', ') : ''}`,
      icon: '❓',
      kw: stem + ' ' + (q.tags || []).join(' '),
    });
  }

  // User-authored flashcards (Highlight → Flashcard). Reads localStorage
  // via the dedicated module so a corrupted blob or quota-exceeded
  // state can't bring the palette down. front+back together become
  // the searchable haystack so even back-of-card terms hit.
  let flashcards = [];
  try {
    flashcards = loadUserFlashcards() || [];
  } catch {
    flashcards = [];
  }
  for (const card of flashcards) {
    if (!card || typeof card.front !== 'string' || !card.front.trim()) continue;
    const back = (card.back || '').toString();
    push({
      type: 'flashcard',
      payload: card,
      label: trunc(card.front),
      hint: 'Flashcard',
      icon: '⚡',
      kw: (card.front + ' ' + back).toLowerCase(),
    });
  }

  // Per-Q notes — stored as { [qIdOrCompoundKey]: noteText } under
  // 'vmx-notes'. We surface each non-empty note as its own row so the
  // user can fuzzy-search their own annotations and jump back to the
  // Q. Key shape is opaque to us; we pass it through as the payload.
  const notesMap = safeReadLS(NOTES_LS_KEY, null);
  if (notesMap && typeof notesMap === 'object' && !Array.isArray(notesMap)) {
    for (const [key, raw] of Object.entries(notesMap)) {
      const text = typeof raw === 'string' ? raw : (raw && typeof raw === 'object' ? (raw.text || raw.note || '') : '');
      const trimmed = (text || '').toString().trim();
      if (!trimmed) continue;
      push({
        type: 'q-note',
        payload: key,
        label: trunc(trimmed),
        hint: 'โน้ต Q ' + key,
        icon: '📝',
        kw: trimmed.toLowerCase(),
      });
    }
  }

  _staticItemsCache = { qbLen: QB.length, items };
  return items;
}

// Dispatch table — translates a cached item back into an action.
// Keeps the item array pure data so we don't have to rebuild closures.
function runItem(item, handlers) {
  const { goView, setSubject, setPracticeMode, openInstructor, openVoiceSettings, onPractice, onPanic, onSketch, onOpenWiki } = handlers;
  switch (item.type) {
    case 'wiki': onOpenWiki?.(item.payload.subject, item.payload.topic); return;
    case 'exam': goView?.(item.payload); return; // payload = 'schedule'
    case 'action': {
      // payload is now an invoke descriptor (from the registry) or one of
      // the two nav-only specials (home view / bookmarks practice mode).
      const inv = item.payload;
      if (!inv || typeof inv !== 'object') return;
      switch (inv.kind) {
        case 'view':      goView?.(inv.view); return;
        case 'practice':  onPractice?.(inv); return;
        case 'panic':     onPanic?.(inv.timeKey || '30'); return;
        case 'event':     try { window.dispatchEvent(new Event(inv.event)); } catch { /* no-op */ } return;
        case 'sketch':    onSketch?.(); return;
        case 'external':  if (inv.url) window.location.assign(inv.url); return;
        // voice-settings opens an overlay instead of navigating — keeps
        // the user on the current Q if they triggered from ExamView.
        case 'voice':     openVoiceSettings?.(); return;
        case 'bookmarks': setPracticeMode?.('bookmarks'); goView?.('config'); return;
        default: return;
      }
    }
    case 'subject':    setSubject?.(item.payload); goView?.('topic-select'); return;
    case 'summary':    goView?.('videos'); return;
    case 'instructor': openInstructor?.(item.payload); return;
    case 'question':   setSubject?.(item.payload.subject); setPracticeMode?.('all'); goView?.('config'); return;
    // User flashcard → jump into SR review. v1 doesn't scroll to the
    // specific card; the user can rip through the deck from the top.
    case 'flashcard':  goView?.('sr-session'); return;
    // Per-Q note → open Bookmarks practice so the user can fuzzy-find
    // their noted Q in a quick-review set. Cheapest navigation that
    // gets them into a context where the note matters.
    case 'q-note':     setPracticeMode?.('bookmarks'); goView?.('config'); return;
    default: return;
  }
}

// Ranked (item, score) pairs — the grouped renderer needs scores to order
// GROUPS by their best hit while keeping items ranked inside each group.
function rankItems(items, query) {
  const q = query.trim().toLowerCase();
  const tokens = q.split(/\s+/).filter(Boolean);
  const scored = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    let score = 0;
    let allMatch = true;
    for (const t of tokens) {
      const pos = item._hayLc.indexOf(t);
      if (pos < 0) { allMatch = false; break; }
      const labelPos = item._labelLc.indexOf(t);
      score += labelPos >= 0 ? (100 - labelPos) : (50 - Math.min(50, pos));
      if (item._labelLc.startsWith(t)) score += 200;
    }
    if (allMatch) scored.push({ item, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, MAX_RESULTS);
}

// ── Presentation helpers ─────────────────────────────────────────────────

const GROUP_META = {
  recent:       { label: 'ล่าสุด',          icon: '🕘' },
  action:       { label: 'Quick Actions',   icon: '⚡' },
  subject:      { label: 'วิชา',            icon: '📚' },
  exam:         { label: 'ตารางสอบ',        icon: '📅' },
  wiki:         { label: 'VetWiki',         icon: '🧬' },
  'library-doc':{ label: 'คลังเอกสาร',      icon: '📄' },
  drug:         { label: 'ขนาดยา',          icon: '💊' },
  summary:      { label: 'สรุปคลิป',        icon: '📝' },
  instructor:   { label: 'อาจารย์',         icon: '👨‍🏫' },
  question:     { label: 'ข้อสอบ',          icon: '❓' },
  flashcard:    { label: 'Flashcards',      icon: '⚡' },
  'q-note':     { label: 'โน้ตของฉัน',      icon: '📝' },
};
const GROUP_ORDER = Object.keys(GROUP_META);

// Per-group render cap. "แสดงเพิ่ม" lifts it for that group only — a query
// like "anatomy" legitimately has dozens of library hits.
const GROUP_CAP = 6;
const GROUP_CAP_EXPANDED = 30;

// "Why only Ctrl+Enter?" — Palm, 2026-08-29. A question-shaped query puts
// the ask row INTO the keyboard flow as the first item, so plain Enter
// asks; on touch it is a big tap target; and when the list comes up empty
// on a settled question, the ask fires by itself — zero keys.
const QUESTION_RE = /([?？]\s*$)|(ไหม|มั้ย|อะไร|ทำไม|ยังไง|อย่างไร|เท่าไหร่|เท่าไร|กี่|คือ|ต่างจาก|ต่างกัน|หรือไม่|บ้าง|ที่ไหน|เมื่อไหร่|แค่ไหน|ได้ไหม|ควร)/;
const ACTION_RE = /(ฝึก|จัด|เปิด|เริ่ม|ติว|ทำข้อสอบ|ขอข้อสอบ|ขอโจทย์|อยากทำ|อยากฝึก|อยากอ่าน|พาไป|ตั้งเวลา|จับเวลา|ให้หน่อย)/;
const looksLikeAction = (q) => q.length >= 6 && ACTION_RE.test(q);
const looksLikeQuestion = (q) => q.length >= 8 && (QUESTION_RE.test(q) || /^(why|what|how|when|which|is|are|can|does|do|explain)\b/i.test(q));

const RECENTS_KEY = 'vmx-omni-recents';
const MAX_RECENTS = 8;

function readRecents() {
  return safeReadLS(RECENTS_KEY, []).filter((r) => r && r.type && r.label);
}
function pushRecent(item) {
  try {
    const slim = { type: item.type, label: item.label, hint: item.hint, icon: item.icon, payload: item.payload };
    if (JSON.stringify(slim).length > 4000) return; // an instructor bio etc. — not worth persisting
    const next = [slim, ...readRecents().filter((r) => !(r.type === slim.type && r.label === slim.label))]
      .slice(0, MAX_RECENTS);
    localStorage.setItem(RECENTS_KEY, JSON.stringify(next));
  } catch { /* storage full or disabled — recents are a nicety */ }
}

// First-token match highlight. One <mark> is enough to show WHY a row
// matched; painting every token turns labels into confetti.
function HighlightedLabel({ label, query }) {
  const q = (query || '').trim().toLowerCase();
  const first = q.split(/\s+/)[0] || '';
  const pos = first ? (label || '').toLowerCase().indexOf(first) : -1;
  if (pos < 0) return label;
  return (
    <>
      {label.slice(0, pos)}
      <mark className="vmx-omni-mark">{label.slice(pos, pos + first.length)}</mark>
      {label.slice(pos + first.length)}
    </>
  );
}

const PLACEHOLDERS = [
  'ลองพิมพ์ "ketamine 12 kg แมว"…',
  'ถามได้เลย เช่น "วัคซีนพิษสุนัขบ้าฉีดกี่เข็ม"…',
  'สั่งได้เลย เช่น "จัดข้อสอบ COM5 20 ข้อ"…',
  'ลองพิมพ์รหัสวิชา เช่น 3104306…',
  'ค้นเอกสาร เช่น "anatomy ปี 1"…',
  'ค้นข้อสอบ อาจารย์ สรุปคลิป โน้ตของคุณ…',
];

// ── Answer cards (intent results — computed, never generated) ────────────

function DoseCard({ intent, onOpenCalc }) {
  const { drug, dose, perKg, weightKg, species } = intent;
  const speciesTh = species === 'cat' ? 'แมว' : species === 'dog' ? 'สุนัข' : null;
  const range = (r) => (r && r.lo != null ? `${r.lo}–${r.hi} ${r.unit}` : null);
  const perKgText = perKg?.perKg === false
    ? `${drug.doseLo}–${drug.doseHi} ${perKg.unit} ต่อตัว`
    : range({ ...perKg, lo: drug.doseLo, hi: drug.doseHi }) + '/kg';
  return (
    <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '14px 16px' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
        <span style={{ fontSize: 18 }} aria-hidden="true">💊</span>
        <strong style={{ fontSize: 16 }}>{drug.generic}</strong>
        <span style={{ fontSize: 12, color: 'var(--clr-ink-soft)' }}>{drug.category}</span>
        {speciesTh && (
          <span style={{ fontFamily: 'var(--vmx-mono)', fontSize: 11, padding: '1px 8px', borderRadius: 10, border: '1px solid var(--clr-border)' }}>
            {speciesTh}
          </span>
        )}
      </div>
      <div style={{ display: 'flex', gap: 18, flexWrap: 'wrap', margin: '10px 0 2px' }}>
        <div>
          <div style={{ fontSize: 11, color: 'var(--clr-ink-soft)' }}>ช่วงขนาดยา</div>
          <div style={{ fontFamily: 'var(--vmx-mono)', fontSize: 15, fontWeight: 600 }}>
            {perKgText} <span style={{ fontWeight: 400, fontSize: 12 }}>{drug.route}</span>
          </div>
        </div>
        {dose && dose.perKg && dose.lo != null && (
          <div>
            <div style={{ fontSize: 11, color: 'var(--clr-ink-soft)' }}>สำหรับ {weightKg} kg</div>
            <div style={{ fontFamily: 'var(--vmx-mono)', fontSize: 15, fontWeight: 700, color: 'var(--clr-sage-text)' }}>
              {dose.lo}{'–'}{dose.hi} {dose.unit} รวม
            </div>
          </div>
        )}
        {drug.freq && (
          <div>
            <div style={{ fontSize: 11, color: 'var(--clr-ink-soft)' }}>ความถี่</div>
            <div style={{ fontSize: 13 }}>{drug.freq}</div>
          </div>
        )}
      </div>
      {dose?.cappedFor && (
        <div style={{ fontSize: 12, color: 'var(--clr-rose-text)', marginTop: 6 }}>
          เพดานเฉพาะ{dose.cappedFor === 'cat' ? 'แมว' : 'สุนัข'}: ไม่เกิน {dose.cap} {dose.unit}/kg
        </div>
      )}
      {drug.note && (
        <div style={{ fontSize: 12, color: 'var(--clr-ink-soft)', marginTop: 6, lineHeight: 1.5 }}>
          {String(drug.note).slice(0, 160)}
        </div>
      )}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 10, flexWrap: 'wrap' }}>
        <button type="button" onClick={onOpenCalc}
          style={{ font: 'inherit', fontSize: 12.5, fontWeight: 600, cursor: 'pointer', border: '1px solid var(--clr-border)', background: 'var(--clr-surface-2)', color: 'var(--clr-ink)', borderRadius: 8, padding: '6px 12px' }}>
          🧮 เปิดเครื่องคิดเลขเต็ม
        </button>
        <span style={{ fontSize: 11, color: 'var(--clr-ink-soft)' }}>
          ช่วงอ้างอิงจากฐานข้อมูลยาในแอป — ตรวจกับข้อมูลยาปัจจุบันก่อนใช้จริง
        </span>
      </div>
    </div>
  );
}

function CourseCard({ intent, onOpenLibraryShelf, onPracticeSubject }) {
  const { code, meta } = intent;
  return (
    <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '14px 16px' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
        <span style={{ fontSize: 18 }} aria-hidden="true">{meta.icon || '📚'}</span>
        <strong style={{ fontSize: 16 }}>{meta.name}</strong>
        <span style={{ fontFamily: 'var(--vmx-mono)', fontSize: 12, color: 'var(--clr-ink-soft)' }}>{code}</span>
      </div>
      {meta.name_en && (
        <div style={{ fontSize: 12.5, color: 'var(--clr-ink-soft)', marginTop: 4 }}>{meta.name_en}</div>
      )}
      <div style={{ display: 'flex', gap: 8, marginTop: 10, flexWrap: 'wrap' }}>
        <button type="button" onClick={() => onOpenLibraryShelf(meta)}
          style={{ font: 'inherit', fontSize: 12.5, fontWeight: 600, cursor: 'pointer', border: '1px solid var(--clr-border)', background: 'var(--clr-surface-2)', color: 'var(--clr-ink)', borderRadius: 8, padding: '6px 12px' }}>
          📚 เปิดชั้นเอกสารวิชานี้
        </button>
        {meta.has_questions && (
          <button type="button" onClick={() => onPracticeSubject(meta.id)}
            style={{ font: 'inherit', fontSize: 12.5, fontWeight: 600, cursor: 'pointer', border: '1px solid var(--clr-border)', background: 'var(--clr-surface-2)', color: 'var(--clr-ink)', borderRadius: 8, padding: '6px 12px' }}>
            ❓ ฝึกข้อสอบวิชานี้
          </button>
        )}
      </div>
    </div>
  );
}

// ── Ask-the-corpus (the LLM layer, grounded end to end) ──────────────────
//
// Ctrl+Enter (or the ✦ row) sends the query to /api/wiki-explain with no
// subject/topic → the server retrieves the most relevant governed sections
// across the whole wiki and answers as CLAIMS citing sectionIds. Before
// anything renders, the claims are re-validated HERE against the app's own
// bundled corpus (dynamic import — the corpus chunk loads only when someone
// actually asks): a citation that does not exist in this build's wiki
// cannot be rendered as one, whatever the network said.

const ASK_STATUS = ['อ่านคลังความรู้ที่เกี่ยวข้อง…', 'เรียบเรียงคำตอบพร้อมที่มา…', 'ตรวจที่มาของทุกประโยค…'];

function AskAnswerCard({ ask, onOpenWiki, onClose }) {
  const [statusIdx, setStatusIdx] = useState(0);
  useEffect(() => {
    if (ask?.phase !== 'loading') return undefined;
    if (typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;
    const t = setInterval(() => setStatusIdx((i) => (i + 1) % ASK_STATUS.length), 1600);
    return () => clearInterval(t);
  }, [ask?.phase]);

  if (!ask) return null;

  if (ask.phase === 'loading') {
    return (
      <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '14px 16px' }} aria-live="polite">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span className="vmx-omni-spark" aria-hidden="true" style={{ color: 'var(--clr-sage-text)' }}>✦</span>
          <span style={{ fontSize: 13, color: 'var(--clr-ink-soft)' }}>{ASK_STATUS[statusIdx]}</span>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 12 }}>
          {[0, 1, 2].map((i) => (
            <div key={i} className="vmx-omni-shimmer" style={{ height: 12, maxWidth: 340 + i * 70 }} />
          ))}
        </div>
      </div>
    );
  }

  if (ask.phase === 'error') {
    return (
      <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '14px 16px' }}>
        <div style={{ fontSize: 13, color: 'var(--clr-ink-soft)' }}>{ask.message}</div>
      </div>
    );
  }

  const sectionMeta = new Map((ask.sections || []).map((s) => [s.sectionId, s]));
  return (
    <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '14px 16px' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap', marginBottom: 8 }}>
        <span aria-hidden="true" style={{ color: 'var(--clr-sage-text)' }}>✦</span>
        <strong style={{ fontSize: 13.5 }}>คำตอบจากคลังความรู้</strong>
        <span style={{ fontSize: 11, color: 'var(--clr-ink-soft)' }}>
          ตอบจากเนื้อหาที่ผ่านการตรวจแล้วเท่านั้น และบอกที่มาทุกประโยค
        </span>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {ask.claims.map((c) => {
          const label = ask.labels?.[c.supportType]?.th;
          return (
            <div key={c.id} className="vmx-omni-row" style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <div style={{ fontSize: 13.5, lineHeight: 1.6 }}>{c.text}</div>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', alignItems: 'center' }}>
                {label && (
                  <span style={{
                    fontFamily: 'var(--vmx-mono)', fontSize: 10.5, padding: '1px 8px', borderRadius: 10,
                    border: '1px solid var(--clr-border)',
                    color: c.supportType === 'vetwiki-verified' ? 'var(--clr-sage-text)'
                      : c.supportType === 'insufficient-evidence' ? 'var(--clr-ink-soft)' : 'var(--clr-gold-text)',
                  }}>
                    {label}
                  </span>
                )}
                {(c.support || []).map(({ sectionId }) => {
                  const m = sectionMeta.get(sectionId);
                  if (!m) return null;
                  return (
                    <button
                      key={sectionId}
                      type="button"
                      onClick={() => { onOpenWiki?.(m.subject, m.topic); onClose(); }}
                      title={m.heading}
                      style={{
                        all: 'unset', cursor: 'pointer', fontSize: 11, fontWeight: 600,
                        color: 'var(--clr-ocean-text)', padding: '1px 4px',
                      }}
                    >
                      → {m.topicTitle}
                    </button>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ── The palette ──────────────────────────────────────────────────────────

export default function CommandPalette({
  open,
  onClose,
  signedIn = false,
  scaffold = false,
  hasSupabase = true,
  selectedYear,
  ...handlers
}) {
  const [query, setQuery] = useState('');
  const [debouncedQuery, setDebouncedQuery] = useState('');
  const [activeIdx, setActiveIdx] = useState(0);
  const [expandedGroups, setExpandedGroups] = useState(() => new Set());
  const [placeholderIdx, setPlaceholderIdx] = useState(0);
  // sourceState: { [id]: { status: 'loading'|'ready'|'error', entries } }
  const [sourceState, setSourceState] = useState({});
  const [ask, setAsk] = useState(null); // null | loading | done | error
  const [agent, setAgent] = useState(null); // null | loading | confirm | refused | error
  // Touch has no Ctrl — the chip and hints must speak tap, not keys.
  const coarsePointer = useMemo(() => typeof matchMedia === 'function' && matchMedia('(pointer: coarse)').matches, []);
  const inputRef = useRef(null);

  // Voice input — the browser's own recognizer (th-TH), no key, no dependency.
  // The transcript lands in the SAME query state, so everything downstream
  // (streamed results, the ask row, auto-ask, the ⚡ agent row) works on a
  // spoken sentence exactly as on a typed one. Hidden where unsupported.
  const [voice, setVoice] = useState(null); // null | 'listening' | 'denied' | 'error'
  const recRef = useRef(null);
  const speechSupported = useMemo(
    () => typeof window !== 'undefined' && !!(window.SpeechRecognition || window.webkitSpeechRecognition),
    [],
  );
  const toggleVoice = () => {
    if (recRef.current) { try { recRef.current.stop(); } catch { /* already stopping */ } return; }
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) return;
    const rec = new SR();
    rec.lang = 'th-TH';
    rec.interimResults = true; // live transcript → results stream while speaking
    rec.continuous = false;
    let finalT = '';
    rec.onresult = (e) => {
      const t = Array.from(e.results).map((r) => r[0]?.transcript || '').join('').trim();
      if (t) { finalT = t; setQuery(t); }
    };
    rec.onerror = (e) => { setVoice(e?.error === 'not-allowed' || e?.error === 'service-not-allowed' ? 'denied' : 'error'); };
    rec.onend = () => {
      recRef.current = null;
      setVoice((v) => (v === 'listening' ? null : v));
      inputRef.current?.focus();
      // Hands-free: a finished spoken sentence acts on itself. A command
      // fetches its plan (execution still waits for the ทำเลย tap), a
      // question asks; a plain phrase just leaves its search results.
      // Action is checked first — "จัดข้อสอบ 20 ข้อได้ไหม" is a polite
      // command, not a question about the world.
      const t = finalT.trim();
      if (t.length >= 6 && looksLikeAction(t)) { lastAutoAsk.current = t; runAgent(t); }
      else if (t.length >= 8 && looksLikeQuestion(t)) { lastAutoAsk.current = t; runAsk(t); }
    };
    recRef.current = rec;
    setVoice('listening');
    try { rec.start(); } catch { recRef.current = null; setVoice('error'); }
  };
  useEffect(() => () => { try { recRef.current?.stop(); } catch { /* unmount race */ } }, []);
  const dialogRef = useModalFocus({ active: open, onClose, initialFocusRef: inputRef });
  const listRef = useRef(null);

  const staticItems = useMemo(() => buildStaticItems(), []);
  const visibleFeatureIds = useMemo(() => new Set(
    visibleFeatures(FEATURES, { signedIn, scaffold, hasSupabase, selectedYear }).map((feature) => feature.id),
  ), [signedIn, scaffold, hasSupabase, selectedYear]);

  // Async sources stream in while the palette is open. Each one caches at
  // module level (omni-sources), so the spinner shows once per session.
  useEffect(() => {
    if (!open) return undefined;
    let alive = true;
    for (const src of OMNI_SOURCES) {
      setSourceState((s) => (s[src.id]?.status === 'ready' ? s : { ...s, [src.id]: { status: 'loading', entries: [] } }));
      src.load().then(
        (entries) => { if (alive) setSourceState((s) => ({ ...s, [src.id]: { status: 'ready', entries } })); },
        (err) => {
          // The chip says "ออฟไลน์"; the console says why. A silent error
          // state cost 20 minutes of guessing the first time this shipped.
          console.error('[omni-source]', src.id, err);
          if (alive) setSourceState((s) => ({ ...s, [src.id]: { status: 'error', entries: [] } }));
        },
      );
    }
    return () => { alive = false; };
  }, [open]);

  const items = useMemo(() => {
    const base = staticItems.filter((item) => {
      if (item.featureId && !visibleFeatureIds.has(item.featureId)) return false;
      if (item.type === 'subject' && selectedYear != null && item.year != null) {
        return Number(item.year) === Number(selectedYear);
      }
      return true;
    });
    const async_ = Object.values(sourceState).flatMap((s) => s.entries || []);
    return base.concat(async_);
  }, [staticItems, visibleFeatureIds, selectedYear, sourceState]);

  const handlersRef = useRef(handlers);
  handlersRef.current = handlers;

  useEffect(() => {
    if (query === debouncedQuery) return undefined;
    const t = setTimeout(() => setDebouncedQuery(query), 60);
    return () => clearTimeout(t);
  }, [query, debouncedQuery]);

  // Rotating placeholder — decorative, so it parks on the first example
  // when the user asked for reduced motion.
  useEffect(() => {
    if (!open) return undefined;
    if (typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches) return undefined;
    const t = setInterval(() => setPlaceholderIdx((i) => (i + 1) % PLACEHOLDERS.length), 3500);
    return () => clearInterval(t);
  }, [open]);

  const hasQuery = !!debouncedQuery.trim();
  const intents = useMemo(() => (hasQuery ? detectIntents(debouncedQuery) : []), [hasQuery, debouncedQuery]);

  // Grouped result model. With a query: rank everything flat, then bucket
  // by type, order groups by their best-ranked hit. Without: recents first,
  // then the curated group order.
  const view = useMemo(() => {
    const recents = hasQuery ? [] : readRecents().map((r) => ({
      ...r,
      _labelLc: (r.label || '').toLowerCase(),
      _hayLc: (r.label || '').toLowerCase(),
      _recent: true,
    }));

    let groups;
    if (!hasQuery) {
      const buckets = new Map();
      if (recents.length) buckets.set('recent', recents);
      for (const item of items) {
        const key = item.type;
        if (!buckets.has(key)) buckets.set(key, []);
        buckets.get(key).push(item);
      }
      groups = [...buckets.entries()]
        .sort((a, b) => GROUP_ORDER.indexOf(a[0]) - GROUP_ORDER.indexOf(b[0]))
        .map(([type, list]) => ({ type, list }));
    } else {
      const ranked = rankItems(items, debouncedQuery);
      const buckets = new Map();
      for (const { item } of ranked) {
        const key = item.type;
        if (!buckets.has(key)) buckets.set(key, []);
        buckets.get(key).push(item);
      }
      groups = [...buckets.entries()].map(([type, list]) => ({ type, list }));
    }

    // Apply per-group caps and lay out the flat keyboard order. A
    // question-shaped query puts the ask row first, so plain Enter asks.
    const flat = [];
    const askInFlow = hasQuery && looksLikeQuestion(debouncedQuery.trim());
    if (askInFlow) flat.push({ type: 'ask' });
    const sections = groups.map(({ type, list }) => {
      const cap = expandedGroups.has(type) ? GROUP_CAP_EXPANDED : GROUP_CAP;
      const shown = list.slice(0, cap);
      const startIdx = flat.length;
      flat.push(...shown);
      return { type, items: shown, startIdx, total: list.length, shown: shown.length };
    });
    return { sections, flat, askInFlow };
  }, [items, debouncedQuery, hasQuery, expandedGroups]);

  const sourcesLoading = Object.values(sourceState).some((s) => s.status === 'loading');

  const indexTotal = items.length;

  useEffect(() => {
    if (open) {
      setQuery('');
      setDebouncedQuery('');
      setActiveIdx(0);
      setExpandedGroups(new Set());
      setAsk(null);
      setAgent(null);
      setVoice(null);
    } else {
      try { recRef.current?.stop(); } catch { /* closing while idle */ }
    }
    return undefined;
  }, [open]);

  useEffect(() => { setActiveIdx(0); }, [debouncedQuery]);

  useEffect(() => {
    if (!listRef.current) return;
    const el = listRef.current.querySelector(`[data-flat-idx="${activeIdx}"]`);
    if (el && typeof el.scrollIntoView === 'function') {
      el.scrollIntoView({ block: 'nearest' });
    }
  }, [activeIdx]);

  if (!open) return null;

  const fire = (item) => {
    if (item.type === 'ask') { runAsk(); return; }
    pushRecent(item);
    if (item.type === 'library-doc') {
      // Same open logic as the shelf: PDFs navigate to the reader instantly
      // (the reader mints the link while its own chunk loads), everything
      // else opens as a plain URL in a new tab.
      const doc = item.payload;
      recordRecentDoc(doc);
      onClose();
      if (docOpenMode(doc).action === 'read') {
        handlersRef.current.onOpenLibraryDoc?.(readerPayload(doc));
        return;
      }
      // Open the tab synchronously — popup blockers only trust window.open
      // during the click, and the mint takes longer than that trust lasts.
      const win = window.open('', '_blank');
      if (win) { try { win.opener = null; } catch { /* hardened browsers */ } }
      resolveDocUrl(doc).then(
        (url) => {
          if (win) win.location.replace(url);
          else window.open(url, '_blank', 'noopener,noreferrer');
        },
        () => {
          if (win) { try { win.close(); } catch { /* already gone */ } }
          handlersRef.current.goView?.('library'); // resolution failed → land on the shelf, which shows its own error UI
        },
      );
      return;
    }
    if (item.type === 'drug') {
      try { window.dispatchEvent(new Event('vmx-open-vetcalc')); } catch { /* no-op */ }
      onClose();
      return;
    }
    runItem(item, handlersRef.current);
    onClose();
  };

  const runAsk = async (spoken) => {
    const question = (typeof spoken === 'string' ? spoken : query).trim();
    if (question.length < 8 || ask?.phase === 'loading') return;
    setAsk({ phase: 'loading' });
    try {
      const res = await fetch('/api/wiki-explain', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ question }),
      });
      if (res.status === 503) { setAsk({ phase: 'error', message: 'ยังไม่ได้เปิดใช้การถามจากคลังความรู้ — เนื้อหาทั้งหมดยังอ่านได้ตามปกติ' }); return; }
      if (res.status === 429) { setAsk({ phase: 'error', message: 'ถามบ่อยเกินไป ลองใหม่ในอีกสักครู่' }); return; }
      if (!(res.headers.get('content-type') || '').includes('application/json')) {
        setAsk({ phase: 'error', message: 'การถามใช้ได้เฉพาะบนเว็บจริง (vetmock.vercel.app)' }); return;
      }
      if (!res.ok) { setAsk({ phase: 'error', message: 'ตอบไม่สำเร็จ ลองใหม่อีกครั้ง' }); return; }
      const data = await res.json();
      // Isomorphic guard: rebuild the allowed-citation map from THIS
      // build's own generated citation index and validate again. The index
      // carries exactly what validateAnswer consumes (topicId + verified per
      // sectionId, drift-gated against the corpus), so the guard costs ~40 KB
      // instead of the full corpus barrel — and it is TIGHTER than loading
      // topics: only sections the server says it supplied, intersected with
      // sections this build really has, can validate a citation.
      const [{ validateAnswer, ANSWER_SUPPORT_LABEL }, { CITATION_INDEX }] = await Promise.all([
        import('../lib/vetwiki/answer.js'),
        import('../lib/vetwiki/citation-index.generated.js'),
      ]);
      const allowed = new Map();
      for (const m of data.meta?.sections || []) {
        const id = String(m?.sectionId || '');
        const hit = CITATION_INDEX[id];
        if (!hit) continue; // server named a section this build does not have
        allowed.set(id, { sectionId: id, topicId: hit[0], verified: !!hit[1] });
      }
      const { claims } = validateAnswer(data.claims, allowed);
      if (!claims.length) { setAsk({ phase: 'error', message: 'ยังตอบจากเนื้อหาที่มีไม่ได้' }); return; }
      setAsk({ phase: 'done', claims, sections: data.meta?.sections || [], labels: ANSWER_SUPPORT_LABEL });
    } catch {
      setAsk({ phase: 'error', message: 'เชื่อมต่อไม่ได้ ลองใหม่อีกครั้ง' });
    }
  };

  // A settled question with an empty list should not need ANY key — the
  // person already typed what they want to know. Once per query string;
  // never while sources are still streaming in (results may yet arrive).
  const lastAutoAsk = useRef('');
  useEffect(() => {
    const q = debouncedQuery.trim();
    if (q.length < 12 || !looksLikeQuestion(q)) return;
    if (sourcesLoading) return;
    if (view.flat.some((i) => i.type !== 'ask')) return;
    if (lastAutoAsk.current === q || ask?.phase === 'loading') return;
    lastAutoAsk.current = q;
    runAsk();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- runAsk reads live state
  }, [debouncedQuery, view, sourcesLoading]);

  const runAgent = async (spoken) => {
    const utterance = (typeof spoken === 'string' ? spoken : query).trim();
    if (utterance.length < 6 || agent?.phase === 'loading') return;
    setAgent({ phase: 'loading' });
    try {
      const res = await fetch('/api/agent-action', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ utterance }),
      });
      if (res.status === 503) { setAgent({ phase: 'error', message: 'ยังไม่ได้เปิดใช้ผู้ช่วยสั่งงาน' }); return; }
      if (res.status === 429) { setAgent({ phase: 'error', message: 'สั่งบ่อยเกินไป ลองใหม่ในอีกสักครู่' }); return; }
      if (!(res.headers.get('content-type') || '').includes('application/json')) {
        setAgent({ phase: 'error', message: 'ผู้ช่วยสั่งงานใช้ได้เฉพาะบนเว็บจริง (vetmock.vercel.app)' }); return;
      }
      if (!res.ok) { setAgent({ phase: 'error', message: 'สั่งไม่สำเร็จ ลองใหม่อีกครั้ง' }); return; }
      const data = await res.json();
      if (!data.action) { setAgent({ phase: 'refused', message: data.reason || 'ยังไม่มีสิ่งที่ตรงกับคำสั่งนี้ในแอป' }); return; }
      // The server already validated every id against the live catalog —
      // the student still confirms before anything runs.
      setAgent({ phase: 'confirm', action: data.action, say: data.say });
    } catch {
      setAgent({ phase: 'error', message: 'เชื่อมต่อไม่ได้ ลองใหม่อีกครั้ง' });
    }
  };

  const executeAgent = (action) => {
    const h = handlersRef.current;
    if (action.type === 'practice') { h.onPractice?.(action.invoke); onClose(); return; }
    if (action.type === 'library') {
      try { sessionStorage.setItem('vmx-library-q', action.subjectName || ''); } catch { /* nicety */ }
      h.goView?.('library'); onClose(); return;
    }
    if (action.type === 'wiki') { h.onOpenWiki?.(action.subject, action.topic); onClose(); return; }
    if (action.type === 'feature') {
      const f = FEATURES.find((x) => x.id === action.id);
      if (f) runItem({ type: 'action', payload: f.invoke }, h);
      onClose();
    }
  };

  const openLibraryShelf = (meta) => {
    try { sessionStorage.setItem('vmx-library-subject', meta.id || ''); } catch { /* nicety */ }
    handlersRef.current.goView?.('library');
    onClose();
  };
  const practiceSubject = (subjectId) => {
    handlersRef.current.setSubject?.(subjectId);
    handlersRef.current.goView?.('topic-select');
    onClose();
  };

  const handleKey = (e) => {
    if (e.key === 'Escape') { e.preventDefault(); onClose(); }
    else if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActiveIdx((i) => Math.min(view.flat.length - 1, i + 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActiveIdx((i) => Math.max(0, i - 1));
    } else if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      runAsk();
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const item = view.flat[activeIdx];
      if (item) fire(item);
    }
  };

  return (
    <div
      className="vmx-modal-overlay"
      onClick={onClose}
      style={{ alignItems: 'flex-start', paddingTop: 'min(12vh, 90px)', backdropFilter: 'blur(5px)' }}
    >
      <div
        ref={dialogRef}
        className="vmx-modal"
        onClick={(e) => e.stopPropagation()}
        style={{ maxWidth: 640, padding: 0, overflow: 'hidden' }}
        role="dialog"
        aria-modal="true"
        tabIndex={-1}
        data-vmx-modal="true"
        aria-label="ค้นหาอัจฉริยะ"
      >
        <div className="vmx-omni-topbar" aria-hidden="true" />

        {/* Search input */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          padding: '16px 20px',
          borderBottom: '1px solid var(--clr-border)',
        }}>
          <span className="vmx-omni-spark" aria-hidden="true" style={{ fontSize: 18, color: 'var(--clr-sage-text)' }}>✦</span>
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              // Typing means the person moved on — clear a stale mic hint.
              setVoice((v) => (v === 'denied' || v === 'error' ? null : v));
            }}
            onKeyDown={handleKey}
            placeholder={PLACEHOLDERS[placeholderIdx]}
            aria-label="ค้นหาใน VetMock"
            style={{
              all: 'unset',
              flex: 1,
              fontSize: 16,
              color: 'var(--clr-ink)',
              fontFamily: 'inherit',
              minWidth: 0,
            }}
            autoComplete="off"
            spellCheck="false"
          />
          {speechSupported && (
            <button
              type="button"
              onClick={toggleVoice}
              aria-label={voice === 'listening' ? 'หยุดฟังเสียง' : 'สั่งงานหรือถามด้วยเสียง'}
              aria-pressed={voice === 'listening'}
              title={voice === 'listening' ? 'หยุดฟังเสียง' : 'สั่งงานหรือถามด้วยเสียง'}
              style={{
                all: 'unset', cursor: 'pointer', width: 34, height: 34, display: 'flex',
                alignItems: 'center', justifyContent: 'center', borderRadius: 8, flexShrink: 0,
                color: voice === 'listening' ? 'var(--clr-rose-text)' : 'var(--clr-ink-soft)',
                background: voice === 'listening' ? 'color-mix(in srgb, currentColor 12%, transparent)' : 'transparent',
              }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M12 2a3 3 0 0 0-3 3v6a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3z" />
                <path d="M19 10v1a7 7 0 0 1-14 0v-1" />
                <line x1="12" y1="18" x2="12" y2="22" />
              </svg>
            </button>
          )}
          <span style={{
            fontFamily: 'var(--vmx-mono)',
            fontSize: 11,
            color: 'var(--clr-ink-soft)',
            padding: '2px 6px',
            border: '1px solid var(--clr-border)',
            borderRadius: 4,
          }}>esc</span>
        </div>

        {/* Voice status lives BELOW the row: inline it squeezed the input
            to 52px on a 375px phone whenever the denied hint showed. */}
        {voice && (
          <div aria-live="polite" style={{
            padding: '6px 20px 0',
            fontSize: 11.5,
            color: voice === 'listening' ? 'var(--clr-rose-text)' : 'var(--clr-ink-soft)',
          }}>
            {voice === 'listening'
              ? 'ฟังอยู่… พูดได้เลย'
              : voice === 'denied'
                ? 'ไมค์ถูกปิดสิทธิ์ในเบราว์เซอร์ — เปิดสิทธิ์ไมโครโฟนแล้วลองใหม่'
                : 'ฟังไม่สำเร็จ ลองใหม่อีกครั้ง'}
          </div>
        )}

        {/* Ask-the-corpus. Question-shaped queries put this row FIRST in
            the keyboard order (plain Enter asks); other queries keep it as
            a tap/click affordance so Enter still opens the top result. */}
        {hasQuery && debouncedQuery.trim().length >= 8 && (
          <button
            type="button"
            onClick={runAsk}
            data-flat-idx={view.askInFlow ? 0 : undefined}
            onMouseEnter={view.askInFlow ? () => setActiveIdx(0) : undefined}
            className="vmx-omni-row"
            style={{
              all: 'unset', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 10,
              boxSizing: 'border-box', width: 'calc(100% - 24px)', margin: '8px 12px 0',
              padding: '10px 12px', minHeight: 44, borderRadius: 10,
              border: '1px dashed color-mix(in srgb, var(--clr-sage) 55%, var(--clr-border))',
              background: view.askInFlow && activeIdx === 0 ? 'var(--clr-surface-2)' : 'transparent',
              color: 'var(--clr-ink)', fontSize: 13,
            }}
          >
            <span className="vmx-omni-spark" aria-hidden="true" style={{ color: 'var(--clr-sage-text)' }}>✦</span>
            <span style={{ flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              ถามคลังความรู้: “{debouncedQuery.trim()}”
            </span>
            <span style={{ fontFamily: 'var(--vmx-mono)', fontSize: 10.5, color: 'var(--clr-ink-soft)', padding: '2px 6px', border: '1px solid var(--clr-border)', borderRadius: 4, whiteSpace: 'nowrap' }}>
              {coarsePointer ? 'แตะถาม' : view.askInFlow ? '↵' : 'ctrl ↵'}
            </span>
          </button>
        )}
        <ErrorBoundary fallback={null}>
          <AskAnswerCard ask={ask} onOpenWiki={handlersRef.current.onOpenWiki} onClose={onClose} />
        </ErrorBoundary>

        {/* Agentic action — the model picks from a validated catalog, the
            student confirms, the palette's own dispatch executes. */}
        {hasQuery && looksLikeAction(debouncedQuery.trim()) && !intents.length && (
          <button
            type="button"
            onClick={runAgent}
            className="vmx-omni-row"
            style={{
              all: 'unset', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 10,
              boxSizing: 'border-box', width: 'calc(100% - 24px)', margin: '8px 12px 0',
              padding: '10px 12px', minHeight: 44, borderRadius: 10,
              border: '1px dashed color-mix(in srgb, var(--clr-gold) 55%, var(--clr-border))',
              color: 'var(--clr-ink)', fontSize: 13,
            }}
          >
            <span aria-hidden="true" style={{ color: 'var(--clr-gold-text)' }}>⚡</span>
            <span style={{ flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              สั่งให้จัดการ: “{debouncedQuery.trim()}”
            </span>
            <span style={{ fontFamily: 'var(--vmx-mono)', fontSize: 10.5, color: 'var(--clr-ink-soft)', padding: '2px 6px', border: '1px solid var(--clr-border)', borderRadius: 4, whiteSpace: 'nowrap' }}>
              {coarsePointer ? 'แตะสั่ง' : 'คลิก'}
            </span>
          </button>
        )}
        {agent?.phase === 'loading' && (
          <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '12px 16px', display: 'flex', gap: 10, alignItems: 'center' }} aria-live="polite">
            <span className="vmx-omni-spark" aria-hidden="true" style={{ color: 'var(--clr-gold-text)' }}>⚡</span>
            <span style={{ fontSize: 13, color: 'var(--clr-ink-soft)' }}>กำลังอ่านคำสั่งและเทียบกับสิ่งที่แอปทำได้จริง…</span>
          </div>
        )}
        {(agent?.phase === 'refused' || agent?.phase === 'error') && (
          <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '12px 16px' }}>
            <span style={{ fontSize: 13, color: 'var(--clr-ink-soft)' }}>{agent.message}</span>
          </div>
        )}
        {agent?.phase === 'confirm' && (
          <div className="vmx-omni-card" style={{ margin: '10px 12px 4px', padding: '14px 16px' }}>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
              <span aria-hidden="true" style={{ color: 'var(--clr-gold-text)' }}>⚡</span>
              <span style={{ fontSize: 13.5, lineHeight: 1.6 }}>{agent.say}</span>
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
              <button type="button" onClick={() => executeAgent(agent.action)}
                style={{ font: 'inherit', fontSize: 12.5, fontWeight: 700, cursor: 'pointer', border: '1px solid var(--clr-border)', background: 'var(--clr-sage)', color: 'var(--clr-ink)', borderRadius: 8, padding: '7px 14px' }}>
                ทำเลย
              </button>
              <button type="button" onClick={() => setAgent(null)}
                style={{ font: 'inherit', fontSize: 12.5, cursor: 'pointer', border: '1px solid var(--clr-border)', background: 'var(--clr-surface-2)', color: 'var(--clr-ink)', borderRadius: 8, padding: '7px 14px' }}>
                ยกเลิก
              </button>
            </div>
          </div>
        )}

        {/* Answer cards — intent hits computed from real data */}
        {intents.map((intent) => (
          intent.kind === 'dose'
            ? <DoseCard key="dose" intent={intent} onOpenCalc={() => { try { window.dispatchEvent(new Event('vmx-open-vetcalc')); } catch { /* no-op */ } onClose(); }} />
            : <CourseCard key="course" intent={intent} onOpenLibraryShelf={openLibraryShelf} onPracticeSubject={practiceSubject} />
        ))}

        {/* Source status — what the index knows right now */}
        {!hasQuery && (
          <div style={{
            padding: '8px 20px',
            display: 'flex',
            gap: 8,
            flexWrap: 'wrap',
            alignItems: 'center',
            borderBottom: '1px solid var(--clr-border)',
            background: 'var(--clr-bg)',
          }}>
            <span style={{ fontFamily: 'var(--vmx-mono)', fontSize: 11, color: 'var(--clr-ink-soft)', padding: '2px 8px', border: '1px solid var(--clr-border)', borderRadius: 10 }}>
              {indexTotal.toLocaleString()} รายการในดัชนี
            </span>
            {OMNI_SOURCES.map((src) => {
              const st = sourceState[src.id];
              return (
                <span key={src.id} style={{ fontFamily: 'var(--vmx-mono)', fontSize: 11, color: 'var(--clr-ink-soft)', padding: '2px 8px', border: '1px solid var(--clr-border)', borderRadius: 10, display: 'inline-flex', gap: 5, alignItems: 'center' }}>
                  <span aria-hidden="true">{src.icon}</span>
                  {src.label}
                  {st?.status === 'loading' && ' กำลังโหลด…'}
                  {st?.status === 'ready' && ` ${st.entries.length.toLocaleString()}`}
                  {st?.status === 'error' && ' ออฟไลน์'}
                </span>
              );
            })}
          </div>
        )}

        {/* Results — grouped, streamed, keyboard-navigable across groups */}
        <div ref={listRef} style={{ maxHeight: '52vh', overflowY: 'auto', padding: 4 }}>
          {view.flat.filter((it) => it.type !== 'ask').length === 0 && !sourcesLoading && intents.length === 0 && !ask && (
            <div style={{ padding: '32px 20px', textAlign: 'center', color: 'var(--clr-ink-soft)', fontSize: 14 }}>
              {debouncedQuery.trim().length >= 8
                ? <>ไม่พบรายการที่ตรง — ลองถามคลังความรู้ด้านบนได้เลย</>
                : <>ไม่พบที่ตรงกับ "{query}"</>}
            </div>
          )}
          {view.sections.map((section) => (
            <div key={section.type}>
              <div style={{
                padding: '10px 16px 4px',
                fontSize: 11,
                fontFamily: 'var(--vmx-mono)',
                color: 'var(--clr-ink-soft)',
                textTransform: 'uppercase',
                letterSpacing: '0.1em',
                fontWeight: 600,
                display: 'flex',
                alignItems: 'baseline',
                gap: 6,
              }}>
                <span aria-hidden="true">{GROUP_META[section.type]?.icon}</span>
                {GROUP_META[section.type]?.label || section.type}
                <span style={{ fontWeight: 400 }}>{section.total.toLocaleString()}</span>
              </div>
              {section.items.map((item, iInGroup) => {
                const flatIdx = section.startIdx + iInGroup;
                const active = flatIdx === activeIdx;
                return (
                  <button
                    key={`${item.type}-${item.label}-${flatIdx}`}
                    data-flat-idx={flatIdx}
                    className="vmx-omni-row"
                    onClick={() => fire(item)}
                    onMouseEnter={() => setActiveIdx(flatIdx)}
                    style={{
                      all: 'unset',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: 12,
                      width: '100%',
                      boxSizing: 'border-box',
                      padding: '9px 16px',
                      borderRadius: 8,
                      background: active ? 'var(--clr-surface-2)' : 'transparent',
                      transition: 'background 0.05s',
                      animationDelay: `${Math.min(iInGroup, 8) * 14}ms`,
                    }}
                  >
                    <span style={{ fontSize: 20, flex: '0 0 auto' }}>{item.icon}</span>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{
                        fontSize: 14,
                        fontWeight: 500,
                        color: 'var(--clr-ink)',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}>
                        <HighlightedLabel label={item.label} query={debouncedQuery} />
                      </div>
                      {item.hint && (
                        <div style={{
                          fontSize: 11,
                          color: 'var(--clr-ink-soft)',
                          fontFamily: 'var(--vmx-mono)',
                          marginTop: 2,
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}>
                          {item.hint}
                        </div>
                      )}
                    </div>
                    {active && (
                      <span style={{ fontFamily: 'var(--vmx-mono)', fontSize: 11, color: 'var(--clr-ink-soft)', flex: '0 0 auto' }}>↵</span>
                    )}
                  </button>
                );
              })}
              {section.shown < section.total && (
                <button
                  type="button"
                  onClick={() => setExpandedGroups((prev) => new Set(prev).add(section.type))}
                  style={{
                    all: 'unset',
                    cursor: 'pointer',
                    display: 'block',
                    boxSizing: 'border-box',
                    width: '100%',
                    padding: '6px 16px 10px 48px',
                    fontSize: 12,
                    color: 'var(--clr-sage-text)',
                    fontWeight: 600,
                  }}
                >
                  แสดงเพิ่ม ({(section.total - section.shown).toLocaleString()} รายการ)
                </button>
              )}
            </div>
          ))}
          {sourcesLoading && (
            <div style={{ padding: '8px 16px 14px', display: 'flex', flexDirection: 'column', gap: 8 }} aria-label="กำลังโหลดแหล่งข้อมูล">
              {[0, 1, 2].map((i) => (
                <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                  <div className="vmx-omni-shimmer" style={{ width: 22, height: 22, borderRadius: 6 }} />
                  <div className="vmx-omni-shimmer" style={{ height: 12, flex: 1, maxWidth: 300 + i * 60 }} />
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer */}
        <div style={{
          padding: '10px 16px',
          borderTop: '1px solid var(--clr-border)',
          background: 'var(--clr-bg)',
          fontFamily: 'var(--vmx-mono)',
          fontSize: 11,
          color: 'var(--clr-ink-soft)',
          display: 'flex',
          gap: 16,
          flexWrap: 'wrap',
        }}>
          <span>↑↓ เลื่อน</span>
          <span>↵ เลือก</span>
          <span>esc ปิด</span>
          <span>{coarsePointer ? 'แตะ ✦ เพื่อถาม' : 'ctrl ↵ ถามคลังความรู้'}</span>
          <span style={{ marginLeft: 'auto' }}>
            {hasQuery ? `${view.flat.length} ผลลัพธ์` : 'ดัชนีสร้างสดจากข้อมูลจริง'}
          </span>
        </div>
      </div>
    </div>
  );
}
