// ============================================================
// LecturerSets — the paper as its lecturers write it
// ============================================================
// One card per lecturer: who they are, the format their part takes, and a
// swipeable row of the title slides they taught from. A tap on a slide opens
// practice on that deck's topics in the lecturer's format; the button under
// the row opens the whole part.
//
// The number on every button comes from a phase-scoped, per-format count
// table generated by the same rule the session applies, so "ถูกผิด 6 ข้อ"
// is what a tap will actually serve. Where a deck has no question in the
// lecturer's format yet, the card says so and offers the mixed set instead of
// opening an empty session.
// ============================================================
import { LECTURER_SETS, LECTURER_SET_SCOPE, FORMAT_LABEL, lecturerTopics } from '../data/lecturer-sets.js';
import { LECTURE_COVERS } from '../data/art.js';
import { Q_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE, Q_PAST_PAPER_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE } from '../data/q-kind-counts.generated.js';

const TH_MONTH = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'];
function thaiDate(iso) {
  const [, m, d] = String(iso || '').split('-').map(Number);
  return m ? `${d} ${TH_MONTH[m - 1]}` : '';
}

export default function LecturerSets({ subject, topics = [], onStart, onOpenInstructor, selectedPhase = LECTURER_SET_SCOPE.phase }) {
  const set = LECTURER_SETS[subject];
  if (!set || typeof onStart !== 'function') return null;

  const labelOf = (topicId) => topics.find((t) => t.id === topicId)?.label || topicId;
  const kindTable = Q_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE[selectedPhase]?.[subject] || {};
  // `_matchCovers` marks a matching set filed under another topic whose bank
  // names this one. A deck cover counts it (the set does include that
  // disease); the lecturer's whole-part button does not, or one set spanning
  // five decks would be counted five times.
  const countOf = (topicIds, kind, { covers = false } = {}) => topicIds.reduce((sum, id) => {
    const row = kindTable[id] || {};
    if (kind === 'all') return sum + Object.entries(row).reduce((a, [k, v]) => (k.startsWith('_') ? a : a + v), 0);
    return sum + (row[kind] || 0) + (covers && kind === 'match' ? (row._matchCovers || 0) : 0);
  }, 0);
  const covers = LECTURE_COVERS[subject] || {};
  // The pool category for a format: ปรนัย must exclude tf and match, which
  // the plain 'mcq' category lumps in (see buildExamPool).
  const categoryOf = (format) => (format === 'mcq' ? 'mcq-only' : format);
  // Past papers only, for the third button. Counts sum the lecturer's own
  // topics; the pool would also admit a set filed under another topic that
  // names one of these diseases, but such a set's home topic is the same
  // lecturer's today, so the number and the session agree.
  const pastTable = Q_PAST_PAPER_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE[selectedPhase]?.[subject] || {};
  const pastCountOf = (topicIds, kind) => topicIds.reduce((sum, id) => sum + ((pastTable[id] || {})[kind] || 0), 0);

  return (
    <div className="vmx-lect-list">
      <p className="vmx-lect-intro">
        กลางภาค {thaiDate(set.examDate)} — {set.coverage} แยกตามอาจารย์ผู้สอนและรูปแบบข้อสอบที่แต่ละท่านใช้
      </p>
      {set.lecturers.map((lec) => {
        const all = lecturerTopics(lec);
        const inFormat = countOf(all, lec.format);
        const inAny = countOf(all, 'all');
        const pastInFormat = pastCountOf(all, lec.format);
        const formatLabel = FORMAT_LABEL[lec.format] || lec.format;
        // A matching question is a whole printed set (one answer list, the
        // items down the page), so it is counted in ชุด, not ข้อ.
        const unit = lec.format === 'match' ? 'ชุด' : 'ข้อ';
        const wholeCategory = inFormat > 0 ? categoryOf(lec.format) : 'all';
        const wholeCount = inFormat > 0 ? inFormat : inAny;
        const wholeLabel = inFormat > 0
          ? `ฝึกแบบ${formatLabel}ทุกหัวข้อของอาจารย์ (${wholeCount} ${unit})`
          : `ยังไม่มีข้อแบบ${formatLabel} ฝึกรวมทุกประเภท (${wholeCount} ข้อ)`;
        return (
          <article key={lec.id} className="vmx-lect" aria-label={lec.name}>
            <header className="vmx-lect-head">
              <button
                type="button"
                className="vmx-lect-name"
                onClick={() => onOpenInstructor?.(lec.lecturer)}
                title="ดูโปรไฟล์อาจารย์"
              >
                {lec.name}
              </button>
              <span className={`vmx-lect-chip${lec.announced ? '' : ' is-unannounced'}`}>
                {formatLabel}{lec.count ? ` ${lec.count} ข้อ` : ''}
              </span>
              <span className="vmx-lect-note">{lec.note}</span>
            </header>

            <div className="vmx-lect-strip" role="list" aria-label={`สไลด์ที่ ${lec.name} สอน`}>
              {lec.sessions.map((s) => s.decks.map((deck) => {
                const art = covers[deck.cover];
                const title = deck.title || labelOf(deck.topics[0]);
                const n = countOf(deck.topics, lec.format, { covers: true });
                const nAll = countOf(deck.topics, 'all');
                const usable = n > 0 ? categoryOf(lec.format) : 'all';
                const shown = n > 0 ? n : nAll;
                const countText = n > 0
                  ? `${formatLabel} ${n} ${unit}`
                  : (nAll > 0 ? `ยังไม่มีข้อแบบ${formatLabel} (รวม ${nAll} ข้อ)` : 'ยังไม่มีข้อสอบ');
                return (
                  <button
                    key={`${s.n}-${deck.cover}`}
                    type="button"
                    role="listitem"
                    className="vmx-lect-cover"
                    disabled={shown === 0}
                    aria-label={`${title} คาบ ${s.n} ${thaiDate(s.date)}, ${countText}`}
                    onClick={() => onStart({ subjectId: subject, topics: deck.topics, questionCategory: usable })}
                  >
                    {art ? <img src={art.src} alt={art.alt} loading="lazy" decoding="async" /> : <span className="vmx-lect-cover-blank" aria-hidden="true" />}
                    <span className="t">{title}</span>
                    <span className="c">{countText}</span>
                    <span className="s">คาบ {s.n} ({thaiDate(s.date)})</span>
                  </button>
                );
              }))}
            </div>

            <div className="vmx-lect-actions">
              <button
                type="button"
                className="vmx-lect-btn is-primary"
                disabled={wholeCount === 0}
                onClick={() => onStart({ subjectId: subject, topics: all, questionCategory: wholeCategory })}
              >
                {wholeLabel}
              </button>
              {lec.count && inFormat >= lec.count && (
                <button
                  type="button"
                  className="vmx-lect-btn"
                  onClick={() => onStart({ subjectId: subject, topics: all, questionCategory: categoryOf(lec.format), numQuestions: lec.count })}
                >
                  จำลองชุด {lec.count} ข้อ
                </button>
              )}
              {pastInFormat > 0 && (
                <button
                  type="button"
                  className="vmx-lect-btn"
                  onClick={() => onStart({ subjectId: subject, topics: all, questionCategory: categoryOf(lec.format), pastPaperOnly: true })}
                >
                  ฝึกเฉพาะข้อสอบเก่า ({pastInFormat} {unit})
                </button>
              )}
            </div>
          </article>
        );
      })}
    </div>
  );
}
