// ============================================================
// LecturerSets — the paper as its lecturers write it
// ============================================================
// One card per lecturer: who they are, the format their part takes, and a
// swipeable row of the title slides they taught from. A tap on a slide opens
// practice on that deck's topics in the lecturer's format; the button under
// the row opens the whole part.
//
// The number on every button comes from a phase-scoped, per-format count
// table generated by the same rule the session applies, so "ถูกผิด 6 ข้อ"
// is what a tap will actually serve. Where a deck has no question in the
// lecturer's format yet, the card says so and offers the mixed set instead of
// opening an empty session.
// ============================================================
import { Fragment, useEffect, useState } from 'react';
import { LECTURER_SETS, LECTURER_SET_SCOPE, FORMAT_LABEL, lecturerTopics } from '../data/lecturer-sets.js';
import { getLibraryCatalogFast, readerPayload, recordRecentDoc, resolveDocUrl } from '../lib/library.js';
import { LECTURE_COVERS } from '../data/art.js';
import { RevealTimingToggle, REVEAL_ROW, REVEAL_END, writeRevealTiming } from './AnswerReveal.jsx';
import { Q_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE, Q_PAST_PAPER_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE } from '../data/q-kind-counts.generated.js';

const TH_MONTH = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'];
function thaiDate(iso) {
  const [, m, d] = String(iso || '').split('-').map(Number);
  return m ? `${d} ${TH_MONTH[m - 1]}` : '';
}

// Save bytes under a name. Eight lines kept here rather than importing
// pdf-export.js, which would drag pdf-lib into this lazy chunk.
function saveBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

const DownloadGlyph = () => (
  <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <path d="M8 2v8M4.5 6.5 8 10l3.5-3.5M2.5 12.5h11" />
  </svg>
);

export default function LecturerSets({ subject, topics = [], onStart, onOpenInstructor, onOpenDoc = null, selectedPhase = LECTURER_SET_SCOPE.phase, instantFeedback = true, setInstantFeedback = null }) {
  const set = LECTURER_SETS[subject];

  // The deck's own slides: a deck names its library_docs slug
  // (lecturer-sets.js) and the catalog row supplies the reader payload.
  // Session snapshot first, the fresh fetch after; no catalog, no pill.
  const wantDocs = Boolean(onOpenDoc && set?.lecturers.some((l) => l.sessions.some((s) => s.decks.some((d) => d.doc))));
  const [docsBySlug, setDocsBySlug] = useState(null);
  useEffect(() => {
    if (!wantDocs) return undefined;
    let live = true;
    const index = (r) => new Map((r?.docs || []).filter((d) => d?.slug).map((d) => [d.slug, d]));
    const { stale, fresh } = getLibraryCatalogFast();
    stale.then((s) => { if (live && s) setDocsBySlug((cur) => cur || index(s)); }).catch(() => {});
    fresh.then((f) => { if (live) setDocsBySlug(index(f)); }).catch(() => {});
    return () => { live = false; };
  }, [wantDocs]);
  const openDeckDoc = (doc) => { recordRecentDoc(doc); onOpenDoc(readerPayload(doc)); };
  // The file itself, saved under the deck's title. The library mints a
  // same-origin URL for its own storage (so the bytes can be fetched and
  // named); a Google Drive document is opened in a new tab instead.
  const [dlSlug, setDlSlug] = useState(null);
  const [dlNote, setDlNote] = useState('');
  const downloadDeck = async (doc) => {
    if (dlSlug) return;
    setDlSlug(doc.slug);
    setDlNote('');
    try {
      const url = await resolveDocUrl(doc);
      if (doc.storage_provider === 'google-drive') {
        window.open(url, '_blank', 'noopener');
        return;
      }
      const name = `${doc.title}.pdf`;
      const abs = new URL(url, window.location.href);
      if (abs.origin === window.location.origin) {
        // The library's own blob route: let the browser stream the file
        // straight to disk with its own progress, instead of buffering the
        // whole deck here first and only then handing it over.
        abs.searchParams.set('dl', '1');
        abs.searchParams.set('name', name);
        const a = document.createElement('a');
        a.href = abs.href;
        a.download = name;
        a.rel = 'noopener';
        document.body.appendChild(a);
        a.click();
        a.remove();
        setDlNote('เริ่มดาวน์โหลดแล้ว ไฟล์จะอยู่ในรายการดาวน์โหลดของเบราว์เซอร์');
        setTimeout(() => setDlNote((cur) => (cur.startsWith('เริ่มดาวน์โหลด') ? '' : cur)), 6000);
      } else {
        const res = await fetch(url);
        if (!res.ok) throw new Error(`ดาวน์โหลดไม่สำเร็จ (${res.status})`);
        saveBlob(await res.blob(), name);
      }
      recordRecentDoc(doc);
    } catch (err) {
      // The library's own messages are Thai (offline, no access); anything
      // else (a parser, a network stack) is not for the student to read.
      const msg = String(err?.message || '');
      setDlNote(/[฀-๿]/.test(msg) ? msg : 'ดาวน์โหลดไม่สำเร็จ ลองอีกครั้ง');
    } finally {
      setDlSlug(null);
    }
  };

  if (!set || typeof onStart !== 'function') return null;

  const labelOf = (topicId) => topics.find((t) => t.id === topicId)?.label || topicId;
  const kindTable = Q_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE[selectedPhase]?.[subject] || {};
  // `_matchCovers` marks a matching set filed under another topic whose bank
  // names this one. A deck cover counts it (the set does include that
  // disease); the lecturer's whole-part button does not, or one set spanning
  // five decks would be counted five times.
  const countOf = (topicIds, kind, { covers = false } = {}) => topicIds.reduce((sum, id) => {
    const row = kindTable[id] || {};
    if (kind === 'all') return sum + Object.entries(row).reduce((a, [k, v]) => (k.startsWith('_') ? a : a + v), 0);
    return sum + (row[kind] || 0) + (covers && kind === 'match' ? (row._matchCovers || 0) : 0);
  }, 0);
  const covers = LECTURE_COVERS[subject] || {};
  // The pool category for a format: ปรนัย must exclude tf and match, which
  // the plain 'mcq' category lumps in (see buildExamPool).
  const categoryOf = (format) => (format === 'mcq' ? 'mcq-only' : format);
  // Past papers only, for the third button. Counts sum the lecturer's own
  // topics; the pool would also admit a set filed under another topic that
  // names one of these diseases, but such a set's home topic is the same
  // lecturer's today, so the number and the session agree.
  const pastTable = Q_PAST_PAPER_COUNTS_BY_TOPIC_BY_KIND_BY_SCOPE[selectedPhase]?.[subject] || {};
  const pastCountOf = (topicIds, kind) => topicIds.reduce((sum, id) => sum + ((pastTable[id] || {})[kind] || 0), 0);

  return (
    <div className="vmx-lect-list">
      <p className="vmx-lect-intro">
        กลางภาค {thaiDate(set.examDate)} — {set.coverage} แยกตามอาจารย์ผู้สอนและรูปแบบข้อสอบที่แต่ละท่านใช้
      </p>
      {/* One switch for every format: instantFeedback is what choice and
          true/false read (ExamView revealAnswer), the stored reveal timing is
          what matching rows and written answers read. Set together so
          "เฉลยทีละข้อ" means the same thing on every button below. */}
      {setInstantFeedback && (
        <div className="vmx-lect-reveal" role="group" aria-label="เวลาที่แสดงเฉลยเมื่อฝึกตามอาจารย์">
          <RevealTimingToggle
            mode={instantFeedback ? REVEAL_ROW : REVEAL_END}
            onChange={(m) => { setInstantFeedback(m === REVEAL_ROW); writeRevealTiming(m); }}
          />
          <span className="vmx-lect-reveal-hint">
            {instantFeedback
              ? 'ตอบแล้วเห็นเฉลยทีละข้อ ทั้งกากบาท ถูกผิด และจับคู่ ส่วนข้อเขียนกดดูเฉลยได้ทันที'
              : 'เห็นเฉลยทั้งชุดหลังส่งคำตอบ เหมือนทำข้อสอบจริง'}
          </span>
        </div>
      )}
      {set.lecturers.map((lec) => {
        const all = lecturerTopics(lec);
        const inFormat = countOf(all, lec.format);
        const inAny = countOf(all, 'all');
        const pastInFormat = pastCountOf(all, lec.format);
        const formatLabel = FORMAT_LABEL[lec.format] || lec.format;
        // A matching question is a whole printed set (one answer list, the
        // items down the page), so it is counted in ชุด, not ข้อ.
        const unit = lec.format === 'match' ? 'ชุด' : 'ข้อ';
        const wholeCategory = inFormat > 0 ? categoryOf(lec.format) : 'all';
        const wholeCount = inFormat > 0 ? inFormat : inAny;
        const wholeLabel = inFormat > 0
          ? `ฝึกแบบ${formatLabel}ทุกหัวข้อของอาจารย์ (${wholeCount} ${unit})`
          : `ยังไม่มีข้อแบบ${formatLabel} ฝึกรวมทุกประเภท (${wholeCount} ข้อ)`;
        // Two lecturers on one card: one profile button per name.
        const people = Array.isArray(lec.lecturers) && lec.lecturers.length ? lec.lecturers : [lec.lecturer];
        const names = people.length > 1 ? lec.name.split(' และ ') : [lec.name];
        return (
          <article key={lec.id} className="vmx-lect" aria-label={lec.name}>
            <header className="vmx-lect-head">
              {names.map((nm, i) => (
                <Fragment key={nm}>
                  {i > 0 && <span className="vmx-lect-and">และ</span>}
                  <button
                    type="button"
                    className="vmx-lect-name"
                    onClick={() => onOpenInstructor?.(people[i] || people[0])}
                    title="ดูโปรไฟล์อาจารย์"
                  >
                    {nm}
                  </button>
                </Fragment>
              ))}
              <span className={`vmx-lect-chip${lec.announced ? '' : ' is-unannounced'}`}>
                {formatLabel}{lec.count ? ` ${lec.count} ข้อ` : ''}
              </span>
              <span className="vmx-lect-note">{lec.note}</span>
            </header>

            <div className="vmx-lect-strip" role="list" aria-label={`สไลด์ที่ ${lec.name} สอน`}>
              {lec.sessions.map((s) => s.decks.map((deck) => {
                const art = covers[deck.cover];
                const title = deck.title || labelOf(deck.topics[0]);
                const n = countOf(deck.topics, lec.format, { covers: true });
                const nAll = countOf(deck.topics, 'all');
                const usable = n > 0 ? categoryOf(lec.format) : 'all';
                const shown = n > 0 ? n : nAll;
                const countText = n > 0
                  ? `${formatLabel} ${n} ${unit}`
                  : (nAll > 0 ? `ยังไม่มีข้อแบบ${formatLabel} (รวม ${nAll} ข้อ)` : 'ยังไม่มีข้อสอบ');
                const doc = deck.doc && docsBySlug ? docsBySlug.get(deck.doc) : null;
                return (
                  <div key={`${s.n}-${deck.cover}`} role="listitem" className="vmx-lect-cover">
                    <button
                      type="button"
                      className="vmx-lect-cover-hit"
                      disabled={shown === 0}
                      aria-label={`${title} คาบ ${s.n} ${thaiDate(s.date)}, ${countText}`}
                      onClick={() => onStart({ subjectId: subject, topics: deck.topics, questionCategory: usable })}
                    >
                      {art ? <img src={art.src} alt={art.alt} loading="lazy" decoding="async" /> : <span className="vmx-lect-cover-blank" aria-hidden="true" />}
                      <span className="t">{title}</span>
                      <span className="c">{countText}</span>
                    </button>
                    <div className="vmx-lect-cover-foot">
                      <span className="s">คาบ {s.n} ({thaiDate(s.date)})</span>
                      {doc && (
                        <span className="vmx-lect-doc-set">
                          <button type="button" className="vmx-lect-doc" title={doc.title} aria-label={`เปิดสไลด์ ${title}`} onClick={() => openDeckDoc(doc)}>
                            สไลด์ PDF
                          </button>
                          <button
                            type="button"
                            className={`vmx-lect-doc is-icon${dlSlug === doc.slug ? ' is-busy' : ''}`}
                            title="ดาวน์โหลดไฟล์ PDF"
                            aria-label={`ดาวน์โหลดสไลด์ ${title}`}
                            disabled={dlSlug === doc.slug}
                            onClick={() => downloadDeck(doc)}
                          >
                            <DownloadGlyph />
                          </button>
                        </span>
                      )}
                    </div>
                  </div>
                );
              }))}
            </div>

            {dlNote && <p className="vmx-lect-dl-note" role="status">{dlNote}</p>}

            <div className="vmx-lect-actions">
              <button
                type="button"
                className="vmx-lect-btn is-primary"
                disabled={wholeCount === 0}
                onClick={() => onStart({ subjectId: subject, topics: all, questionCategory: wholeCategory })}
              >
                {wholeLabel}
              </button>
              {/* A part written in one format but practised in another as
                  well (the previous cohort's true/false for a written part). */}
              {(lec.alsoFormats || []).map((fmt) => {
                const n = countOf(all, fmt);
                if (!n) return null;
                return (
                  <button
                    key={fmt}
                    type="button"
                    className="vmx-lect-btn"
                    onClick={() => onStart({ subjectId: subject, topics: all, questionCategory: categoryOf(fmt) })}
                  >
                    ฝึกแบบ{FORMAT_LABEL[fmt] || fmt}ทุกหัวข้อของอาจารย์ ({n} {fmt === 'match' ? 'ชุด' : 'ข้อ'})
                  </button>
                );
              })}
              {lec.count && inFormat >= lec.count && (
                <button
                  type="button"
                  className="vmx-lect-btn"
                  onClick={() => onStart({ subjectId: subject, topics: all, questionCategory: categoryOf(lec.format), numQuestions: lec.count })}
                >
                  จำลองชุด {lec.count} ข้อ
                </button>
              )}
              {pastInFormat > 0 && (
                <button
                  type="button"
                  className="vmx-lect-btn"
                  onClick={() => onStart({ subjectId: subject, topics: all, questionCategory: categoryOf(lec.format), pastPaperOnly: true })}
                >
                  ฝึกเฉพาะข้อสอบเก่า ({pastInFormat} {unit})
                </button>
              )}
            </div>
          </article>
        );
      })}
    </div>
  );
}
