// ============================================================
// SlideFigures — the real images from the lecture deck, per section
// ============================================================
// One renderer for every surface that shows a note-derived section
// (NotesView, the VetWiki article page). The map is generated by
// scripts/extract-slide-figures.mjs, keyed by the SAME stable section id
// both surfaces already use — so a subject whose figures get extracted
// lights up everywhere at once, and the two surfaces cannot drift apart.
//
// A histology note describing a stain is worth much less than the stain;
// a neuroanatomy section about the midbrain is worth much less than the
// midbrain.
//
// The id→paths map is ~250 KB of strings, and most articles have no
// figures yet — so it loads as its own on-demand chunk, once, instead of
// riding inside every article's JavaScript.

import { useEffect, useState } from 'react';

let _mapPromise = null;
function loadMap() {
  if (!_mapPromise) _mapPromise = import('../data/slide-images.generated.js');
  return _mapPromise;
}

export default function SlideFigures({ sectionId, source = '' }) {
  const [slides, setSlides] = useState(null);
  useEffect(() => {
    if (!sectionId) return undefined;
    let alive = true;
    loadMap().then((m) => { if (alive) setSlides(m.slidesFor(sectionId)); }).catch(() => {});
    return () => { alive = false; };
  }, [sectionId]);

  if (!slides || slides.length === 0) return null;
  return (
    <div style={{ marginTop: 14, display: 'grid', gap: 10 }}>
      {slides.map((src) => (
        <figure key={src} style={{ margin: 0 }}>
          <img
            src={src}
            alt={`ภาพจากสไลด์ ${source || ''}`}
            loading="lazy"
            decoding="async"
            style={{ display: 'block', width: '100%', borderRadius: 8, border: '1px solid var(--clr-border)', background: 'var(--clr-surface)' }}
          />
          {/* The file is already served as a plain image, so saving it costs
              nothing extra to host — this only spares the reader a
              right-click. */}
          <figcaption style={{ marginTop: 4, fontSize: 11, fontFamily: 'var(--vmx-mono)', color: 'var(--clr-ink-soft)' }}>
            <a href={src} download style={{ color: 'inherit' }}>⬇ บันทึกภาพ</a>
          </figcaption>
        </figure>
      ))}
    </div>
  );
}
