#!/usr/bin/env node
// ============================================================
// scripts/stats.mjs — the authoritative content inventory
// ============================================================
// One command that MEASURES the repo instead of trusting any hand-written
// number. Every stat here is counted from the source files at run time.
//
//   npm run stats           print to stdout
//   npm run stats -- --write  regenerate docs/content-inventory.md
//
// Why this exists: the project's numbers had drifted across notes, vault
// entries and docs (1700+ / 2650 / 2956 / 2948 all appear somewhere for the
// same thing). A generated inventory can't go stale — if you want the number,
// you run the command.
// ============================================================

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'src', 'data');
const WRITE = process.argv.includes('--write');

const ls = (re) => fs.readdirSync(DATA).filter((f) => re.test(f)).sort();
const imp = (f) => import(new URL(`../src/data/${f}`, import.meta.url).href);

// ---- questions -----------------------------------------------------------
const qFiles = ls(/^questions-.*\.js$/);
let qTotal = 0;
const qByFile = [];
for (const f of qFiles) {
  const m = await imp(f);
  const arrays = Object.entries(m).filter(([, v]) => Array.isArray(v));
  const pick = arrays.sort((a, b) => b[1].length - a[1].length)[0];
  const n = pick ? pick[1].length : 0;
  qTotal += n;
  qByFile.push({ file: f, count: n });
}

const qc = await imp('q-counts.js');
const reg = await imp('bank-registry.generated.js');
const registryTotal = reg.BANK_REGISTRY.reduce((n, b) => n + b.count, 0);
const notInRegistry = qFiles.filter((f) => !reg.BANK_REGISTRY.some((b) => b.file === f));

// ---- notes ---------------------------------------------------------------
const nFiles = ls(/^notes-.*\.js$/);
let noteTopics = 0; let noteSections = 0; let noteSourced = 0;
for (const f of nFiles) {
  const m = await imp(f);
  for (const v of Object.values(m)) {
    if (!v || typeof v !== 'object') continue;
    for (const topic of Object.values(v)) {
      if (!topic || !Array.isArray(topic.sections)) continue;
      noteTopics += 1;
      noteSections += topic.sections.length;
      noteSourced += topic.sections.filter((s) => s.source).length;
    }
  }
}

// ---- video summaries -----------------------------------------------------
const vFiles = ls(/^video-summaries-.*\.js$/).filter((f) => !/meta/.test(f));
let videos = 0;
for (const f of vFiles) {
  const m = await imp(f);
  for (const v of Object.values(m)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) videos += Object.keys(v).length;
  }
}

// ---- curriculum ----------------------------------------------------------
const cur = await imp('curriculum.js');
const subjects = cur.SUBJECTS.length;
const curTopics = cur.SUBJECTS.reduce((n, s) => n + (s.topics?.length || 0), 0);
const years = [...new Set(Object.keys(qc.Q_COUNTS_BY_YEAR))].sort();

// ---- VetWiki -------------------------------------------------------------
const vw = await import(new URL('../src/lib/vetwiki/index.js', import.meta.url).href);
const govTopics = vw.listTopics();
let govSections = 0; let govVerified = 0; const govSources = new Set();
for (const t of govTopics) {
  const k = vw.loadTopic(t.subject, t.topic);
  govSections += k.sections.length;
  const p = vw.provenanceSummary(k);
  govVerified += p.verifiedClaimCount;
  for (const s of p.sources) govSources.add(s.id);
}

// ---- report --------------------------------------------------------------
const consistent = qTotal === qc.QB_TOTAL && qTotal === registryTotal && notInRegistry.length === 0;

const lines = [];
const L = (s = '') => lines.push(s);
L('# Content inventory');
L();
L('> AUTO-GENERATED by `npm run stats -- --write`. Do not hand-edit — every');
L('> number here is counted from the source files, so it cannot drift.');
L();
L(`Generated from the working tree at the time of the run.`);
L();
L('## Questions');
L();
L('| | |');
L('|---|---|');
L(`| **Total questions** | **${qTotal.toLocaleString()}** |`);
L(`| Question banks (files) | ${qFiles.length} |`);
L(`| Subjects with questions | ${Object.keys(qc.Q_COUNTS_BY_SUBJECT).length} |`);
L(`| Years covered | ${years.join(', ')} |`);
for (const [y, n] of Object.entries(qc.Q_COUNTS_BY_YEAR)) L(`| — year ${y} | ${n.toLocaleString()} |`);
L();
L(`Consistency: counted **${qTotal}**, \`q-counts.js\` says **${qc.QB_TOTAL}**, registry sums to **${registryTotal}**, files missing from the registry: **${notInRegistry.length}** → ${consistent ? '✅ consistent' : '❌ DRIFT'}`);
L();
L('## Study notes');
L();
L('| | |');
L('|---|---|');
L(`| Note files | ${nFiles.length} |`);
L(`| Topics | ${noteTopics} |`);
L(`| Sections | ${noteSections} |`);
L(`| Sections carrying a source locator | ${noteSourced} (${Math.round((noteSourced / noteSections) * 100)}%) |`);
L();
L('## Video summaries');
L();
L(`${videos} summarised videos across ${vFiles.length} files.`);
L();
L('## Curriculum');
L();
L(`${subjects} subjects, ${curTopics} topics in the taxonomy.`);
L();
L('## VetWiki (governed knowledge)');
L();
L('| | |');
L('|---|---|');
L(`| Governed topics | ${govTopics.length} |`);
L(`| Governed sections | ${govSections} |`);
L(`| Claims verified against an external source | ${govVerified} |`);
L(`| Distinct external sources cited | ${govSources.size} |`);
L(`| Share of note sections governed | ${((govSections / noteSections) * 100).toFixed(1)}% |`);
L();

const md = lines.join('\n');
if (WRITE) {
  const out = path.join(ROOT, 'docs', 'content-inventory.md');
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, md, 'utf8');
  console.log(`✓ wrote docs/content-inventory.md`);
}
console.log(md);
if (!consistent) {
  console.error('\n❌ content stats are INCONSISTENT — run `npm run regen:q-counts` and `npm run regen:registry`');
  process.exit(1);
}
