#!/usr/bin/env node
// ============================================================
// scripts/stats.mjs — the authoritative content inventory
// ============================================================
// One command that MEASURES the repo instead of trusting any hand-written
// number. Every stat here is counted from the source files at run time.
//
//   npm run stats           print to stdout
//   npm run stats -- --write  regenerate docs/content-inventory.md
//   npm run stats:check     fail if generated docs/README stats are stale
//
// Why this exists: the project's numbers had drifted across notes, vault
// entries and docs (1700+ / 2650 / 2956 / 2948 all appear somewhere for the
// same thing). The checked generated inventory is the durable source for
// documentation; `stats:check` prevents it silently drifting again.
// ============================================================

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'src', 'data');
const WRITE = process.argv.includes('--write');
const CHECK = process.argv.includes('--check');

if (WRITE && CHECK) throw new Error('Choose either --write or --check, not both.');

const INVENTORY_PATH = path.join(ROOT, 'docs', 'content-inventory.md');
const README_PATH = path.join(ROOT, 'README.md');
const README_STATS_START = '<!-- content-stats:start -->';
const README_STATS_END = '<!-- content-stats:end -->';

const ls = (re) => fs.readdirSync(DATA).filter((f) => re.test(f)).sort();
const imp = (f) => import(new URL(`../src/data/${f}`, import.meta.url).href);

// ---- questions -----------------------------------------------------------
const qFiles = ls(/^questions-.*\.js$/);
let qTotal = 0;
const qByFile = [];
for (const f of qFiles) {
  const m = await imp(f);
  const arrays = Object.entries(m).filter(([, v]) => Array.isArray(v));
  const pick = arrays.sort((a, b) => b[1].length - a[1].length)[0];
  const n = pick ? pick[1].length : 0;
  qTotal += n;
  qByFile.push({ file: f, count: n });
}

const qc = await imp('q-counts.js');
const reg = await imp('bank-registry.generated.js');
const registryTotal = reg.BANK_REGISTRY.reduce((n, b) => n + b.count, 0);
const notInRegistry = qFiles.filter((f) => !reg.BANK_REGISTRY.some((b) => b.file === f));

// ---- notes ---------------------------------------------------------------
const nFiles = ls(/^notes-.*\.js$/);
let noteTopics = 0; let noteSections = 0; let noteSourced = 0;
for (const f of nFiles) {
  const m = await imp(f);
  for (const v of Object.values(m)) {
    if (!v || typeof v !== 'object') continue;
    for (const topic of Object.values(v)) {
      if (!topic || !Array.isArray(topic.sections)) continue;
      noteTopics += 1;
      noteSections += topic.sections.length;
      noteSourced += topic.sections.filter((s) => s.source).length;
    }
  }
}

// ---- video summaries -----------------------------------------------------
const vFiles = ls(/^video-summaries-.*\.js$/).filter((f) => !/meta/.test(f));
let videos = 0;
for (const f of vFiles) {
  const m = await imp(f);
  for (const v of Object.values(m)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) videos += Object.keys(v).length;
  }
}

// ---- curriculum ----------------------------------------------------------
const cur = await imp('curriculum.js');
const subjects = cur.SUBJECTS.length;
const curTopics = cur.SUBJECTS.reduce((n, s) => n + (s.topics?.length || 0), 0);
const years = [...new Set(Object.keys(qc.Q_COUNTS_BY_YEAR))].sort();

// ---- VetWiki -------------------------------------------------------------
const vw = await import(new URL('../src/lib/vetwiki/index.js', import.meta.url).href);
const govTopics = vw.listTopics();
let govSections = 0; let govVerified = 0; const govSources = new Set();
for (const t of govTopics) {
  const k = vw.loadTopic(t.subject, t.topic);
  govSections += k.sections.length;
  const p = vw.provenanceSummary(k);
  govVerified += p.verifiedClaimCount;
  for (const s of p.sources) govSources.add(s.id);
}

// ---- report --------------------------------------------------------------
const deliverableTotal = qc.QB_TOTAL;
const blockedTotal = qc.QB_BLOCKED_TOTAL || 0;
const consistent = qTotal === qc.QB_SOURCE_TOTAL
  && qTotal === registryTotal
  && deliverableTotal + blockedTotal === qTotal
  && notInRegistry.length === 0;
const fmt = (n) => n.toLocaleString('en-US');
const sourcedPercent = noteSections ? Math.round((noteSourced / noteSections) * 100) : 0;
const governedPercent = noteSections ? ((govSections / noteSections) * 100).toFixed(1) : '0.0';

const lines = [];
const L = (s = '') => lines.push(s);
L('# Content inventory');
L();
L('> AUTO-GENERATED by `npm run stats -- --write`. Do not hand-edit — every');
L('> number here is counted from the source files, so it cannot drift.');
L();
L(`Generated from the working tree at the time of the run.`);
L();
L('## Questions');
L();
L('| | |');
L('|---|---|');
L(`| **Questions ready for learners** | **${fmt(deliverableTotal)}** |`);
L(`| Questions retained but fail-closed pending a verified figure | ${fmt(blockedTotal)} |`);
L(`| Total questions in source banks | ${fmt(qTotal)} |`);
L(`| Question banks (files) | ${qFiles.length} |`);
L(`| Subjects with questions | ${Object.keys(qc.Q_COUNTS_BY_SUBJECT).length} |`);
L(`| Years covered | ${years.join(', ')} |`);
for (const [y, n] of Object.entries(qc.Q_COUNTS_BY_YEAR)) L(`| — year ${y} | ${fmt(n)} |`);
L();
L(`Consistency: source banks **${qTotal}**, learner-ready **${deliverableTotal}**, fail-closed **${blockedTotal}**, registry sums to **${registryTotal}**, files missing from the registry: **${notInRegistry.length}** → ${consistent ? '✅ consistent' : '❌ DRIFT'}`);
L();
L('## Study notes');
L();
L('| | |');
L('|---|---|');
L(`| Note files | ${nFiles.length} |`);
L(`| Topics | ${noteTopics} |`);
L(`| Sections | ${noteSections} |`);
L(`| Sections carrying a source locator | ${noteSourced} (${sourcedPercent}%) |`);
L();
L('## Video summaries');
L();
L(`${videos} summarised videos across ${vFiles.length} files.`);
L();
L('## Curriculum');
L();
L(`${subjects} subjects, ${curTopics} topics in the taxonomy.`);
L();
L('## VetWiki (governed knowledge)');
L();
L('| | |');
L('|---|---|');
L(`| Governed topics | ${govTopics.length} |`);
L(`| Governed sections | ${govSections} |`);
L(`| Claims verified against an external source | ${govVerified} |`);
L(`| Distinct external sources cited | ${govSources.size} |`);
L(`| Share of note sections governed | ${governedPercent}% |`);
L();

const md = lines.join('\n');
const yearSummary = Object.entries(qc.Q_COUNTS_BY_YEAR)
  .map(([year, count]) => `ปี ${year} (${fmt(count)})`)
  .join(', ');
const readmeStats = [
  README_STATS_START,
  '| | |',
  '|---|---|',
  `| ข้อสอบพร้อมฝึก | **${fmt(deliverableTotal)} ข้อ** ใน ${qFiles.length} bank files, ${Object.keys(qc.Q_COUNTS_BY_SUBJECT).length} วิชา |`,
  `| พักไว้เพื่อความถูกต้อง | ${fmt(blockedTotal)} ข้อรอภาพที่ตรวจสอบแล้ว (เก็บใน source bank แต่ไม่ส่งให้ผู้เรียน) |`,
  `| ชั้นปีที่มีเนื้อหา | ${yearSummary} |`,
  `| สรุปโน้ต | ${nFiles.length} ไฟล์, ${fmt(noteTopics)} หัวข้อ, ${fmt(noteSections)} sections, อ้างอิงแหล่งที่มาครบ ${sourcedPercent}% |`,
  `| สรุปคลิป | ${fmt(videos)} คลิป ใน ${vFiles.length} ไฟล์ |`,
  `| VetWiki (governed) | ${fmt(govTopics.length)} หัวข้อ, ${fmt(govSections)} sections = ${governedPercent}% ของ note sections |`,
  `| Taxonomy | ${fmt(subjects)} วิชา, ${fmt(curTopics)} หัวข้อ |`,
  '| ชนิดคำถาม | MCQ, True/False, Fill-in, Matching, Short answer, Writing |',
  README_STATS_END,
].join('\n');
const normalizeEol = (source) => source.replace(/\r\n/g, '\n');

function replaceReadmeStats(source) {
  const start = source.indexOf(README_STATS_START);
  const end = source.indexOf(README_STATS_END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error('README generated stats markers are missing or out of order.');
  }
  const eol = source.includes('\r\n') ? '\r\n' : '\n';
  const renderedStats = readmeStats.replace(/\n/g, eol);
  return source.slice(0, start) + renderedStats + source.slice(end + README_STATS_END.length);
}

let generatedDrift = false;
if (WRITE) {
  fs.mkdirSync(path.dirname(INVENTORY_PATH), { recursive: true });
  fs.writeFileSync(INVENTORY_PATH, md, 'utf8');
  const readme = fs.readFileSync(README_PATH, 'utf8');
  fs.writeFileSync(README_PATH, replaceReadmeStats(readme), 'utf8');
  console.log('✓ wrote docs/content-inventory.md and README stats block');
}
if (CHECK) {
  const inventoryCurrent = fs.existsSync(INVENTORY_PATH)
    ? fs.readFileSync(INVENTORY_PATH, 'utf8')
    : '';
  const readmeCurrent = fs.readFileSync(README_PATH, 'utf8');
  const expectedReadme = replaceReadmeStats(readmeCurrent);
  const stale = [];
  if (normalizeEol(inventoryCurrent) !== md) stale.push('docs/content-inventory.md');
  if (readmeCurrent !== expectedReadme) stale.push('README.md stats block');
  if (stale.length) {
    generatedDrift = true;
    console.error(`\n❌ generated stats are stale: ${stale.join(', ')}`);
    console.error('   run: npm run stats -- --write');
  } else {
    console.log('\n✓ generated stats are current');
  }
}
console.log(md);
if (!consistent) {
  console.error('\n❌ content stats are INCONSISTENT — run `npm run regen:q-counts` and `npm run regen:registry`');
}
if (!consistent || generatedDrift) process.exit(1);
