// ============================================================
// VetWiki — external source registry
// ============================================================
// Stable, real, verifiable veterinary sources that VetWiki claims cite.
//
// ⛔ IRON RULE 0: every entry here is a REAL source. Do NOT add a source,
// author, journal, volume, page, DOI, or URL that has not been verified.
// `availability`:
//   'verified-online'  = the citation (and URL where present) was confirmed
//                        against the live source during authoring.
//   'named'            = a real, well-known reference we name for attribution
//                        but do NOT link/quote a specific passage from (so we
//                        never fabricate a locator we haven't checked).
// A missing URL is honest — better no link than a guessed one.
// ============================================================

/** @typedef {import('./schema.js').SourceRef} SourceRef */

/**
 * @typedef {Object} Source
 * @property {string} id
 * @property {string} title
 * @property {string} organization
 * @property {'guideline'|'textbook'|'primary-literature'|'lecture-note'} kind
 * @property {number} [year]
 * @property {string} [edition]
 * @property {string} [citation]     human-readable full citation
 * @property {string} [url]          ONLY when verified
 * @property {'verified-online'|'named'} availability
 */

/** @type {Record<string, Source>} */
export const SOURCES = {
  'woah-tahm-rabies': {
    id: 'woah-tahm-rabies',
    title: 'Manual of Diagnostic Tests and Vaccines for Terrestrial Animals — Chapter 3.1.18 Rabies (Infection with rabies virus and other lyssaviruses)',
    organization: 'WOAH (World Organisation for Animal Health)',
    kind: 'guideline',
    year: 2023,
    citation: 'WOAH. Terrestrial Manual, Chapter 3.1.18 — Rabies. 2023.',
    url: 'https://www.woah.org/fileadmin/Home/eng/Health_standards/tahm/3.01.18_RABIES.pdf',
    availability: 'verified-online',
  },
  'tepsumethanon-2005': {
    id: 'tepsumethanon-2005',
    title: 'Six criteria for rabies diagnosis in living dogs',
    organization: 'Journal of the Medical Association of Thailand',
    kind: 'primary-literature',
    year: 2005,
    citation: 'Tepsumethanon V, Wilde H, Meslin FX. Six criteria for rabies diagnosis in living dogs. J Med Assoc Thai. 2005;88(3):419-22.',
    availability: 'verified-online', // citation + sens 90.2% / spec 96.2% confirmed
  },
  'wsava-2024': {
    id: 'wsava-2024',
    title: '2024 guidelines for the vaccination of dogs and cats — compiled by the Vaccination Guidelines Group (VGG) of the WSAVA',
    organization: 'WSAVA · Journal of Small Animal Practice',
    kind: 'guideline',
    year: 2024,
    citation: 'Squires RA, Crawford C, Marcondes M, Whitley N. 2024 guidelines for the vaccination of dogs and cats (WSAVA VGG). J Small Anim Pract. 2024;65(5):277-316. doi:10.1111/jsap.13718',
    url: 'https://wsava.org/wp-content/uploads/2024/04/WSAVA-Vaccination-guidelines-2024.pdf',
    availability: 'verified-online', // journal/volume/pages + DOI + official PDF confirmed
  },
  'greene-iddc': {
    id: 'greene-iddc',
    title: 'Infectious Diseases of the Dog and Cat',
    organization: 'Elsevier (Greene / Sykes eds.)',
    kind: 'textbook',
    citation: "Greene CE / Sykes JE (eds.). Infectious Diseases of the Dog and Cat. Elsevier.",
    availability: 'named', // real standard reference; no specific page asserted
  },
  'msd-household-poisons': {
    id: 'msd-household-poisons',
    title: 'Common Household Poisons (Household Hazards for Pet Birds)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Household Poisons. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-household-poisons',
    availability: 'verified-online',
  },
  'msd-popular-pet-birds': {
    id: 'msd-popular-pet-birds',
    title: 'Popular Pet Birds (Species, Lifespan & Clinical Considerations)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Popular Pet Birds. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/popular-pet-birds',
    availability: 'verified-online',
  },
  'msd-behavior-drugs-dog': {
    id: 'msd-behavior-drugs-dog',
    title: 'Common Drugs Used to Treat Behavior Problems in Dogs',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Drugs Used to Treat Behavior Problems in Dogs. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-drugs-used-to-treat-behavior-problems-in-dogs',
    availability: 'verified-online',
  },
  'msd-cat-urine-marking': {
    id: 'msd-cat-urine-marking',
    title: 'Distinguishing Urine Marking From Undesirable Toileting in Cats',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Distinguishing Urine Marking From Undesirable Toileting in Cats. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/distinguishing-urine-marking-from-undesirable-toileting-in-cats',
    availability: 'verified-online',
  },
  'msd-controlled-exposure-dog': {
    id: 'msd-controlled-exposure-dog',
    title: 'General Guidelines for Effective Controlled Exposure Behavior Modification in Dogs',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. General Guidelines for Effective Controlled Exposure Behavior Modification in Dogs. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/general-guidelines-for-effective-controlled-exposure-behavior-modification-in-dogs',
    availability: 'verified-online',
  },
  'msd-medical-behavior-causes': {
    id: 'msd-medical-behavior-causes',
    title: 'Medical Causes of Behavioral Signs',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Medical Causes of Behavioral Signs. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/medical-causes-of-behavioral-signs',
    availability: 'verified-online',
  },
  'msd-reptile-lifespan': {
    id: 'msd-reptile-lifespan',
    title: 'Average Life Span of Reptiles in Captivity',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Average Life Span of Reptiles in Captivity. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/average-life-span-of-reptiles-in-captivity',
    availability: 'verified-online',
  },
  'msd-biting-behavior': {
    id: 'msd-biting-behavior',
    title: 'Biting in Small Animals and Pets',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Biting. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/biting',
    availability: 'verified-online',
  },
  'msd-rabbit-breeds': {
    id: 'msd-rabbit-breeds',
    title: 'Breeds of Rabbits',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Breeds of Rabbits. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/breeds-of-rabbits',
    availability: 'verified-online',
  },
  'msd-buying-first-rabbit': {
    id: 'msd-buying-first-rabbit',
    title: 'Buying Your First Rabbit (Physical Exam Checklist)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Buying Your First Rabbit. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/buying-your-first-rabbit',
    availability: 'verified-online',
  },
  'msd-mice-illness-signs': {
    id: 'msd-mice-illness-signs',
    title: 'Checking for Signs of Illness in Mice',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Checking for Signs of Illness in Mice. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/checking-for-signs-of-illness-in-mice',
    availability: 'verified-online',
  },
  'msd-chinchilla-care-checklist': {
    id: 'msd-chinchilla-care-checklist',
    title: 'Chinchilla Care Checklist',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Chinchilla Care Checklist. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/chinchilla-care-checklist',
    availability: 'verified-online',
  },
  'msd-fish-illness-signs': {
    id: 'msd-fish-illness-signs',
    title: 'Common Signs of Illness in Fish',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Signs of Illness in Fish. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-signs-of-illness-in-fish',
    availability: 'verified-online',
  },
  'msd-rats-illness-signs': {
    id: 'msd-rats-illness-signs',
    title: 'Common Signs of Illness in Rats',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Signs of Illness in Rats. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-signs-of-illness-in-rats',
    availability: 'verified-online',
  },
  'msd-ferret-zoonoses': {
    id: 'msd-ferret-zoonoses',
    title: 'Diseases Spread from Ferrets to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Ferrets to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-ferrets-to-people',
    availability: 'verified-online',
  },
  'msd-gerbil-zoonoses': {
    id: 'msd-gerbil-zoonoses',
    title: 'Diseases Spread from Gerbils to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Gerbils to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-gerbils-to-people',
    availability: 'verified-online',
  },
  'msd-hamster-zoonoses': {
    id: 'msd-hamster-zoonoses',
    title: 'Diseases Spread from Hamsters to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Hamsters to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-hamsters-to-people',
    availability: 'verified-online',
  },
  'msd-mice-zoonoses': {
    id: 'msd-mice-zoonoses',
    title: 'Diseases Spread from Mice to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Mice to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-mice-to-people',
    availability: 'verified-online',
  },
  'msd-pig-zoonoses': {
    id: 'msd-pig-zoonoses',
    title: 'Diseases Spread from Potbellied Pigs to Humans',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Potbellied Pigs to Humans. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-potbellied-pigs-to-humans',
    availability: 'verified-online',
  },
  'msd-rabbit-zoonoses': {
    id: 'msd-rabbit-zoonoses',
    title: 'Diseases Spread from Rabbits to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Rabbits to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-rabbits-to-people',
    availability: 'verified-online',
  },
  'msd-rat-zoonoses': {
    id: 'msd-rat-zoonoses',
    title: 'Diseases Spread from Rats to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Rats to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-rats-to-people',
    availability: 'verified-online',
  },
  'msd-reptile-zoonoses': {
    id: 'msd-reptile-zoonoses',
    title: 'Diseases Spread from Reptiles to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Reptiles to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-reptiles-to-people',
    availability: 'verified-online',
  },
  'msd-gerbil-illness-warning': {
    id: 'msd-gerbil-illness-warning',
    title: 'Early Warning Signs of Illness in Your Gerbil',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Early Warning Signs of Illness in Your Gerbil. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/early-warning-signs-of-illness-in-your-gerbil',
    availability: 'verified-online',
  },
  'msd-exotic-emergencies': {
    id: 'msd-exotic-emergencies',
    title: 'Emergencies in Exotic Pets and Small Animals',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Emergencies. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/emergencies',
    availability: 'verified-online',
  },
  'msd-safe-environment': {
    id: 'msd-safe-environment',
    title: 'Ensuring a Safe Environment for Small Animals',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Ensuring a Safe Environment. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/ensuring-a-safe-environment',
    availability: 'verified-online',
  },
  'msd-aquarium-maintenance': {
    id: 'msd-aquarium-maintenance',
    title: 'Essential Maintenance for Aquariums',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Essential Maintenance. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/essential-maintenance',
    availability: 'verified-online',
  },
  'msd-explaining-ph': {
    id: 'msd-explaining-ph',
    title: 'Explaining pH and Water Chemistry in Aquariums',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Explaining pH. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/explaining-ph',
    availability: 'verified-online',
  },
  'msd-feeding-sick-ferret': {
    id: 'msd-feeding-sick-ferret',
    title: 'Feeding a Sick Ferret (Nutritional Support Protocol)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Feeding a Sick Ferret. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/feeding-a-sick-ferret',
    availability: 'verified-online',
  },
  'msd-ferrets-glance': {
    id: 'msd-ferrets-glance',
    title: 'Ferrets at a Glance (Physiological & Reproductive Constants)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Ferrets at a Glance. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/ferrets-at-a-glance',
    availability: 'verified-online',
  },
  'msd-hamster-breeds': {
    id: 'msd-hamster-breeds',
    title: 'Hamster Breeds Commonly Kept as Pets',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Hamster Breeds Commonly Kept as Pets. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/hamster-breeds-commonly-kept-as-pets',
    availability: 'verified-online',
  },
  'msd-hamster-pregnancy': {
    id: 'msd-hamster-pregnancy',
    title: 'If Your Hamster is Pregnant (Reproductive & Maternal Care)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. If Your Hamster is Pregnant. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/if-your-hamster-is-pregnant',
    availability: 'verified-online',
  },
  'msd-amphibian-diseases': {
    id: 'msd-amphibian-diseases',
    title: 'Infectious Diseases of Amphibians',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Infectious Diseases of Amphibians. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/infectious-diseases-of-amphibians',
    availability: 'verified-online',
  },
  'msd-mice-glance': {
    id: 'msd-mice-glance',
    title: 'Mice at a Glance (Physiological & Reproductive Constants)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Mice at a Glance. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/mice-at-a-glance',
    availability: 'verified-online',
  },
  'msd-rabbit-nutrition': {
    id: 'msd-rabbit-nutrition',
    title: 'Nutrient Requirements of Rabbits',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Nutrient Requirements of Rabbits. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/nutrient-requirements-of-rabbits',
    availability: 'verified-online',
  },
};

/** Resolve a SourceRef to its Source record (or null if it points at a
 *  lecture-note locator rather than an external source). */
export function resolveSource(ref) {
  if (!ref) return null;
  return SOURCES[ref.sourceId] || null;
}

export const ALL_SOURCE_IDS = Object.keys(SOURCES);
