// ============================================================
// VetWiki — external source registry
// ============================================================
// Stable, real, verifiable veterinary sources that VetWiki claims cite.
//
// ⛔ IRON RULE 0: every entry here is a REAL source. Do NOT add a source,
// author, journal, volume, page, DOI, or URL that has not been verified.
// `availability`:
//   'verified-online'  = the citation (and URL where present) was confirmed
//                        against the live source during authoring.
//   'named'            = a real, well-known reference we name for attribution
//                        but do NOT link/quote a specific passage from (so we
//                        never fabricate a locator we haven't checked).
// A missing URL is honest — better no link than a guessed one.
// ============================================================

/** @typedef {import('./schema.js').SourceRef} SourceRef */

/**
 * @typedef {Object} Source
 * @property {string} id
 * @property {string} title
 * @property {string} organization
 * @property {'guideline'|'textbook'|'primary-literature'|'lecture-note'} kind
 * @property {number} [year]
 * @property {string} [edition]
 * @property {string} [citation]     human-readable full citation
 * @property {string} [url]          ONLY when verified
 * @property {string} [pmid]         PubMed id — resolved live by verify:sources
 * @property {string} [doi]          DOI — resolved live against Crossref by verify:sources
 * @property {'verified-online'|'named'} availability
 */
//
// Prefer a `pmid` or `doi` over a bare `url`. An identifier can be resolved
// against a registry and compared with the title we registered, so
// `npm run verify:sources` can PROVE the source is the work we say it is. A
// url can only be checked for reachability, and many publishers block bots.

/** @type {Record<string, Source>} */
export const SOURCES = {
  'woah-tahm-rabies': {
    id: 'woah-tahm-rabies',
    title: 'Manual of Diagnostic Tests and Vaccines for Terrestrial Animals — Chapter 3.1.18 Rabies (Infection with rabies virus and other lyssaviruses)',
    organization: 'WOAH (World Organisation for Animal Health)',
    kind: 'guideline',
    year: 2023,
    citation: 'WOAH. Terrestrial Manual, Chapter 3.1.18 — Rabies. 2023.',
    url: 'https://www.woah.org/fileadmin/Home/eng/Health_standards/tahm/3.01.18_RABIES.pdf',
    availability: 'verified-online',
  },
  'tepsumethanon-2005': {
    id: 'tepsumethanon-2005',
    title: 'Six criteria for rabies diagnosis in living dogs',
    organization: 'Journal of the Medical Association of Thailand',
    kind: 'primary-literature',
    year: 2005,
    citation: 'Tepsumethanon V, Wilde H, Meslin FX. Six criteria for rabies diagnosis in living dogs. J Med Assoc Thai. 2005;88(3):419-22.',
    pmid: '15962654',
    url: 'https://pubmed.ncbi.nlm.nih.gov/15962654/',
    availability: 'verified-online', // PubMed abstract states 90.2% sens / 96.2% spec / 94.6% accuracy
  },
  'wsava-2024': {
    id: 'wsava-2024',
    title: '2024 guidelines for the vaccination of dogs and cats — compiled by the Vaccination Guidelines Group (VGG) of the WSAVA',
    organization: 'WSAVA, Journal of Small Animal Practice',
    kind: 'guideline',
    year: 2024,
    citation: 'Squires RA, Crawford C, Marcondes M, Whitley N. 2024 guidelines for the vaccination of dogs and cats (WSAVA VGG). J Small Anim Pract. 2024;65(5):277-316. doi:10.1111/jsap.13718',
    url: 'https://wsava.org/wp-content/uploads/2024/04/WSAVA-Vaccination-guidelines-2024.pdf',
    availability: 'verified-online', // journal/volume/pages + DOI + official PDF confirmed
  },
  'greene-iddc': {
    id: 'greene-iddc',
    title: 'Infectious Diseases of the Dog and Cat',
    organization: 'Elsevier (Greene / Sykes eds.)',
    kind: 'textbook',
    citation: "Greene CE / Sykes JE (eds.). Infectious Diseases of the Dog and Cat. Elsevier.",
    availability: 'named', // real standard reference; no specific page asserted
  },
  'msd-household-poisons': {
    id: 'msd-household-poisons',
    title: 'Common Household Poisons (Household Hazards for Pet Birds)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Household Poisons. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-household-poisons',
    availability: 'verified-online',
  },
  'msd-popular-pet-birds': {
    id: 'msd-popular-pet-birds',
    title: 'Popular Pet Birds (Species, Lifespan & Clinical Considerations)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Popular Pet Birds. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/popular-pet-birds',
    availability: 'verified-online',
  },
  'msd-behavior-drugs-dog': {
    id: 'msd-behavior-drugs-dog',
    title: 'Common Drugs Used to Treat Behavior Problems in Dogs',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Drugs Used to Treat Behavior Problems in Dogs. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-drugs-used-to-treat-behavior-problems-in-dogs',
    availability: 'verified-online',
  },
  'msd-cat-urine-marking': {
    id: 'msd-cat-urine-marking',
    title: 'Distinguishing Urine Marking From Undesirable Toileting in Cats',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Distinguishing Urine Marking From Undesirable Toileting in Cats. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/distinguishing-urine-marking-from-undesirable-toileting-in-cats',
    availability: 'verified-online',
  },
  'msd-controlled-exposure-dog': {
    id: 'msd-controlled-exposure-dog',
    title: 'General Guidelines for Effective Controlled Exposure Behavior Modification in Dogs',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. General Guidelines for Effective Controlled Exposure Behavior Modification in Dogs. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/general-guidelines-for-effective-controlled-exposure-behavior-modification-in-dogs',
    availability: 'verified-online',
  },
  'msd-medical-behavior-causes': {
    id: 'msd-medical-behavior-causes',
    title: 'Medical Causes of Behavioral Signs',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Medical Causes of Behavioral Signs. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/medical-causes-of-behavioral-signs',
    availability: 'verified-online',
  },
  'msd-reptile-lifespan': {
    id: 'msd-reptile-lifespan',
    title: 'Average Life Span of Reptiles in Captivity',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Average Life Span of Reptiles in Captivity. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/average-life-span-of-reptiles-in-captivity',
    availability: 'verified-online',
  },
  'msd-biting-behavior': {
    id: 'msd-biting-behavior',
    title: 'Biting in Small Animals and Pets',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Biting. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/biting',
    availability: 'verified-online',
  },
  'msd-rabbit-breeds': {
    id: 'msd-rabbit-breeds',
    title: 'Breeds of Rabbits',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Breeds of Rabbits. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/breeds-of-rabbits',
    availability: 'verified-online',
  },
  'msd-buying-first-rabbit': {
    id: 'msd-buying-first-rabbit',
    title: 'Buying Your First Rabbit (Physical Exam Checklist)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Buying Your First Rabbit. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/buying-your-first-rabbit',
    availability: 'verified-online',
  },
  'msd-mice-illness-signs': {
    id: 'msd-mice-illness-signs',
    title: 'Checking for Signs of Illness in Mice',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Checking for Signs of Illness in Mice. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/checking-for-signs-of-illness-in-mice',
    availability: 'verified-online',
  },
  'msd-chinchilla-care-checklist': {
    id: 'msd-chinchilla-care-checklist',
    title: 'Chinchilla Care Checklist',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Chinchilla Care Checklist. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/chinchilla-care-checklist',
    availability: 'verified-online',
  },
  'msd-fish-illness-signs': {
    id: 'msd-fish-illness-signs',
    title: 'Common Signs of Illness in Fish',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Signs of Illness in Fish. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-signs-of-illness-in-fish',
    availability: 'verified-online',
  },
  'msd-rats-illness-signs': {
    id: 'msd-rats-illness-signs',
    title: 'Common Signs of Illness in Rats',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Common Signs of Illness in Rats. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/common-signs-of-illness-in-rats',
    availability: 'verified-online',
  },
  'msd-ferret-zoonoses': {
    id: 'msd-ferret-zoonoses',
    title: 'Diseases Spread from Ferrets to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Ferrets to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-ferrets-to-people',
    availability: 'verified-online',
  },
  'msd-gerbil-zoonoses': {
    id: 'msd-gerbil-zoonoses',
    title: 'Diseases Spread from Gerbils to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Gerbils to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-gerbils-to-people',
    availability: 'verified-online',
  },
  'msd-hamster-zoonoses': {
    id: 'msd-hamster-zoonoses',
    title: 'Diseases Spread from Hamsters to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Hamsters to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-hamsters-to-people',
    availability: 'verified-online',
  },
  'msd-mice-zoonoses': {
    id: 'msd-mice-zoonoses',
    title: 'Diseases Spread from Mice to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Mice to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-mice-to-people',
    availability: 'verified-online',
  },
  'msd-pig-zoonoses': {
    id: 'msd-pig-zoonoses',
    title: 'Diseases Spread from Potbellied Pigs to Humans',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Potbellied Pigs to Humans. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-potbellied-pigs-to-humans',
    availability: 'verified-online',
  },
  'msd-rabbit-zoonoses': {
    id: 'msd-rabbit-zoonoses',
    title: 'Diseases Spread from Rabbits to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Rabbits to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-rabbits-to-people',
    availability: 'verified-online',
  },
  'msd-rat-zoonoses': {
    id: 'msd-rat-zoonoses',
    title: 'Diseases Spread from Rats to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Rats to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-rats-to-people',
    availability: 'verified-online',
  },
  'msd-reptile-zoonoses': {
    id: 'msd-reptile-zoonoses',
    title: 'Diseases Spread from Reptiles to People',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Diseases that can be Spread from Reptiles to People. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/diseases-that-can-be-spread-from-reptiles-to-people',
    availability: 'verified-online',
  },
  'msd-gerbil-illness-warning': {
    id: 'msd-gerbil-illness-warning',
    title: 'Early Warning Signs of Illness in Your Gerbil',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Early Warning Signs of Illness in Your Gerbil. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/early-warning-signs-of-illness-in-your-gerbil',
    availability: 'verified-online',
  },
  'msd-exotic-emergencies': {
    id: 'msd-exotic-emergencies',
    title: 'Emergencies in Exotic Pets and Small Animals',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Emergencies. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/emergencies',
    availability: 'verified-online',
  },
  'msd-safe-environment': {
    id: 'msd-safe-environment',
    title: 'Ensuring a Safe Environment for Small Animals',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Ensuring a Safe Environment. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/ensuring-a-safe-environment',
    availability: 'verified-online',
  },
  'msd-aquarium-maintenance': {
    id: 'msd-aquarium-maintenance',
    title: 'Essential Maintenance for Aquariums',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Essential Maintenance. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/essential-maintenance',
    availability: 'verified-online',
  },
  'msd-explaining-ph': {
    id: 'msd-explaining-ph',
    title: 'Explaining pH and Water Chemistry in Aquariums',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Explaining pH. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/explaining-ph',
    availability: 'verified-online',
  },
  'msd-feeding-sick-ferret': {
    id: 'msd-feeding-sick-ferret',
    title: 'Feeding a Sick Ferret (Nutritional Support Protocol)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Feeding a Sick Ferret. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/feeding-a-sick-ferret',
    availability: 'verified-online',
  },
  'msd-ferrets-glance': {
    id: 'msd-ferrets-glance',
    title: 'Ferrets at a Glance (Physiological & Reproductive Constants)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Ferrets at a Glance. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/ferrets-at-a-glance',
    availability: 'verified-online',
  },
  'msd-hamster-breeds': {
    id: 'msd-hamster-breeds',
    title: 'Hamster Breeds Commonly Kept as Pets',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Hamster Breeds Commonly Kept as Pets. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/hamster-breeds-commonly-kept-as-pets',
    availability: 'verified-online',
  },
  'msd-hamster-pregnancy': {
    id: 'msd-hamster-pregnancy',
    title: 'If Your Hamster is Pregnant (Reproductive & Maternal Care)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. If Your Hamster is Pregnant. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/if-your-hamster-is-pregnant',
    availability: 'verified-online',
  },
  'msd-amphibian-diseases': {
    id: 'msd-amphibian-diseases',
    title: 'Infectious Diseases of Amphibians',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Infectious Diseases of Amphibians. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/infectious-diseases-of-amphibians',
    availability: 'verified-online',
  },
  'msd-mice-glance': {
    id: 'msd-mice-glance',
    title: 'Mice at a Glance (Physiological & Reproductive Constants)',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Mice at a Glance. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/mice-at-a-glance',
    availability: 'verified-online',
  },
  'msd-rabbit-nutrition': {
    id: 'msd-rabbit-nutrition',
    title: 'Nutrient Requirements of Rabbits',
    organization: 'MSD Veterinary Manual',
    kind: 'guideline',
    year: 2026,
    citation: 'Merck & Co., Inc. Nutrient Requirements of Rabbits. MSD Veterinary Manual.',
    url: 'https://www.msdvetmanual.com/multimedia/table/nutrient-requirements-of-rabbits',
    availability: 'verified-online',
  },

  // ---- zoonoses sourcing pass, 2026-08-01 ----------------------------
  // Every identifier below was resolved against NCBI E-utilities or Crossref
  // and its title compared with the registered one before being written here.
  // Re-checkable at any time with: npm run verify:sources
  'pmid-20193207': {
    id: 'pmid-20193207',
    title: '[Complete genome sequencing and analyses of rabies viruses isolated from wild animals (Chinese Ferret-Badger) in Zhejiang province].',
    organization: 'Zhonghua Liu Xing Bing Xue Za Zhi',
    kind: 'primary-literature',
    year: 2009,
    pmid: '20193207',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20193207/',
    availability: 'verified-online',
  },
  'pmid-15885837': {
    id: 'pmid-15885837',
    title: 'Replication strategies of rabies virus.',
    organization: 'Virus Res',
    kind: 'primary-literature',
    year: 2005,
    pmid: '15885837',
    doi: '10.1016/j.virusres.2005.04.004',
    url: 'https://pubmed.ncbi.nlm.nih.gov/15885837/',
    availability: 'verified-online',
  },
  'pmid-34490393': {
    id: 'pmid-34490393',
    title: 'The Impact of Socioeconomic Factors on Knowledge, Attitudes, and Practices of Dog Owners on Dog Rabies Control in Thailand.',
    organization: 'Front Vet Sci',
    kind: 'primary-literature',
    year: 2021,
    pmid: '34490393',
    doi: '10.3389/fvets.2021.699352',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34490393/',
    availability: 'verified-online',
  },
  'pmid-11849687': {
    id: 'pmid-11849687',
    title: 'Distribution of rabies antigen in infected brain material: determining the reliability of different regions of the brain for the rabies fluorescent antibody test.',
    organization: 'J Virol Methods',
    kind: 'primary-literature',
    year: 2002,
    pmid: '11849687',
    doi: '10.1016/s0166-0934(01)00423-2',
    url: 'https://pubmed.ncbi.nlm.nih.gov/11849687/',
    availability: 'verified-online',
  },
  'pmid-29925781': {
    id: 'pmid-29925781',
    title: 'Additional Progress in the Development and Application of a Direct, Rapid Immunohistochemical Test for Rabies Diagnosis.',
    organization: 'Vet Sci',
    kind: 'primary-literature',
    year: 2018,
    pmid: '29925781',
    doi: '10.3390/vetsci5020059',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29925781/',
    availability: 'verified-online',
  },
  'pmid-35686145': {
    id: 'pmid-35686145',
    title: 'Factors affecting preventive behavior against leptospirosis among the population at risk in Si Sa Ket, Thailand.',
    organization: 'One Health',
    kind: 'primary-literature',
    year: 2022,
    pmid: '35686145',
    doi: '10.1016/j.onehlt.2022.100399',
    url: 'https://pubmed.ncbi.nlm.nih.gov/35686145/',
    availability: 'verified-online',
  },
  'pmid-31099522': {
    id: 'pmid-31099522',
    title: 'Spatial and statistical analysis of leptospirosis in Thailand from 2013 to 2015.',
    organization: 'Geospat Health',
    kind: 'primary-literature',
    year: 2019,
    pmid: '31099522',
    doi: '10.4081/gh.2019.739',
    url: 'https://pubmed.ncbi.nlm.nih.gov/31099522/',
    availability: 'verified-online',
  },
  'pmid-29284248': {
    id: 'pmid-29284248',
    title: 'Streptococcus suis: a re-emerging pathogen associated with occupational exposure to pigs or pork products. Part I - Epidemiology.',
    organization: 'Ann Agric Environ Med',
    kind: 'primary-literature',
    year: 2017,
    pmid: '29284248',
    doi: '10.26444/aaem/79813',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29284248/',
    availability: 'verified-online',
  },
  'pmid-24734186': {
    id: 'pmid-24734186',
    title: 'Correlation between PFGE Groups and mrp/epf/sly Genotypes of Human Streptococcus suis Serotype 2 in Northern Thailand.',
    organization: 'J Pathog',
    kind: 'primary-literature',
    year: 2014,
    pmid: '24734186',
    doi: '10.1155/2014/350416',
    url: 'https://pubmed.ncbi.nlm.nih.gov/24734186/',
    availability: 'verified-online',
  },
  'pmid-9204307': {
    id: 'pmid-9204307',
    title: 'Brucellosis: an overview.',
    organization: 'Emerg Infect Dis',
    kind: 'primary-literature',
    year: 1997,
    pmid: '9204307',
    doi: '10.3201/eid0302.970219',
    url: 'https://pubmed.ncbi.nlm.nih.gov/9204307/',
    availability: 'verified-online',
  },
  'pmid-27651083': {
    id: 'pmid-27651083',
    title: 'Incidence Patterns and Occupational Risk Factors of Human Brucellosis in Greece, 2004-2015.',
    organization: 'Int J Occup Environ Med',
    kind: 'primary-literature',
    year: 2016,
    pmid: '27651083',
    doi: '10.15171/ijoem.2016.806',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27651083/',
    availability: 'verified-online',
  },
  'pmid-23813816': {
    id: 'pmid-23813816',
    title: 'Bartonella species infection in cats: ABCD guidelines on prevention and management.',
    organization: 'J Feline Med Surg',
    kind: 'guideline',
    year: 2013,
    pmid: '23813816',
    doi: '10.1177/1098612X13489214',
    url: 'https://pubmed.ncbi.nlm.nih.gov/23813816/',
    availability: 'verified-online',
  },
  'pmid-28714909': {
    id: 'pmid-28714909',
    title: 'The Interplay between the Host Receptor and Influenza Virus Hemagglutinin and Neuraminidase.',
    organization: 'Int J Mol Sci',
    kind: 'primary-literature',
    year: 2017,
    pmid: '28714909',
    doi: '10.3390/ijms18071541',
    url: 'https://doi.org/10.3390/ijms18071541',
    availability: 'verified-online',
  },
  'pmid-15931279': {
    id: 'pmid-15931279',
    title: 'Birds, migration and emerging zoonoses: west nile virus, lyme disease, influenza A and enteropathogens.',
    organization: 'Clin Med Res',
    kind: 'primary-literature',
    year: 2003,
    pmid: '15931279',
    doi: '10.3121/cmr.1.1.5',
    url: 'https://doi.org/10.3121/cmr.1.1.5',
    availability: 'verified-online',
  },
  'pmid-28734617': {
    id: 'pmid-28734617',
    title: 'Epidemiology, Evolution, and Pathogenesis of H7N9 Influenza Viruses in Five Epidemic Waves since 2013 in China.',
    organization: 'Trends Microbiol',
    kind: 'primary-literature',
    year: 2017,
    pmid: '28734617',
    doi: '10.1016/j.tim.2017.06.008',
    url: 'https://doi.org/10.1016/j.tim.2017.06.008',
    availability: 'verified-online',
  },
  'pmid-23735535': {
    id: 'pmid-23735535',
    title: 'Natural history of highly pathogenic avian influenza H5N1.',
    organization: 'Virus Res',
    kind: 'primary-literature',
    year: 2013,
    pmid: '23735535',
    doi: '10.1016/j.virusres.2013.05.009',
    url: 'https://doi.org/10.1016/j.virusres.2013.05.009',
    availability: 'verified-online',
  },
  'pmid-9749297': {
    id: 'pmid-9749297',
    title: '[Influenza A (H5N1) in Hong Kong: Forerunner of a pandemic or just a scientifically interesting phenomenon and a useful exercise in pandemiology?].',
    organization: 'Ned Tijdschr Geneeskd',
    kind: 'primary-literature',
    year: 1998,
    pmid: '9749297',
    url: 'https://pubmed.ncbi.nlm.nih.gov/9749297/',
    availability: 'verified-online',
  },
  'pmid-10395870': {
    id: 'pmid-10395870',
    title: 'Case-control study of risk factors for avian influenza A (H5N1) disease, Hong Kong, 1997.',
    organization: 'J Infect Dis',
    kind: 'primary-literature',
    year: 1999,
    pmid: '10395870',
    doi: '10.1086/314903',
    url: 'https://doi.org/10.1086/314903',
    availability: 'verified-online',
  },
  'pmid-40165538': {
    id: 'pmid-40165538',
    title: 'Editorial: Rapid Testing for the Avian Influenza A(H5N1) Virus is Urgently Required as Infections in Poultry and Dairy Cows are on the Rise, and so is Transmission to Humans.',
    organization: 'Med Sci Monit',
    kind: 'primary-literature',
    year: 2025,
    pmid: '40165538',
    doi: '10.12659/MSM.949109',
    url: 'https://doi.org/10.12659/MSM.949109',
    availability: 'verified-online',
  },
  'pmid-28196963': {
    id: 'pmid-28196963',
    title: 'Genetic Predisposition To Acquire a Polybasic Cleavage Site for Highly Pathogenic Avian Influenza Virus Hemagglutinin.',
    organization: 'mBio',
    kind: 'primary-literature',
    year: 2017,
    pmid: '28196963',
    doi: '10.1128/mBio.02298-16',
    url: 'https://doi.org/10.1128/mBio.02298-16',
    availability: 'verified-online',
  },
  'pmid-27086031': {
    id: 'pmid-27086031',
    title: 'Porcine deltacoronavirus infection: Etiology, cell culture for virus isolation and propagation, molecular epidemiology and pathogenesis.',
    organization: 'Virus Res',
    kind: 'primary-literature',
    year: 2016,
    pmid: '27086031',
    doi: '10.1016/j.virusres.2016.04.009',
    url: 'https://doi.org/10.1016/j.virusres.2016.04.009',
    availability: 'verified-online',
  },
  'pmid-14647384': {
    id: 'pmid-14647384',
    title: 'Angiotensin-converting enzyme 2 is a functional receptor for the SARS coronavirus.',
    organization: 'Nature',
    kind: 'primary-literature',
    year: 2003,
    pmid: '14647384',
    doi: '10.1038/nature02145',
    url: 'https://doi.org/10.1038/nature02145',
    availability: 'verified-online',
  },
  'pmid-23486063': {
    id: 'pmid-23486063',
    title: 'Dipeptidyl peptidase 4 is a functional receptor for the emerging human coronavirus-EMC.',
    organization: 'Nature',
    kind: 'primary-literature',
    year: 2013,
    pmid: '23486063',
    doi: '10.1038/nature12005',
    url: 'https://doi.org/10.1038/nature12005',
    availability: 'verified-online',
  },
  'pmid-32015507': {
    id: 'pmid-32015507',
    title: 'A pneumonia outbreak associated with a new coronavirus of probable bat origin.',
    organization: 'Nature',
    kind: 'primary-literature',
    year: 2020,
    pmid: '32015507',
    doi: '10.1038/s41586-020-2012-7',
    url: 'https://doi.org/10.1038/s41586-020-2012-7',
    availability: 'verified-online',
  },
  'pmid-12958366': {
    id: 'pmid-12958366',
    title: 'Isolation and characterization of viruses related to the SARS coronavirus from animals in southern China.',
    organization: 'Science',
    kind: 'primary-literature',
    year: 2003,
    pmid: '12958366',
    doi: '10.1126/science.1087139',
    url: 'https://doi.org/10.1126/science.1087139',
    availability: 'verified-online',
  },
  'pmid-23933067': {
    id: 'pmid-23933067',
    title: 'Middle East respiratory syndrome coronavirus neutralising serum antibodies in dromedary camels: a comparative serological study.',
    organization: 'Lancet Infect Dis',
    kind: 'primary-literature',
    year: 2013,
    pmid: '23933067',
    doi: '10.1016/S1473-3099(13)70164-6',
    url: 'https://doi.org/10.1016/S1473-3099(13)70164-6',
    availability: 'verified-online',
  },
  'pmid-24896817': {
    id: 'pmid-24896817',
    title: 'Evidence for camel-to-human transmission of MERS coronavirus.',
    organization: 'N Engl J Med',
    kind: 'primary-literature',
    year: 2014,
    pmid: '24896817',
    doi: '10.1056/NEJMoa1401505',
    url: 'https://doi.org/10.1056/NEJMoa1401505',
    availability: 'verified-online',
  },
  'pmid-32269068': {
    id: 'pmid-32269068',
    title: 'Susceptibility of ferrets, cats, dogs, and other domesticated animals to SARS-coronavirus 2.',
    organization: 'Science',
    kind: 'primary-literature',
    year: 2020,
    pmid: '32269068',
    doi: '10.1126/science.abb7015',
    url: 'https://doi.org/10.1126/science.abb7015',
    availability: 'verified-online',
  },
  'pmid-26086337': {
    id: 'pmid-26086337',
    title: 'The Potential Use of Wolbachia-Based Mosquito Biocontrol Strategies for Japanese Encephalitis.',
    organization: 'PLoS Negl Trop Dis',
    kind: 'primary-literature',
    year: 2015,
    pmid: '26086337',
    doi: '10.1371/journal.pntd.0003576',
    url: 'https://doi.org/10.1371/journal.pntd.0003576',
    availability: 'verified-online',
  },
  'pmid-35746679': {
    id: 'pmid-35746679',
    title: 'The Emergence of Japanese Encephalitis Virus in Australia in 2022: Existing Knowledge of Mosquito Vectors.',
    organization: 'Viruses',
    kind: 'primary-literature',
    year: 2022,
    pmid: '35746679',
    doi: '10.3390/v14061208',
    url: 'https://doi.org/10.3390/v14061208',
    availability: 'verified-online',
  },
  'pmid-31310198': {
    id: 'pmid-31310198',
    title: 'Rift Valley fever: biology and epidemiology.',
    organization: 'J Gen Virol',
    kind: 'primary-literature',
    year: 2019,
    pmid: '31310198',
    doi: '10.1099/jgv.0.001296',
    url: 'https://doi.org/10.1099/jgv.0.001296',
    availability: 'verified-online',
  },
  'pmid-35073355': {
    id: 'pmid-35073355',
    title: 'Paving the way for human vaccination against Rift Valley fever virus: A systematic literature review of RVFV epidemiology from 1999 to 2021.',
    organization: 'PLoS Negl Trop Dis',
    kind: 'primary-literature',
    year: 2022,
    pmid: '35073355',
    doi: '10.1371/journal.pntd.0009852',
    url: 'https://doi.org/10.1371/journal.pntd.0009852',
    availability: 'verified-online',
  },
  'pmid-27207312': {
    id: 'pmid-27207312',
    title: 'Epidemiological and clinical aspects on West Nile virus, a globally emerging pathogen.',
    organization: 'Infect Dis (Lond)',
    kind: 'primary-literature',
    year: 2016,
    pmid: '27207312',
    doi: '10.3109/23744235.2016.1164890',
    url: 'https://doi.org/10.3109/23744235.2016.1164890',
    availability: 'verified-online',
  },
  'pmid-36918725': {
    id: 'pmid-36918725',
    title: 'Crimean-Congo haemorrhagic fever virus.',
    organization: 'Nat Rev Microbiol',
    kind: 'primary-literature',
    year: 2023,
    pmid: '36918725',
    doi: '10.1038/s41579-023-00871-9',
    url: 'https://doi.org/10.1038/s41579-023-00871-9',
    availability: 'verified-online',
  },
  'pmid-32891500': {
    id: 'pmid-32891500',
    title: 'Emerging Tickborne Viral Infections: What Wilderness Medicine Providers Need to Know.',
    organization: 'Wilderness Environ Med',
    kind: 'primary-literature',
    year: 2020,
    pmid: '32891500',
    doi: '10.1016/j.wem.2020.06.011',
    url: 'https://doi.org/10.1016/j.wem.2020.06.011',
    availability: 'verified-online',
  },
  'pmid-6801762': {
    id: 'pmid-6801762',
    title: 'Novel proteinaceous infectious particles cause scrapie.',
    organization: 'Science',
    kind: 'primary-literature',
    year: 1982,
    pmid: '6801762',
    doi: '10.1126/science.6801762',
    url: 'https://doi.org/10.1126/science.6801762',
    availability: 'verified-online',
  },
  'pmid-16798390': {
    id: 'pmid-16798390',
    title: 'Kuru in the 21st century--an acquired human prion disease with very long incubation periods.',
    organization: 'Lancet',
    kind: 'primary-literature',
    year: 2006,
    pmid: '16798390',
    doi: '10.1016/S0140-6736(06)68930-7',
    url: 'https://doi.org/10.1016/S0140-6736(06)68930-7',
    availability: 'verified-online',
  },
  'pmid-9333239': {
    id: 'pmid-9333239',
    title: 'Transmissions to mice indicate that \'new variant\' CJD is caused by the BSE agent.',
    organization: 'Nature',
    kind: 'primary-literature',
    year: 1997,
    pmid: '9333239',
    doi: '10.1038/39057',
    url: 'https://doi.org/10.1038/39057',
    availability: 'verified-online',
  },
  'pmid-23449776': {
    id: 'pmid-23449776',
    title: 'Prion infectivity in the spleen of a PRNP heterozygous individual with subclinical variant Creutzfeldt-Jakob disease.',
    organization: 'Brain',
    kind: 'primary-literature',
    year: 2013,
    pmid: '23449776',
    doi: '10.1093/brain/awt032',
    url: 'https://doi.org/10.1093/brain/awt032',
    availability: 'verified-online',
  },
  'pmid-1688299': {
    id: 'pmid-1688299',
    title: 'Bovine spongiform encephalopathy: a neuropathological perspective.',
    organization: 'Brain Pathol',
    kind: 'primary-literature',
    year: 1991,
    pmid: '1688299',
    doi: '10.1111/j.1750-3639.1991.tb00642.x',
    url: 'https://doi.org/10.1111/j.1750-3639.1991.tb00642.x',
    availability: 'verified-online',
  },
  'pmid-27109462': {
    id: 'pmid-27109462',
    title: 'Review: A review on classical and atypical scrapie in caprine: Prion protein gene polymorphisms and their role in the disease.',
    organization: 'Animal',
    kind: 'primary-literature',
    year: 2016,
    pmid: '27109462',
    doi: '10.1017/S1751731116000653',
    url: 'https://doi.org/10.1017/S1751731116000653',
    availability: 'verified-online',
  },
  'pmid-34823556': {
    id: 'pmid-34823556',
    title: 'Chronic wasting disease in Europe: new strains on the horizon.',
    organization: 'Acta Vet Scand',
    kind: 'primary-literature',
    year: 2021,
    pmid: '34823556',
    doi: '10.1186/s13028-021-00606-x',
    url: 'https://doi.org/10.1186/s13028-021-00606-x',
    availability: 'verified-online',
  },
  'guide-woah-world-organisat-2023': {
    id: 'guide-woah-world-organisat-2023',
    title: 'Manual of Diagnostic Tests and Vaccines for Terrestrial Animals (Terrestrial Manual), Chapter 3.1.18. Rabies (infection with rabies virus and other lyssaviruses)',
    organization: 'WOAH (World Organisation for Animal Health)',
    kind: 'guideline',
    year: 2023,
    url: 'https://www.woah.org/fileadmin/Home/eng/Health_standards/tahm/3.01.18_RABIES.pdf',
    availability: 'named',
  },
};

/** Resolve a SourceRef to its Source record (or null if it points at a
 *  lecture-note locator rather than an external source). */
export function resolveSource(ref) {
  if (!ref) return null;
  return SOURCES[ref.sourceId] || null;
}

export const ALL_SOURCE_IDS = Object.keys(SOURCES);
