// ============================================================
// Landing i18n dictionary (en / th)
// ============================================================
// Verbatim from design_handoff_vetmock_landing, plus a few honest
// keys the real auth flow needs (magic-link states, errors) that the
// design's fake 6-digit-OTP flow didn't have.
// Clinical / technical terms stay English in both languages.
// ============================================================

export const DICT = {
  en: {
    start: 'Start Practicing', signIn: 'Sign In', muteLabel: 'Sound',
    nav: [{ label: 'Practice', href: '#solution' }, { label: 'Progress', href: '#progress' }, { label: 'Lab', href: '#lab' }, { label: 'Panic Mode', href: '#panic' }, { label: 'Subjects', href: '#subjects' }],
    ctxChip: 'CUVET / Y4 / S1 Midterm',
    heroEyebrow: 'Built for veterinary students',
    heroPre: 'Practice before the ', heroEm: 'real exam.', heroPost: '',
    heroSub: 'Study with the veterinary question bank, timed exam mode, detailed explanations, progress tracking, and practical image stations — all available in VetMock today.',
    heroCta1: 'Start Exam Mode', heroCta2: 'Browse Subjects', heroTrust: 'Free — no credit card. Start practising immediately.',
    // Hero stat labels. The VALUES are derived from the shipped question
    // bank in LandingBody — never hand-typed marketing numbers.
    statQuestions: 'Questions', statSubjects: 'Subjects', statFree: 'Cost', statFreeValue: 'Free',
    heroWords: ['subject practice', 'timed exam mode', 'wrong-answer review', 'spaced repetition'],
    heroFocusLine: 'Choose a study tool:',
    heroBankLabel: 'Question bank', heroBankLine: 'Sample question from the shipped veterinary question bank',
    floats: ['Clinical reasoning', 'Timed practice', 'Instant explanation', 'Weak-topic detection'],
    heroTag: 'Small Animal Med — Endocrine',
    heroQ: 'A 7-year-old Labrador Retriever presents with polyuria, polydipsia, abdominal distension, and bilateral symmetrical alopecia. Which diagnostic test is the most appropriate next step?',
    heroExplain: 'The signalment and signs — PU/PD, a pot-bellied abdomen, and endocrine (bilaterally symmetrical) alopecia — point to hyperadrenocorticism (Cushing’s). The LDDST is the screening test of choice, with the highest sensitivity for spontaneous disease.',
    heroConfQ: 'How confident are you?', conf: ['Guessing', 'Unsure', 'Confident'],
    check: 'Check answer', reset: 'Reset demo', demoNote: 'Interactive demo — this doesn’t affect your progress.',
    previewBadge: 'Preview', labDemoNote: 'Sample station — for demonstration.', weakPreviewNote: 'Example insights — what VetMock surfaces once you’ve practised.',
    correct: 'Correct', wrong: 'Not quite', why: 'Why',
    navTitle: 'Exam progress', legAnswered: 'Answered', legCurrent: 'Current', legFlagged: 'Flagged',
    trustLabel: 'Why VetMock',
    trust: ['Designed around real veterinary examination formats', 'Built specifically for veterinary students', 'Practice written and visual questions in one place', 'Review explanations immediately after each session'],
    probLabel: 'The problem', probHead: 'Reading everything is not the same as being ready.',
    problems: [
      { emoji: '📖', title: 'You remember the lecture, but can’t answer the question', body: 'Knowledge feels familiar — until the choices look almost identical.' },
      { emoji: '🔬', title: 'Lab exams are hard to practise alone', body: 'Slides, radiographs, specimens, and clinical images need repeated visual exposure.' },
      { emoji: '⏳', title: 'You find your weak topics too late', body: 'Without realistic practice, it’s hard to know what you truly understand.' },
    ],
    solLabel: 'The solution',
    solPre: 'One place to practise like it’s the ', solEm: 'real exam.', solPost: '',
    solSub: 'Two core ways to train — timed written questions and image-based practical stations — with an explanation after every answer.',
    mockName: 'Exam Mode', mockDesc: 'Take realistic, timed examinations built around veterinary subjects and clinical scenarios.',
    // Every bullet here must be a shipped capability (no "Difficulty
    // selection" — questions carry no difficulty field and the exam config
    // has no such control).
    mockBullets: ['Timed and untimed modes', 'Subject-specific exams', 'Detailed answer explanations', 'Question bookmarking'],
    labFName: 'Lab Practice', labFDesc: 'Train your visual recognition and practical examination skills through image-based questions.',
    labExamples: [{ emoji: '🔬', label: 'Histopathology slides' }, { emoji: '🩻', label: 'Radiographic images' }, { emoji: '🪱', label: 'Parasitology specimens' }, { emoji: '🦴', label: 'Anatomy identification' }, { emoji: '🦠', label: 'Microbiology results' }, { emoji: '🐕', label: 'Clinical photographs' }],
    panicLabel: 'When time is short', panicHead: 'Exam tomorrow?',
    panicCalm: 'Take a breath. Here’s the most efficient way to use the time you have left.',
    panicDesc: 'Panic Mode turns the highest-yield topics into a focused revision session based on the time you have left.',
    panicTimeQ: 'How much time do you have left?',
    panicTimes: [{ key: '15', label: '15 minutes' }, { key: '30', label: '30 minutes' }, { key: '60', label: '1 hour' }, { key: 'tonight', label: 'Tonight' }],
    panicPlanTitle: 'Your revision set',
    panicStatConcepts: 'Essential concepts', panicStatTraps: 'Common traps', panicStatQ: 'High-yield Q', panicStatWeak: 'Weak topics',
    panicFocusTitle: 'Prioritised for you', panicCta: 'Enter Panic Mode', panicFocus: PANIC_LABELS(),
    howLabel: 'How it works', howHead: 'From “I read it” to “I’ve got it.”',
    steps: [
      { title: 'Choose what you’re preparing for', body: 'Select a subject, examination type, or practical lab.' },
      { title: 'Practise under realistic conditions', body: 'Answer questions with optional timers, confidence ratings, and exam settings.' },
      { title: 'Understand every mistake', body: 'Review explanations, find your weak topics, and practise them again.' },
    ],
    subjLabel: 'Question bank',
    subjPre: 'Every subject, from ', subjEm: 'preclinical to clinical.', subjPost: '',
    subjSub: 'Structured questions across preclinical, paraclinical, and clinical veterinary subjects.',
    subjRealNote: 'Live now — real question counts. Pick one to start practising.',
    subjShowcaseNote: 'The full subject map VetMock is built around.',
    subjToggleReal: 'Practise now', subjToggleShowcase: 'See all subjects',
    tabs: [{ key: 'all', label: 'All' }, { key: 'preclinical', label: 'Preclinical' }, { key: 'paraclinical', label: 'Paraclinical' }, { key: 'clinical', label: 'Clinical' }],
    qWord: 'questions', startPractice: 'Start practising',
    labSecLabel: 'Lab simulation', labSecHead: 'Practical exams require practical preparation.',
    labSecSub: 'OSPE-style stations that recreate the laboratory bench — a diagnostic image, a prompt, and a countdown. Move from one station to the next.',
    labStation: 'Station 3 — Diagnostic Imaging',
    labPrompt: 'Identify the radiographic abnormality and select the most likely diagnosis.',
    labExplain: 'A dorsally elevated cardiac silhouette with left atrial enlargement and a caudodorsal interstitial-to-alveolar pattern is classic for cardiogenic pulmonary oedema in the dog.',
    labNext: 'Next station', labImgPlaceholder: 'Radiograph preview',
    toolAnnotate: 'Annotate', toolMeasure: 'Measure', toolReset: 'Reset view',
    aLabel: 'Performance Insights', aHead: 'Know what to study next.', progressTitle: 'Progress',
    aSub: 'VetMock turns each practice session into a clear picture of your strengths, weak areas, and exam readiness.',
    aSample: 'Sample dashboard',
    aStatLabels: ['Overall accuracy', 'Questions completed', 'Strongest subject', 'Weakest subject'],
    aStatVals: ['68%', '1,240', 'Pharmacology', 'Parasitology'],
    aConfTitle: 'Confidence vs correctness', aConfConfident: 'When confident', aConfUnsure: 'When unsure',
    aActivityTitle: 'Recent activity', aActivitySub: 'questions / day', aDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    aMasteryTitle: 'Topic mastery',
    rLabel: 'Exam readiness', rHeadPre: 'Your ', rHeadEm: 'readiness score', rHeadPost: ', at a glance.',
    rScoreWord: 'Readiness score', rMsg: 'On track — keep closing the gaps.',
    rMetricLabels: ['Knowledge coverage', 'Question accuracy', 'Practical recognition', 'Time management', 'Consistency'],
    rDisclaimer: 'A study-progress indicator — not a prediction or guarantee of your actual examination result.',
    weakLabel: 'Weakness detection', weakHead: 'VetMock notices the patterns you miss.', weakSub: 'Every session updates a picture of how you think — then turns it into focused practice.', weakCta: 'Open VetMock to practise weak topics',
    weaknessCards: [
      { tag: 'Pattern', text: 'You often confuse hyperadrenocorticism with hypothyroidism.', color: 'var(--clr-gold)' },
      { tag: 'Accuracy', text: 'Your accuracy drops on questions that require diagnostic test selection.', color: 'var(--clr-rose)' },
      { tag: 'Visual', text: 'Thoracic radiographic pattern recognition needs more practice.', color: 'var(--clr-ocean)' },
      { tag: 'Speed', text: 'You answer pharmacology accurately — but slowly.', color: 'var(--clr-sage)' },
    ],
    ctaPre: 'Your first attempt shouldn’t be in the ', ctaEm: 'exam room.', ctaPost: '',
    ctaSub: 'Start practising with realistic veterinary questions and walk into your next exam knowing what to expect.',
    cta1: 'Start Practicing', cta2: 'View Subjects',
    footTagline: 'Built for veterinary students.',
    footIndependent: 'VetMock is an independent study tool. Not affiliated with any faculty, university, or examination board.',
    footLinks: [{ label: 'Practice', href: '#solution' }, { label: 'Lab', href: '#lab' }, { label: 'Panic Mode', href: '#panic' }, { label: 'Subjects', href: '#subjects' }, { label: 'About', href: '#why' }],
    copyright: '© 2026 VetMock',
    ckHead: 'Can we remember where you left off?',
    ckBody: 'VetMock uses essential cookies to keep the platform working and remember your study context. Optional cookies help us improve the learning experience.',
    ckAccept: 'Sounds good', ckEssential: 'Essential only', ckPrefs: 'Choose preferences', ckSave: 'Save preferences', ckAlways: 'Always on',
    ckEssentialT: 'Essential', ckEssentialD: 'Sign-in, security, and remembering your study context.',
    ckAnalyticsT: 'Product analytics', ckAnalyticsD: 'Helps us see which features actually help students learn.',
    ckPersonalT: 'Personalisation', ckPersonalD: 'Remembers your year, semester, exam period, and interface preferences.',
    lgHead: 'Pick up where you left off.', lgBody: 'Your curriculum, recent cases, saved mistakes, and study context will be ready.',
    lgGoogle: 'Continue with Google', lgGuest: 'Continue as guest', lgPassword: 'Sign in with a password', lgEmailLabel: 'Email',
    lgSend: 'Email me a sign-in link', lgSending: 'Sending…', lgOr: 'or',
    lgCtx: 'CUVET / Year 4 / Semester 1 Midterm', lgSaved: 'Your study context will be saved',
    lgReturn: 'Continue where you stopped', lgReturnCase: 'Decision 7 of 12',
    lgSentHead: 'Check your inbox', lgSentBody: 'We sent a sign-in link to', lgSentHint: 'Open it on this device to continue.',
    lgSentTip: 'The link signs you in — no code to type. It expires shortly, so use it soon.',
    lgResend: 'Resend link', lgBack: 'Use another email', lgVerify: 'Verify and continue',
    lgIndependent: 'Independent platform — not an official university sign-in. We store your study context, never patient records.',
    lgErrEmail: 'Enter a valid email address.', lgErrRate: 'Too many attempts — wait a moment and try again.',
    lgErrNoUser: 'No account for this email yet. Use "Sign in with a password" to create one.', lgErrGeneric: 'Couldn’t send the link. Please try again.',
  },
  th: {
    start: 'เริ่มฝึกเลย', signIn: 'เข้าสู่ระบบ', muteLabel: 'เสียง',
    nav: [{ label: 'ฝึกทำโจทย์', href: '#solution' }, { label: 'ความคืบหน้า', href: '#progress' }, { label: 'แล็บ', href: '#lab' }, { label: 'Panic Mode', href: '#panic' }, { label: 'รายวิชา', href: '#subjects' }],
    ctxChip: 'CUVET / ปี 4 / เทอม 1 กลางภาค',
    heroEyebrow: 'สร้างเพื่อนักศึกษาสัตวแพทย์',
    heroPre: 'ลุยโจทย์ให้ชิน ก่อนเข้า', heroEm: 'ห้องสอบจริง', heroPost: '',
    heroSub: 'อ่านและฝึกจากคลังข้อสอบสัตวแพทย์ ใช้โหมดสอบแบบจับเวลา อ่านเฉลย ติดตามความคืบหน้า และฝึกสถานีภาพ — ทุกอย่างนี้เปิดใช้งานได้จริงใน VetMock',
    heroCta1: 'เริ่มโหมดสอบ', heroCta2: 'ดูรายวิชา', heroTrust: 'ฟรี ไม่ต้องใช้บัตรเครดิต เริ่มฝึกได้ทันที',
    statQuestions: 'ข้อสอบ', statSubjects: 'รายวิชา', statFree: 'ค่าใช้จ่าย', statFreeValue: 'ฟรี',
    heroWords: ['ฝึกแยกรายวิชา', 'โหมดสอบจับเวลา', 'ทบทวนข้อที่ตอบผิด', 'Spaced Repetition'],
    heroFocusLine: 'เลือกเครื่องมือที่ต้องการ:',
    heroBankLabel: 'คลังข้อสอบ', heroBankLine: 'โจทย์ตัวอย่างจากคลังข้อสอบที่เปิดใช้งานจริง',
    floats: ['การให้เหตุผลทางคลินิก', 'ฝึกแบบจับเวลา', 'เฉลยทันที', 'ตรวจจับหัวข้อที่อ่อน'],
    heroTag: 'Small Animal Med — Endocrine',
    heroQ: 'สุนัขพันธุ์ Labrador Retriever อายุ 7 ปี มาด้วยอาการ polyuria, polydipsia, ท้องกาง และ bilateral symmetrical alopecia — ควรส่งตรวจอะไรเป็นลำดับถัดไปเหมาะสมที่สุด?',
    heroExplain: 'อาการ PU/PD ท้องกางแบบ pot-belly และ endocrine alopecia ที่สมมาตรสองข้าง ชี้ไปที่ hyperadrenocorticism (Cushing’s) — LDDST เป็น screening test ที่ไวที่สุด และเป็น test of choice สำหรับโรคที่เกิดเอง',
    heroConfQ: 'มั่นใจแค่ไหน?', conf: ['เดา', 'ไม่แน่ใจ', 'มั่นใจ'],
    previewBadge: 'ตัวอย่าง', labDemoNote: 'สถานีตัวอย่าง เพื่อการสาธิต', weakPreviewNote: 'ตัวอย่างของสิ่งที่ VetMock จะบอกเมื่อคุณฝึกไปสักพัก', check: 'ตรวจคำตอบ', reset: 'ลองใหม่', demoNote: 'เดโมทดลอง ไม่มีผลกับความคืบหน้าของคุณ',
    correct: 'ถูกต้อง', wrong: 'ยังไม่ใช่', why: 'เฉลย',
    navTitle: 'ความคืบหน้า', legAnswered: 'ตอบแล้ว', legCurrent: 'ข้อนี้', legFlagged: 'ปักหมุด',
    trustLabel: 'ทำไมต้อง VetMock',
    trust: ['ออกแบบตามรูปแบบข้อสอบสัตวแพทย์จริง', 'สร้างมาเพื่อนักศึกษาสัตวแพทย์โดยเฉพาะ', 'ฝึกทั้งข้อเขียนและข้อภาพในที่เดียว', 'อ่านเฉลยได้ทันทีหลังฝึกจบ'],
    probLabel: 'ปัญหาที่เจอ', probHead: 'อ่านครบทุกอย่าง ไม่เท่ากับพร้อมสอบ',
    problems: [
      { emoji: '📖', title: 'จำเลกเชอร์ได้ แต่พอเจอโจทย์กลับตอบไม่ได้', body: 'ความรู้เหมือนคุ้นเคยดี จนกระทั่งตัวเลือกมันคล้ายกันไปหมด' },
      { emoji: '🔬', title: 'สอบแล็บ ฝึกเองคนเดียวยาก', body: 'สไลด์ ฟิล์ม specimen และภาพ clinical ต้องเห็นซ้ำ ๆ บ่อย ๆ ถึงจะจำได้' },
      { emoji: '⏳', title: 'กว่าจะรู้ว่าอ่อนตรงไหน ก็สายไปแล้ว', body: 'ถ้าไม่ได้ลองทำโจทย์จริง ๆ ก็ยากที่จะรู้ว่าเข้าใจจริงหรือแค่คิดว่าเข้าใจ' },
    ],
    solLabel: 'ทางออก',
    solPre: 'ที่เดียว ฝึกให้เหมือน', solEm: 'สอบจริง', solPost: '',
    solSub: 'ฝึกสองรูปแบบหลัก — ข้อเขียนแบบจับเวลา และสถานีภาพแบบปฏิบัติ — พร้อมเฉลยหลังตอบทุกข้อ',
    mockName: 'โหมดสอบ', mockDesc: 'ทำข้อสอบเสมือนจริงแบบจับเวลา อิงตามรายวิชาและ clinical scenario ทางสัตวแพทย์',
    mockBullets: ['โหมดจับเวลาและไม่จับเวลา', 'ข้อสอบแยกตามรายวิชา', 'เฉลยละเอียดทุกข้อ', 'บุ๊กมาร์กข้อที่อยากกลับมาดู'],
    labFName: 'Lab Practice', labFDesc: 'ฝึกการดูภาพและทักษะสอบปฏิบัติ ผ่านโจทย์ที่ใช้ภาพจริง',
    labExamples: [{ emoji: '🔬', label: 'Histopathology slides' }, { emoji: '🩻', label: 'Radiographic images' }, { emoji: '🪱', label: 'Parasitology specimens' }, { emoji: '🦴', label: 'Anatomy identification' }, { emoji: '🦠', label: 'Microbiology results' }, { emoji: '🐕', label: 'Clinical photographs' }],
    panicLabel: 'เมื่อเวลาเหลือน้อย', panicHead: 'พรุ่งนี้สอบแล้ว?',
    panicCalm: 'หายใจเข้าลึก ๆ แล้วเราจะช่วยจัดให้คุ้มที่สุดกับเวลาที่เหลือ',
    panicDesc: 'Panic Mode จะจัดหัวข้อ high-yield ที่สำคัญที่สุด ให้เป็นแผนทบทวนแบบโฟกัส ตามเวลาที่คุณเหลือ',
    panicTimeQ: 'เหลือเวลาเท่าไหร่?',
    panicTimes: [{ key: '15', label: '15 นาที' }, { key: '30', label: '30 นาที' }, { key: '60', label: '1 ชั่วโมง' }, { key: 'tonight', label: 'คืนนี้' }],
    panicPlanTitle: 'ชุดทบทวนของคุณ',
    panicStatConcepts: 'คอนเซ็ปต์สำคัญ', panicStatTraps: 'กับดักที่ออกบ่อย', panicStatQ: 'โจทย์ high-yield', panicStatWeak: 'หัวข้อที่อ่อน',
    panicFocusTitle: 'จัดให้ตามจุดอ่อนของคุณ', panicCta: 'เข้าสู่ Panic Mode', panicFocus: PANIC_LABELS(),
    howLabel: 'ใช้งานยังไง', howHead: 'จาก “อ่านแล้ว” เป็น “เข้าใจแล้ว”',
    steps: [
      { title: 'เลือกสิ่งที่กำลังจะสอบ', body: 'เลือกวิชา ประเภทข้อสอบ หรือแล็บปฏิบัติ' },
      { title: 'ฝึกในเงื่อนไขเหมือนจริง', body: 'ทำโจทย์พร้อมตัวจับเวลา ระดับความมั่นใจ และการตั้งค่าแบบห้องสอบ' },
      { title: 'เข้าใจทุกข้อที่ผิด', body: 'อ่านเฉลย หาหัวข้อที่อ่อน แล้วกลับมาฝึกซ้ำ' },
    ],
    subjLabel: 'คลังโจทย์',
    subjPre: 'ครบทุกวิชา ตั้งแต่ ', subjEm: 'preclinical ถึง clinical', subjPost: '',
    subjSub: 'โจทย์จัดหมวดครบ ทั้งวิชา preclinical, paraclinical และ clinical',
    subjRealNote: 'เปิดให้ฝึกแล้ว จำนวนข้อจริง เลือกวิชาเพื่อเริ่มฝึกได้เลย',
    subjShowcaseNote: 'ภาพรวมรายวิชาทั้งหมดที่ VetMock ออกแบบไว้',
    subjToggleReal: 'ฝึกเลย', subjToggleShowcase: 'ดูรายวิชาทั้งหมด',
    tabs: [{ key: 'all', label: 'ทั้งหมด' }, { key: 'preclinical', label: 'Preclinical' }, { key: 'paraclinical', label: 'Paraclinical' }, { key: 'clinical', label: 'Clinical' }],
    qWord: 'ข้อ', startPractice: 'เริ่มฝึก',
    labSecLabel: 'จำลองสอบแล็บ', labSecHead: 'สอบปฏิบัติ ต้องเตรียมแบบปฏิบัติ',
    labSecSub: 'สถานีแบบ OSPE ที่จำลองโต๊ะแล็บจริง — มีภาพวินิจฉัย โจทย์ และเวลานับถอยหลัง เปลี่ยนจากสถานีหนึ่งไปอีกสถานี',
    labStation: 'สถานีที่ 3 — Diagnostic Imaging',
    labPrompt: 'ระบุความผิดปกติในภาพรังสี แล้วเลือก diagnosis ที่เป็นไปได้มากที่สุด',
    labExplain: 'เงาหัวใจยกตัวติด sternum ร่วมกับ left atrial enlargement และ interstitial-to-alveolar pattern บริเวณ caudodorsal เป็นภาพคลาสสิกของ cardiogenic pulmonary oedema ในสุนัข',
    labNext: 'สถานีถัดไป', labImgPlaceholder: 'ตัวอย่างภาพรังสี',
    toolAnnotate: 'ทำเครื่องหมาย', toolMeasure: 'วัดระยะ', toolReset: 'รีเซ็ตภาพ',
    aLabel: 'สรุปผลการฝึก', aHead: 'รู้ว่าควรอ่านอะไรต่อ', progressTitle: 'ความคืบหน้า',
    aSub: 'VetMock เปลี่ยนทุกครั้งที่ฝึก ให้เป็นภาพรวมชัด ๆ ว่าคุณเก่งตรงไหน อ่อนตรงไหน และพร้อมสอบแค่ไหน',
    aSample: 'ตัวอย่างแดชบอร์ด',
    aStatLabels: ['ความแม่นโดยรวม', 'จำนวนข้อที่ทำ', 'วิชาที่แข็งสุด', 'วิชาที่อ่อนสุด'],
    aStatVals: ['68%', '1,240', 'Pharmacology', 'Parasitology'],
    aConfTitle: 'ความมั่นใจ vs ความถูกต้อง', aConfConfident: 'ตอนมั่นใจ', aConfUnsure: 'ตอนไม่แน่ใจ',
    aActivityTitle: 'กิจกรรมล่าสุด', aActivitySub: 'ข้อ / วัน', aDays: ['จ.', 'อ.', 'พ.', 'พฤ.', 'ศ.', 'ส.', 'อา.'],
    aMasteryTitle: 'ความเชี่ยวชาญรายหัวข้อ',
    rLabel: 'ความพร้อมสอบ', rHeadPre: 'ดู ', rHeadEm: 'คะแนนความพร้อม', rHeadPost: 'ของคุณแบบรวดเดียว',
    rScoreWord: 'คะแนนความพร้อม', rMsg: 'มาถูกทางแล้ว ค่อย ๆ อุดจุดอ่อนต่อไป',
    rMetricLabels: ['ความครอบคลุมเนื้อหา', 'ความแม่นในการตอบ', 'การจำภาพ/ปฏิบัติ', 'การบริหารเวลา', 'ความสม่ำเสมอ'],
    rDisclaimer: 'เป็นตัวชี้วัดความคืบหน้าในการอ่าน ไม่ใช่การทำนายหรือรับประกันผลสอบจริง',
    weakLabel: 'ตรวจจับจุดอ่อน', weakHead: 'VetMock เห็นแพตเทิร์นที่คุณพลาดบ่อย', weakSub: 'ทุกครั้งที่ฝึกจะอัปเดตภาพว่าคุณคิดยังไง แล้วเปลี่ยนเป็นชุดฝึกที่โฟกัส', weakCta: 'เข้าแอปเพื่อฝึกหัวข้อที่อ่อน',
    weaknessCards: [
      { tag: 'Pattern', text: 'คุณมักสับสนระหว่าง hyperadrenocorticism กับ hypothyroidism', color: 'var(--clr-gold)' },
      { tag: 'Accuracy', text: 'ความแม่นของคุณลดลงในข้อที่ต้องเลือก diagnostic test', color: 'var(--clr-rose)' },
      { tag: 'Visual', text: 'การอ่าน pattern ภาพรังสีทรวงอก ยังต้องฝึกเพิ่ม', color: 'var(--clr-ocean)' },
      { tag: 'Speed', text: 'คุณตอบ pharmacology ได้แม่น แต่ช้า', color: 'var(--clr-sage)' },
    ],
    ctaPre: 'ครั้งแรกที่ลองทำ ไม่ควรเป็นตอนอยู่ใน', ctaEm: 'ห้องสอบ', ctaPost: '',
    ctaSub: 'เริ่มฝึกกับโจทย์สัตวแพทย์เสมือนจริง แล้วเดินเข้าห้องสอบครั้งหน้าแบบรู้ว่าจะเจออะไร',
    cta1: 'เริ่มฝึกเลย', cta2: 'ดูรายวิชา',
    footTagline: 'สร้างเพื่อนักศึกษาสัตวแพทย์',
    footIndependent: 'VetMock เป็นเครื่องมือฝึกอิสระ ไม่ได้สังกัดคณะ มหาวิทยาลัย หรือหน่วยงานจัดสอบใด ๆ',
    footLinks: [{ label: 'ฝึกทำโจทย์', href: '#solution' }, { label: 'แล็บ', href: '#lab' }, { label: 'Panic Mode', href: '#panic' }, { label: 'รายวิชา', href: '#subjects' }, { label: 'เกี่ยวกับ', href: '#why' }],
    copyright: '© 2026 VetMock',
    ckHead: 'ให้เราจำที่ที่คุณค้างไว้ได้ไหม?',
    ckBody: 'VetMock ใช้คุกกี้ที่จำเป็นเพื่อให้ระบบทำงานและจำบริบทการเรียนของคุณ ส่วนคุกกี้เสริมช่วยให้เราปรับปรุงประสบการณ์การเรียนให้ดีขึ้น',
    ckAccept: 'โอเคเลย', ckEssential: 'เฉพาะที่จำเป็น', ckPrefs: 'เลือกเอง', ckSave: 'บันทึกการตั้งค่า', ckAlways: 'เปิดตลอด',
    ckEssentialT: 'จำเป็น', ckEssentialD: 'การเข้าสู่ระบบ ความปลอดภัย และการจำบริบทการเรียนของคุณ',
    ckAnalyticsT: 'วิเคราะห์การใช้งาน', ckAnalyticsD: 'ช่วยให้เราเห็นว่าฟีเจอร์ไหนช่วยการเรียนได้จริง',
    ckPersonalT: 'ปรับแต่งเฉพาะคุณ', ckPersonalD: 'จำปี เทอม ช่วงสอบ และการตั้งค่าหน้าจอของคุณ',
    lgHead: 'กลับมาต่อจากที่ค้างไว้', lgBody: 'หลักสูตร เคสล่าสุด ข้อที่พลาด และบริบทการเรียนของคุณ พร้อมแล้ว',
    lgGoogle: 'เข้าสู่ระบบด้วย Google', lgGuest: 'ใช้งานแบบผู้เยี่ยมชม', lgPassword: 'เข้าสู่ระบบด้วยรหัสผ่าน', lgEmailLabel: 'อีเมล',
    lgSend: 'ส่งลิงก์เข้าสู่ระบบให้ฉัน', lgSending: 'กำลังส่ง…', lgOr: 'หรือ',
    lgCtx: 'CUVET / ปี 4 / เทอม 1 กลางภาค', lgSaved: 'บริบทการเรียนของคุณจะถูกบันทึกไว้',
    lgReturn: 'ไปต่อจากที่หยุดไว้', lgReturnCase: 'ตัดสินใจข้อ 7 จาก 12',
    lgSentHead: 'เช็กอีเมลของคุณ', lgSentBody: 'เราส่งลิงก์เข้าสู่ระบบไปที่', lgSentHint: 'เปิดลิงก์บนเครื่องนี้เพื่อไปต่อ',
    lgSentTip: 'ลิงก์จะพาเข้าสู่ระบบเลย ไม่ต้องกรอกรหัส ลิงก์มีอายุจำกัด ใช้ให้เร็วนะ',
    lgResend: 'ส่งลิงก์ใหม่', lgBack: 'ใช้อีเมลอื่น', lgVerify: 'ยืนยันและไปต่อ',
    lgIndependent: 'แพลตฟอร์มอิสระ — ไม่ใช่การเข้าสู่ระบบทางการของมหาวิทยาลัย เราเก็บบริบทการเรียนของคุณ ไม่เก็บข้อมูลผู้ป่วย',
    lgErrEmail: 'กรอกอีเมลให้ถูกต้อง', lgErrRate: 'ลองบ่อยเกินไป รอสักครู่แล้วลองใหม่',
    lgErrNoUser: 'ยังไม่มีบัญชีสำหรับอีเมลนี้ ใช้ "เข้าสู่ระบบด้วยรหัสผ่าน" เพื่อสมัคร', lgErrGeneric: 'ส่งลิงก์ไม่สำเร็จ ลองอีกครั้ง',
  },
};

// Shared (language-independent) focus labels for Panic Mode.
function PANIC_LABELS() {
  return ['Canine hyperadrenocorticism', 'GnRH agonists vs antagonists', 'IMHA — saline agglutination', 'Rumenotomy — left flank approach', 'Poultry drug withdrawal times', 'Status epilepticus — first-line'];
}
