// Every generated module is rebuilt by an npm regen:* script, and several of
// those scripts import another one's output: regen:q-counts reads the delivery
// list and, through lib/exam-scope.js, the exam-paper table. The pipeline doc
// used to list q-counts before both, so an ingest done by the book built its
// per-paper counts from the previous run's inputs. regen:all is the one order
// to run; this test derives each generator's inputs from its import graph and
// each generated file's generator from the file's own header, so a new
// generator or a new import is checked without editing the test.
import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const rel = (file) => path.relative(repo, file).replace(/\\/g, '/');
const { scripts } = JSON.parse(fs.readFileSync(path.join(repo, 'package.json'), 'utf8'));

// `npm run a && npm run b -- --x` → [{ name: 'a', args: '' }, { name: 'b', args: '--x' }]
const stepsOf = (chain) => chain.split(' && ').map((part) => {
  const m = /^npm run ([\w:-]+)(?: -- (.+))?$/.exec(part.trim());
  assert.ok(m, `unexpected step "${part}"`);
  return { name: m[1], args: m[2] ?? '' };
});
const scriptFileOf = (name) => /^node (scripts\/[\w.-]+\.m?js)(?:\s|$)/.exec(scripts[name] ?? '')?.[1];

// A template literal counts when its path is static; only a cache-busting
// query may be interpolated (`../src/lib/vetwiki/index.js?t=${Date.now()}`).
const IMPORTS = [
  /\bfrom\s*['"]([^'"\n]+)['"]/g,
  /\bimport\s*\(\s*[`'"]([^`'"$?\n]+)(?:\?[^`'"\n]*)?[`'"]\s*\)/g,
  /\bimport\s+['"]([^'"\n]+)['"]/g,
  /new URL\(\s*[`'"]([^`'"$?\n]+)(?:\?[^`'"\n]*)?[`'"]\s*,\s*import\.meta\.url/g,
];
// Scripts also load modules through path.join(ROOT, 'src/...').
const ROOT_PATHS = /['"]((?:src|api)\/[^'"\s]+\.m?js)['"]/g;

const sources = new Map();
const sourceOf = (file) => {
  if (!sources.has(file)) sources.set(file, fs.readFileSync(file, 'utf8'));
  return sources.get(file);
};

function directImports(file) {
  const text = sourceOf(file);
  const found = new Set();
  for (const pattern of IMPORTS) {
    for (const [, spec] of text.matchAll(pattern)) {
      if (spec.startsWith('.')) found.add(path.resolve(path.dirname(file), spec.split('?')[0]));
    }
  }
  for (const [, p] of text.matchAll(ROOT_PATHS)) found.add(path.join(repo, p));
  return [...found].filter((f) => fs.existsSync(f) && fs.statSync(f).isFile());
}

const closures = new Map();
function closureOf(entry) {
  if (closures.has(entry)) return closures.get(entry);
  const seen = new Set();
  const queue = [entry];
  while (queue.length) {
    const file = queue.pop();
    if (seen.has(file)) continue;
    seen.add(file);
    if (/\.m?js$/.test(file)) queue.push(...directImports(file));
  }
  seen.delete(entry);
  closures.set(entry, seen);
  return seen;
}

// The step that writes `file`, read from the file's own header
// ("GENERATED by scripts/x.mjs", "Run `npm run regen:x`").
function writerOf(file, steps) {
  if (!/\.m?js$/.test(file)) return null;
  const header = sourceOf(file).split('\n').slice(0, 15).join('\n');
  if (!/generated|auto-derived|regenerate/i.test(header)) return null;
  const m = /npm run (regen:[\w-]+)|scripts\/([\w.-]+\.mjs)/.exec(header);
  if (!m) return null;
  if (m[1]) return steps.find((s) => s.name === m[1])?.name ?? null;
  return steps.find((s) => scriptFileOf(s.name) === `scripts/${m[2]}`)?.name ?? null;
}

function orderProblems(steps) {
  const position = new Map(steps.map((s, i) => [s.name, i]));
  const problems = [];
  steps.forEach((step, i) => {
    const file = scriptFileOf(step.name);
    if (!file) return;
    for (const dep of closureOf(path.join(repo, file))) {
      const writer = writerOf(dep, steps);
      if (!writer || writer === step.name) continue;
      if (position.get(writer) > i) problems.push(`${step.name} reads ${rel(dep)}, which ${writer} writes later`);
    }
  });
  return problems;
}

test('regen:all runs every generator once, and rewrites the stats last', () => {
  assert.equal(typeof scripts['regen:all'], 'string', 'package.json must define regen:all');
  const steps = stepsOf(scripts['regen:all']);
  const names = steps.map((s) => s.name);
  assert.equal(new Set(names).size, names.length, 'no generator runs twice');
  const generators = Object.keys(scripts).filter((k) => k.startsWith('regen:') && k !== 'regen:all');
  assert.deepEqual(generators.filter((g) => !names.includes(g)), [], 'every regen:* script belongs in regen:all');
  // stats reads the bank registry and the q-counts tables through a template
  // import this test cannot follow, so it goes after everything.
  assert.deepEqual(steps.at(-1), { name: 'stats', args: '--write' });
});

test('regen:all runs each generator after every generator whose output it imports', () => {
  assert.deepEqual(orderProblems(stepsOf(scripts['regen:all'])), []);
});

test('the order the pipeline doc used to give is caught', () => {
  const documented = 'npm run regen:registry && npm run regen:q-counts && npm run regen:delivery'
    + ' && npm run regen:written-questions && npm run regen:glossary-related'
    + ' && npm run regen:citation-index && npm run regen:conflict-summary'
    + ' && npm run regen:notes-registry && npm run regen:exam-papers && npm run regen:video-meta';
  const problems = orderProblems(stepsOf(documented));
  assert.ok(problems.includes(
    'regen:q-counts reads src/data/question-delivery.generated.js, which regen:delivery writes later',
  ), problems.join('\n'));
  assert.ok(problems.includes(
    'regen:q-counts reads src/data/exam-papers.generated.js, which regen:exam-papers writes later',
  ), problems.join('\n'));
});

test('the gate detects stale files and never regenerates them', () => {
  for (const name of ['gate', 'build', 'lint:all', 'test:unit']) {
    assert.doesNotMatch(scripts[name], /regen:all/, `${name} must not run regen:all`);
  }
});

test('the pipeline doc regenerates with regen:all', () => {
  const doc = fs.readFileSync(path.join(repo, 'docs/EXAM-SUBJECT-PIPELINE.md'), 'utf8');
  assert.match(doc, /npm run regen:all/);
  assert.doesNotMatch(doc, /regen:registry regen:q-counts/, 'the hand-ordered list must not come back');
});
